### PR TITLE
cleanup: Remove Bloom filter optimization

### PR DESCRIPTION
**Pull request by IagoAbal**
Follows: 2428d17ee7c ("Disable Bloom filter optimization by default (#6197)")

It was probably more impactful when it was first introduced, but the engine has evolved and nowadays it does not seem to have a noticeable impact on performance. We disabled it by default on Sep 2022 and this went completely unnoticed.

What triggered this was that the Bloom filter had tricky interactions with const-prop and sym-prop, see #4670, and PA-1920 (or PR #6179).

Ran p/default on 30 repos from stress-test-monorepo with some interesting results, removing -bloom_filter caused an average speedup of 1.15x, and 9 repos in particular particularly benefited with an average speedup of 1.35x (PowerShell, cpython, flask, hadoop, kubernetes, maven, metabase, mypy, react)! Perhaps this could be due to removing `s_strings` from `stmt` in Generic AST?

test plan:
make test

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
Need to update some script because there's one legitimate CI failure (you can ignore the one for JS).

**Review by aryx — APPROVED** [review]
I wonder if we could store somewhere in a comment a trace of our use of bloom filter; just so that in 1 year if someone come with the idea of using a Bloom filter, he can see in the code
it might not be such a good idea.

**Comment by IagoAbal** [comment]
> I wonder if we could store somewhere in a comment a trace of our use of bloom filter; just so that in 1 year if someone come with the idea of using a Bloom filter, he can see in the code
> it might not be such a good idea.

Yeah I agree, but where to put it?

**Comment by IagoAbal** [comment]
> > I wonder if we could store somewhere in a comment a trace of our use of bloom filter; just so that in 1 year if someone come with the idea of using a Bloom filter, he can see in the code
> > it might not be such a good idea.
> 
> Yeah I agree, but where to put it?

Added a note to the `stmt` type in AST_generic.

**Pull request merged**
