### PR TITLE
Use new interface for timeouts

### PR DESCRIPTION
**Pull request by mjambon**
`set_timeout` now returns an option rather than raising an exception.

See https://github.com/returntocorp/pfff/pull/458 for details.

Makes https://github.com/returntocorp/semgrep/pull/3599 unnecessary.

PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Comment by mjambon** [comment]
Looks like I broke ruby:
```
E           (TODO: 0) semgrep-rules/ruby/lang/security/weak-hashes-md5.yaml
E           	✖ weak-hashes-md5                                              TP: 0 TN: 0 FP: 0 FN: 9
E           	test: /tmp/pytest-of-runner/pytest-0/popen-gw0/test_semgrep_rules_repo0/semgrep-rules/ruby/lang/security/weak-hashes-md5.rb, expected lines: [5, 7, 9, 11, 14, 16, 18, 20, 22], reported lines: []
E           (TODO: 0) semgrep-rules/ruby/lang/security/nested-attributes.yaml
E           	✖ nested-attributes                                            TP: 0 TN: 0 FP: 0 FN: 1
E           	test: /tmp/pytest-of-runner/pytest-0/popen-gw0/test_semgrep_rules_repo0/semgrep-rules/ruby/lang/security/nested-attributes.rb, expected lines: [6], reported lines: []
E           (TODO: 0) semgrep-rules/ruby/lang/security/model-attributes-attr-protected.yaml
E           	✖ model-attributes-attr-protected                              TP: 0 TN: 1 FP: 0 FN: 1
E           	test: /tmp/pytest-of-runner/pytest-0/popen-gw0/test_semgrep_rules_repo0/semgrep-rules/ruby/lang/security/model-attributes-attr-protected.rb, expected lines: [3], reported lines: []
E           (TODO: 0) semgrep-rules/ruby/lang/security/timing-attack.yaml
E           	✖ timing-attack                                                TP: 0 TN: 0 FP: 0 FN: 2
E           	test: /tmp/pytest-of-runner/pytest-0/popen-gw0/test_semgrep_rules_repo0/semgrep-rules/ruby/lang/security/timing-attack.rb, expected lines: [3, 5], reported lines: []
E           (TODO: 0) semgrep-rules/ruby/lang/security/cookie-serialization.yaml
E           	✖ cookie-serialization                                         TP: 0 TN: 0 FP: 0 FN: 2
E           	test: /tmp/pytest-of-runner/pytest-0/popen-gw0/test_semgrep_rules_repo0/semgrep-rules/ruby/lang/security/cookie-serialization.rb, expected lines: [3, 5], reported lines: []
E           (TODO: 0) semgrep-rules/ruby/lang/security/weak-hashes-sha1.yaml
E           	✖ weak-hashes-sha1                                             TP: 0 TN: 3 FP: 0 FN: 10
```

**Comment by IagoAbal** [comment]
Might this be because of a previously unnoticed nested `timeout_function` ? Pfff's `Parse_ruby.parse` has a `timeout_function` which may be nested with the one set by Semgrep's `Main`.

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
Yes for the Ruby we need to do like for JS and make the timeout a parameter of the parsing
function that can be disabled by the caller.

**Comment by aryx** [comment]
But this is great we now can detect that (dynamically)!

**Pull request merged**
