### PR TITLE
ci: allow libpcre2 to be dynamically linked

### PR DESCRIPTION
**Pull request by kopecs**
Based off of discussion with @amchiclet and @mjambon we should just dynamically link pcre2 on MacOS due to the issues it creates in the build when attempting to statically link, and the fact that we essentially rely on it being available at runtime via `git` regardless.

### CODE REVIEW

**Comment by mjambon** [comment]
I approve of the PR description. Not sure what's going on with the steps that can't find the dynamic library.

**Review by mjambon — APPROVED** [review]

**Comment by amchiclet** [comment]
I'm debugging the missing libraries now.

**Comment by amchiclet** [comment]
For `build-test-osx-x86`, we could probably just be ok when pcre2 is not in `/usr/bin`.

For `build-test-osx-arm64`, I'm guessing the environment that tests the python wheel doesn't have pcre2 installed.

**Review by aryx — CHANGES_REQUESTED** [review]
I'd rather not merge this, or document clearly what's wrong with statically linking libpcre2?
We do that for all the other libraries, why we should suddently dynamically link for libpcre2?

**Comment by amchiclet** [comment]
I think this particular PR can be closed.

Last week we decided to [revert the pcre2 PR](https://github.com/semgrep/semgrep/pull/10064) until we find the best solution moving forward. One solution moving forward is to dynamically link the library. If we can link statically without breaking opam (which uses git, which uses pcre2), that would probably work too.

**Comment by aryx** [comment]
What we can do @kopecs is maybe to move the dynamic library to a different directory, and use LD_LIBRARY_PATH to dynamically allows opam/git to find it, but not gcc.

**Comment by aryx** [comment]
Or we can find the actual right way to link statically on macos X without using this hack of removing the dynamic libraries ... it was a hack; maybe now there is a proper way to use static linking in macos

**Comment by kopecs** [comment]
Sure. Is there a reasonable way to test this which isn't going to require a bunch of back and forth with github actions? I believe my normal build just dynamically links --- I am not really a fan of the fact that what we do locally is so different because it creates last-minute issues like this.

**Comment by aryx** [comment]
If you have a mac, you can the scripts that are run from CI.

**Pull request closed without merging**
