### PR TITLE
updated readme with new products

### PR DESCRIPTION
**Pull request by s-santillan**
PR checklist:

- (n/a) Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- (n/a) Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
**I did not make any edits to code**
- [x] Change has no security implications (otherwise, ping security team)

Update README with current products.

### CODE REVIEW

**Review by pabloest — APPROVED** [review]

**Comment by aryx** [comment]
I understand this must have been done quickly, but the precommit checks are failing on this PR, which means
now all our PRs are failing because this thing was committed.
Please use pre-commit locally next time.

**Comment by s-santillan** [comment]
@aryx Sorry about that. Should I redo anything with the pre-commit step?

**Comment by aryx** [comment]
You can run pre-commit run -a, and submit the modifications

**Comment by aryx** [comment]
you need to install pre-commit first (it's explained in our doc)

**Comment by s-santillan** [comment]
Done: https://github.com/returntocorp/semgrep/pull/7154

Happy to report that that the pre-commit jobs are green now (but CircleCI is not.)

**Pull request merged**
