### PR TITLE
feat(taint): Provide taint traces in semgrep's JSON output

### PR DESCRIPTION
**Pull request by nmote**
Test plan: Automated tests

For the Semgrep App integration, log in, then add this rule to my board: https://semgrep.dev/orgs/-/editor/s/XO6q

Download the test file for that rule, then run:

`python -m semgrep ci --dry-run --include test.js`

Observe in the JSON output that the `dataflow_trace` field on the finding appears as expected: https://gist.github.com/nmote/5ad538b49697cc483680f54e49ddf57a

PR checklist:

- [x] Documentation is up-to-date
- [x] `changelog.d/<issue>.<type>` is a file with the _what_, _why_, and _how_ of the change.
  - \<issue> is `pa-312` (Linear ticket), `gh-1234` (GitHub issue), or `new-gizmo` (unique semantic name)
  - \<type> is `added`, `changed`, `fixed`, or `infra`.
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see the [Contribution guidelines](https://semgrep.dev/docs/contributing/how-to-contribute/)!

### CODE REVIEW

**Comment by nmote** [comment]
Now updated with traces in the App output, too! I didn't realize that was separate from the ordinary JSON output. Thanks @brendongo for letting me know.

I'm hoping that this is exercised by a snapshot test, but otherwise I'll have to figure out how to manually test that output.

**Comment by nmote** [comment]
Since no tests failed when I changed the Semgrep App output, I figured out how to manually test it and updated the test plan accordingly.

**Comment by brendongo** [comment]
I would have expected https://github.com/returntocorp/semgrep/blob/develop/cli/tests/e2e/test_ci.py#L406 to fail actually

**Comment by brendongo** [comment]
Oh it's cause that test isnt using a taint rule nvm

**Review by brendongo — APPROVED** [review]
I would feel more comfortable with a test that verifies the to_app_finding_format output but I think we can add that in once we stabilize this dataflow trace output since we might need to adjust depending on what we need on app-side anyway.

**Comment by nmote** [comment]
Sounds good! I filed a linear ticket so I don't forget: https://linear.app/r2c/issue/PA-1611/add-automated-test-for-taint-traces-in-the-semgrep-app-output

**Review by IagoAbal — APPROVED** [review]
Nice!

**Pull request merged**
