### PR TITLE
chore: delete deepexprstmt generic test

### PR DESCRIPTION
**Pull request by brandonspark**
**What:**
The `deep_exprstmt.generic` test is wrong, it says that there should be findings, and there are not. This borks the cheatsheet regenerating script, which expects findings. Also, it doesn't really make sense to do a deep expr-stmt thing on a Generic file.

**Why:**
We should fix this so we don't have wrong tests, and also so we can regenerate the cheatsheet.

**How:**
I deleted the file.

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
Why this has become an issue? How old is this file? What broke?

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
Those tests were maybe not even run?

**Comment by brandonspark** [comment]
> Those tests were maybe not even run?

Yes, these tests were not run. The suite of tests which goes through and finds tests with their associated `.sgrep` files seems to not visit the `POLYGLOT` folder, so these tests are not automatically run (though they are checked by the cheatsheet script).

**Comment by aryx** [comment]
The POLYGLOT directory is used by the testsuite. It's to factorize .sgrep file that are the same with different languages.
For example when we see a tests/java/foo.java test file, we look for tests/java/foo.sgrep for the pattern, but if it's not there we look for tests/POLYGLOT/foo.sgrep.

**Pull request merged**
