### PR TITLE
fix(test): fix php parsing errors in test

### PR DESCRIPTION
**Pull request by ihji**
PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by akuhlens — APPROVED** [review]
This looks fine to me. One of the parse errors seems to marked to succeed and the other to fail. I would be interested to see if that needs changing too. 

Also there is the question of what has changed to surface this error, and why has it just now changed? It seems like it didn't use to cause a parse failure to forget a semi colon. I wonder why it does now.

**Comment by ihji** [comment]
> This looks fine to me. One of the parse errors seems to marked to succeed and the other to fail. I would be interested to see if that needs changing too.
> 
> Also there is the question of what has changed to surface this error, and why has it just now changed? It seems like it didn't use to cause a parse failure to forget a semi colon. I wonder why it does now.

The parsing error appears to have been present for months, but it has recently become noticeable. While I'm not sure of the root cause, my priority is to fix the error since it is causing issues with local testing for developers. The PHP code without the semicolon is considered invalid by the PHP tree sitter grammar, so it definitely needs to be fixed.

**Comment by ihji** [comment]
Merged with the `benchmarks-full` testing error, as it is unrelated to the current change.

**Comment by aryx** [comment]
yes would be great to know why the error got triggered just now ... What changed recently that caused that to suddently happen????

**Pull request merged**
