### PR TITLE
Add ruby tests to semgrep-core

### PR DESCRIPTION
**Pull request by minusworld**

### CODE REVIEW

**Comment by mschwager** [comment]
Noice! Looks like everything but `regexp_string` works!

**Comment by minusworld** [comment]
> Noice! Looks like everything but `regexp_string` works!

Yeah and that was because I put the `# ERROR` comment in the semgrep pattern file 🤦‍♂️

**Review by ievans — APPROVED** [review]
Hurray for tests, thank you @minusworld for filling these out! 

Can you make a separate PR to update semgrep.live with the cheatsheet.json generated by running `generate_test_matrix.py`?

**Comment by minusworld** [comment]
> Hurray for tests, thank you @minusworld for filling these out!
> 
> Can you make a separate PR to update semgrep.live with the cheatsheet.json generated by running `generate_test_matrix.py`?

Is that in this repo or in `semgrep-app`?

**Pull request merged**
