### PR TITLE
ResolvedName of dotted_ident -> GlobalName of string list

### PR DESCRIPTION
**Pull request by aryx**
This is the PR for a possible resolution of the
ResolvedName and metavariable mess.
The idea is to not store tokens anymore for resolved names
(now rename to GlobalName), because anyway the tokens
in it can come from different files, or contain tokens whose
range might contain keywords (e.g., in import {bar} from foo).
We want to move away from tokens anyway as a general principle,
and prefer proper pretty printing.

test plan:
make test, and hope for no regression in semgrep.
At some point also test in deep-semgrep and test
with the new testsuite brandon is preparing covering
more edge cases of interactions between resolved names
and metavariable-regex: and metavariable-pattern:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
wat? this works now?

**Comment by aryx** [comment]
Apparently lewis did some change to the react-href rule and test files so now no more regressions :)

**Comment by aryx** [comment]
@iago can I merge?

**Review by IagoAbal — APPROVED** [review]

**Comment by IagoAbal** [comment]
This closes #4185 (I believe).

**Pull request merged**
