### PR TITLE
Check performance impact of always running the GC alarm

### PR DESCRIPTION
**Pull request by mjambon**
PR checklist:
- [ ] documentation is up to date
- [ ] changelog is up to date

### CODE REVIEW

**Comment by aryx** [comment]
At least we can disable it by default and when people get a segfault they can turn it on, get something slower but working at least .. or can give us a better bug report than just segfault.

**Comment by aryx** [comment]
Still we should ask on discuss.ocaml how to improve this or get the Stack_overflow working also on macOS reliably.

**Comment by mjambon** [comment]
oh, that code calls `Gc.compact ()` at the end of each run. That seems like a bad idea. I'll check.

**Comment by mjambon** [comment]
yup, that was it. We can call `Gc.compact ()` only when catching an `Out_of_memory` exception, although I'm not sure it's the right thing to do. Perhaps `Gc.full_major ()` would be just fine. It probably doesn't matter.

**Pull request closed without merging**
