### PR TITLE
Use 'make test' to run pytest tests in CI

### PR DESCRIPTION
**Pull request by mjambon**
This PR reduces discrepancies between what's used in CI and the old `make test` command that runs pytest tests.
* the default `make test` command in `/cli` is now the reference and it is used by CI jobs. It used to be `make test-for-ci`.
* the old `make test` is now `make test-dev`. It's for developers who want tests to fail faster. The main issue that prevents us from merging the two is that not all the tests will run if a test fails in the "quick" or in the "kinda_slow" groups. In CI, we want all the tests to run and get a complete recap at the end. See todo comments in the makefile.
* the old pytest command used in CI was selecting fewer tests (1567 vs. 1728) than when explicitly passing a folder as an argument. ~~We don't know why.~~ This was fixed by configuring pytest to run by default on `/cli/tests/default` instead of some selection of folders. This moved a lot of files from `/cli/tests/` to `/cli/tests/default/`.
* the old pytest command used in CI wasn't checking that all the tests had a speed marker. This is fixed.

Various tests were using paths of the form `TESTS_PATH / "e2e" / "targets"` and I had to update it everywhere. Now it uses a variable `TARGETS_PATH` instead. Same with rules and `RULES_PATH`.

### CODE REVIEW

**Review by aryx — COMMENTED** [review]
I'd rather not add yet another subfolder like default/.

Why not make cli/tests/ this default
and move the performance and aq tests, which are not run by default elsewhere?

**Comment by aryx** [comment]
This would avoid all those renamings and avoid some merge conflicts (which you have right now ...)

**Review by aryx — CHANGES_REQUESTED** [review]
move instead cli/tests/qa/ and cli/tests/performance out of there.

**Comment by aryx** [comment]
maybe in cli/perf/, just like for semgrep-core we have /tests and /perf/

**Comment by mjambon** [comment]
> move instead cli/tests/qa/ and cli/tests/performance out of there.

I didn't do this because `conftest.py` and other config files are in `tests/`. Somehow we need one folder for the conf, one subfolder for the default tests and other subfolders for the other tests.

**Review by aryx — APPROVED** [review]

**Pull request merged**
