### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by dmitris**

### CODE REVIEW

**Comment by aryx** [comment]
Thx @dmitris Did you find time to sign the CLA? I know it's a bit ridiculous for just a typo fix, but hopefully you can contribute more things later and the CLA will be useful.

**Comment by dmitris** [comment]
@aryx thanks for asking, still waiting on an internal approval to sign it...  - hope to be able to sign it soon!

**Comment by dmitris** [comment]
@aryx emailed the signed CLA. Joyeux Noël et une bonne année! 😄

**Comment by ievans** [comment]
rx'd CLA, thanks @dmitris! @cla-bot check

**Review by ievans — APPROVED** [review]

**Pull request merged**
