### PR TITLE
Update upload docker instructions

### PR DESCRIPTION
**Pull request by brendongo**
PR checklist:
- [ ] documentation is up to date
- [ ] changelog is up to date

### CODE REVIEW

**Review by raghavjain3 — APPROVED** [review]

**Review by ievans — CHANGES_REQUESTED** [review]
What's the next step after this? How do I use the rule? How is it namedspaced? Can it be deleted? Will it be overwritten if I upload again?

**Comment by raghavjain3** [comment]
> What's the next step after this? How do I use the rule? How is it namedspaced? Can it be deleted? Will it be overwritten if I upload again?

I'll add this

**Comment by raghavjain3** [comment]
@ievans @brendongo I created this PR to answer those questions within our documentation https://github.com/returntocorp/semgrep-docs/pull/256

The goal is to have this be our source of truth so once information goes out, I'll update this Github README with a link to that section of the documentation.

**Comment by raghavjain3** [comment]
@ievans @brendongo I created this PR to answer those questions within our documentation https://github.com/returntocorp/semgrep-docs/pull/256

I'll update this Github README with a link to that section of the documentation.

**Comment by ievans** [comment]
Sounds great @raghavjain3 !

**Review by ievans — APPROVED** [review]

**Pull request merged**
