### PR TITLE
fix(pro): fix the timeout set in CI

### PR DESCRIPTION
**Pull request by emjin**
Test plan: run the docker image on one of the repos that currently times out.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by emjin** [comment]
TODO: need to document all of these resource limits

**Comment by emjin** [comment]
Tested on one of the repos that previously times out, it works!

**Comment by nmote** [comment]
Wait, so reducing the timeout makes something that previously timed out no longer time out? Am I reading that right?

**Comment by emjin** [comment]
Previously one of the semgrep pro runs would hit the github actions timeout and not return any results. Now, it hits our timeout first and gives up on interfile analysis, instead running a normal analysis and reporting back results.

**Review by nmote — APPROVED** [review]

**Pull request merged**
