### PR TITLE
Remove rules-file

### PR DESCRIPTION
**Pull request by emjin**
Remove `-rules_file` and the corresponding code `semgrep_with_patterns` and `semgrep_with_patterns_file`, since `-config` is strictly better. 

This also removes functionality for running `semgrep-core -f -json` or `semgrep-core -e -json`, since it is always possible to put the pattern in a config file. `-json` is not necessary for `semgrep -e`

Test plan:

semgrep -e:

```
➜  semgrep git:(EJ-remove-rules-file) semgrep -e '$X == $Y' perf/run-benchmarks --lang=py
perf/run-benchmarks
95:        return self.str == other.str
--------------------------------------------------------------------------------
134:    if variant_name == STD and timings is not None:
--------------------------------------------------------------------------------
134:    if variant_name == STD and timings is not None:
--------------------------------------------------------------------------------
274:    if status == 0:
--------------------------------------------------------------------------------
276:    elif status == 3:
--------------------------------------------------------------------------------
498:                if variant.name == STD:
--------------------------------------------------------------------------------
498:                if variant.name == STD:
--------------------------------------------------------------------------------
654:if __name__ == "__main__":
ran 1 rules on 1 files: 8 findings
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
➜  semgrep git:(EJ-remove-rules-file) sc -e '$X == $Y' perf/run-benchmarks -lang python -json
Uncaught exception:
  
  (Failure "To run with JSON, please use -config")

Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Common.finalize in file "src/pfff/commons/Common.ml", line 614, characters 14-18
Re-raised at Common.finalize in file "src/pfff/commons/Common.ml", line 619, characters 4-11
Called from Common.main_boilerplate.(fun) in file "src/pfff/commons/Common.ml", line 1603, characters 12-16
Called from Common.pp_do_in_zero_box in file "src/pfff/commons/Common.ml", line 1571, characters 45-49
Called from Common.finalize in file "src/pfff/commons/Common.ml", line 614, characters 14-18
Re-raised at Common.finalize in file "src/pfff/commons/Common.ml", line 619, characters 4-11
Called from Common.exn_to_real_unixexit in file "src/pfff/commons/Common.ml", line 1568, characters 6-10
Called from Dune__exe__Main in file "src/cli/Main.ml", line 1424, characters 2-148
```

semgrep -f:

```
➜  semgrep git:(EJ-remove-rules-file) semgrep -f semgrep-core/tests/OTHER/rules/settings.yaml semgrep-core/tests/OTHER/rules/settings.js   
running 1 rules...
semgrep-core/tests/OTHER/rules/settings.js
severity:warning rule:semgrep-core.tests.OTHER.rules.test-options: Working!
7:    foo(1);
ran 1 rules on 1 files: 1 findings
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
```

semgrep --config
```
➜  semgrep git:(EJ-remove-rules-file) semgrep --config semgrep-core/tests/OTHER/rules/settings.yaml semgrep-core/tests/OTHER/rules/settings.js
running 1 rules...
semgrep-core/tests/OTHER/rules/settings.js
severity:warning rule:semgrep-core.tests.OTHER.rules.test-options: Working!
7:    foo(1);
ran 1 rules on 1 files: 1 findings
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
```

sc -e

```
➜  semgrep git:(EJ-remove-rules-file) sc -e '$X == $Y' perf/run-benchmarks -lang python perf/run-benchmarks:95
         return self.str == other.str
perf/run-benchmarks:134
     if variant_name == STD and timings is not None:
perf/run-benchmarks:134
     if variant_name == STD and timings is not None:
perf/run-benchmarks:274
     if status == 0:
perf/run-benchmarks:276
     elif status == 3:
perf/run-benchmarks:498
                 if variant.name == STD:
perf/run-benchmarks:498
                 if variant.name == STD:
perf/run-benchmarks:654
 if __name__ == "__main__":
```

sc -f:
```
➜  semgrep git:(EJ-remove-rules-file) sc -f semgrep-core/tests/js/unordered_metavar.sgrep semgrep-core/tests/js/unordered_metavar.js -lang js
semgrep-core/tests/js/unordered_metavar.js:2
 var foo = {
     one: 1,
     two: 2,
     three: 3,
 }
semgrep-core/tests/js/unordered_metavar.js:9
 var foo = {
     two: 2,
 }
```

sc -config:
```
➜  semgrep git:(EJ-remove-rules-file) sc -config semgrep-core/tests/OTHER/rules/settings.yaml semgrep-core/tests/OTHER/rules/settings.js -lang js
semgrep-core/tests/OTHER/rules/settings.js:7 with rule test-options
     foo(1);
```

PR checklist:
- [ ] documentation is up to date
- [ ] changelog is up to date

### CODE REVIEW

**Comment by mjambon** [comment]
It's great that you simplify some of this Main.ml and remove redundant paths.

With these changes, is there a way to run semgrep-core with a pattern and some target files? What I care about is to see (1) complete output and (2) the same data as when invoked from python. I'm totally fine with json output, and I don't mind eliminating incremental text output.

**Comment by emjin** [comment]
Are you asking if we can still do something like `semgrep-core -f pattern_file.sgrep python/ -lang python`?

**Comment by mjambon** [comment]
no, I'm asking if I can do either
```
semgrep-core -e pattern python/ -lang python
```
or
```
semgrep-core -f <(echo pattern) python/ -lang python
```
The latter would rely on this special bash feature that creates a temporary file (but it doesn't work, I think it has to do with something in ocaml). I prefer a plain `-e`.

**Comment by emjin** [comment]
The former works for me

➜  semgrep-core git:(EJ-remove-rules-file) sc -e '$X == $Y' tests/python -lang python 
tests/python/deep_cond.py:3
     if x == true:
tests/python/deep_cond.py:7
     if (b == c) and (x == true):
tests/python/deep_cond.py:7
     if (b == c) and (x == true):
tests/python/dots_nested_stmts.py:3
     if (x == some_cond):
tests/python/equivalence_eq.py:5
     if a + b == a + b:
tests/python/metavar_equality_expr.py:5
     if a + b == a + b:
tests/python/misc_if1.py:2
 if __name__ == "__main__":
tests/python/misc_import.py:1
 if __name__ == '__main__':
error count: 1
➜  semgrep-core git:(EJ-remove-rules-file) sc -rules_file              
/Users/emma/workspace/semgrep/semgrep-core/_build/default/src/cli/Main.exe: unknown option '-rules_file'.
Usage: Main.exe [options] -lang <str> [-e|-f|-config] <pattern> <files_or_dirs>

**Comment by mjambon** [comment]
ah sorry, I meant with json output (see below). I don't understand what you mean by the following:

> This also removes functionality for running `semgrep-core -f -json` or `semgrep-core -e -json`, since it is always possible to put the pattern in a config file. `-json` is not necessary for `semgrep -e`

I want to:
* be able to run a pattern against targets without having to create a file for holding the pattern,
* and get the full json output, because the text output is not what's returned to `semgrep`. Also because it's incomplete (lacks details, including the list of skipped files).

This is the kind of semgrep-core commands I normally run:

```
$ semgrep-core -e '$X == $Y' tests/python -lang python -json | ydump
{
  "matches": [
    {
      "check_id": "-e/-f",
      "path": "tests/python/deep_cond.py",
      "start": { "line": 3, "col": 8, "offset": 36 },
      "end": { "line": 3, "col": 17, "offset": 45 },
      "extra": {
        "message": "",
        "metavars": {
          "$Y": {
            "start": { "line": 3, "col": 13, "offset": 41 },
            "end": { "line": 3, "col": 17, "offset": 45 },
            "abstract_content": "true",
            "unique_id": {
              "type": "AST",
              "md5sum": "bc345f8da8cbee0018d563fc3f495a6b"
            }
          },
          "$X": {
            "start": { "line": 3, "col": 8, "offset": 36 },
            "end": { "line": 3, "col": 9, "offset": 37 },
            "abstract_content": "x",
            "unique_id": {
              "type": "AST",
              "md5sum": "96811ca43f052adf9eeb430fe0b4ce44"
            }
          }
        },
        "lines": []
      }
    },
<snip>
    {
      "check_id": "-e/-f",
      "path": "tests/python/misc_import.py",
      "start": { "line": 1, "col": 4, "offset": 3 },
      "end": { "line": 1, "col": 26, "offset": 25 },
      "extra": {
        "message": "",
        "metavars": {
          "$Y": {
            "start": { "line": 1, "col": 16, "offset": 15 },
            "end": { "line": 1, "col": 26, "offset": 25 },
            "abstract_content": "'__main__'",
            "unique_id": {
              "type": "AST",
              "md5sum": "41ceb3577323c1bb6c0cd75c9afb5646"
            }
          },
          "$X": {
            "start": { "line": 1, "col": 4, "offset": 3 },
            "end": { "line": 1, "col": 12, "offset": 11 },
            "abstract_content": "__name__",
            "unique_id": {
              "type": "AST",
              "md5sum": "11c75e7bbb8b1fcbe11653a641545b03"
            }
          }
        },
        "lines": []
      }
    }
  ],
  "errors": [
    {
      "check_id": "CFGError",
      "path": "tests/python/dataflow/div-by-zero.py",
      "start": { "line": 2, "col": 12, "offset": 22 },
      "end": { "line": 2, "col": 13, "offset": 23 },
      "extra": {
        "message": "Control flow error: Found division by zero",
        "line": "    bad = 1/0"
      }
    }
  ],
  "skipped": [
    {
      "path": "tests/python/ac_matching_dots.sgrep",
      "reason": "wrong_language",
      "details": "target file doesn't look like language Python"
    },
<snip>
    {
      "path": "tests/python/untyped_vs_typed.sgrep",
      "reason": "wrong_language",
      "details": "target file doesn't look like language Python"
    },
    {
      "path": "tests/python/visitor_def.sgrep",
      "reason": "wrong_language",
      "details": "target file doesn't look like language Python"
    }
  ],
  "stats": { "okfiles": 142, "errorfiles": 1 }
}
```

**Comment by emjin** [comment]
Ah, I see. This is indeed not possible with my change. I can add it back, but will take some work.

**Comment by mjambon** [comment]
As I mentioned earlier, I don't care much for incremental input. If that's something you and other semgrep-core devs are ok with, we could simplify some code:
1. produce the results
2. depending on the output format, print as json or as text

Right now we have two non-trivial branches for text and json instead of being purely about printing the results.

**Comment by mjambon** [comment]
I think the priorities should be:
* convenient command line for those who use it (human devs, python): "make common tasks easy and advanced tasks possible"
* deduplicate code

So I think it's natural to:
* allow a single pattern as input, allow a rule file as input; the former gets converted into the latter immediately.
* process the rule file normally and match it against the targets (only one code path), resulting in structured and complete scan results.
* print the scan results using whichever format was specified on the command line.

**Comment by emjin** [comment]
I agree with this proposal. I don't have time to implement it right now, but this is also my ideal. Feel free to close this PR in favor of that approach.

**Pull request closed without merging**
