### PR TITLE
fix(c#): use elvis operator to prevent exponential trees

### LINKED ISSUE #6018: Performance issues when parsing null conditional operators in C#
This file takes several minutes to parse:

```
public class Foo
{
    private static bool MyFunction(object x)
    {
        return 
            x.A?.B 
            || x.A?.C 
            || x.D?.E 
            || x.D?.F 
            || x.G?.B 
            || x.G?.H 
            || x.G?.I 
            || x.G?.J 
            || x.G?.K 
            || x.G?.L 
            || x.G?.C 
            || x.G?.N?.B 
            || x.G?.M?.B 
            || x.G?.O?.B 
            || x.G?.P?.B 
            || x.Q?.B ;
    }
}
```

```
$ time bin/semgrep-core -dump_ast -lang csharp loop.cs > /dev/null
bin/semgrep-core -dump_ast -lang csharp loop.cs > /dev/null  102.77s user 29.71s system 79% cpu 2:46.45 total
```

```
$ time semgrep -l csharp -e '$A=3' loop.cs
Scanning 1 file.
Warning: 1 timeout error(s) in loop.cs when running the following rules: [-]
```

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR translates C# expressions like `e?.foo` differently, using the `Elvis` operator in `AST_generic`, so we don't produce exponentially sized trees.

## Why:
Previously, we translated `e?.foo` to `e == null ? null : e.foo`, which duplicates `e`. This quickly can lead us to exponentially sized trees, in certain corner cases.

## How:
Change it so we instead use the Elvis operator, in keeping with how we translate in other languages, like Rust.

## Test plan:
Counting the number of lines in the dumped AST of a certain file went from 389,742 lines to 1414, after this change.

Closes PA-2701
Closes #6018

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
cc @Sjord

**Comment by aryx** [comment]
Again this weird git error in CI:
```
 Error: fatal: repository 'https://github.com/returntocorp/semgrep-elixir/' not found
  Error: fatal: clone of 'https://github.com/returntocorp/semgrep-elixir' into submodule path '/Users/runner/work/semgrep/semgrep/languages/elixir/tree-sitter/semgrep-elixir' failed
  Failed to clone 'languages/elixir/tree-sitter/semgrep-elixir' a second time, aborting
  Error: The process '/usr/local/bin/git' failed with exit code 1
```

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
A changelog entry might have been useful.

**Comment by brandonspark** [comment]
> A changelog entry might have been useful.

I thought it was non user-facing, but actually in hindsight I guess I could have just said "some C# programs will be faster now".

**Pull request merged**
