### PR TITLE
Catch errors from semgrep run as validation errors

### LINKED ISSUE #5293: Semgrep validate does not report error when config file is missing
```
$ semgrep --validate --config ./notexists.yml
Fetching rules from https://semgrep.dev/registry.
$
```

The command does with an error exit status, but I would expect it to print an error.

### PR DESCRIPTION
**Pull request by Sjord**
So that errors are shown on the output.

Closes #5293.

PR checklist:

- [ ] Documentation is up-to-date
- [ ] Changelog is up-to-date
- [ ] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by emjin** [comment]
Are the test failures expected?

**Comment by aryx** [comment]
@emjin any feedback?

**Comment by emjin** [comment]
I'm extremely baffled by these failing tests. They pass locally when I made the same changes by hand. I'm going to open an equivalent PR and see what happens

**Review by brendongo — APPROVED** [review]

**Comment by brendongo** [comment]
Looks like tests were passing in https://github.com/returntocorp/semgrep/pull/5505 \shrug

**Pull request merged**
