### PR TITLE
chore: Print error logs from the RPC subprocess

### PR DESCRIPTION
**Pull request by nmote**
Test plan:

* Automated tests
* Add `prerr_endline "HELLO WORLD";` to the beginning of the `RPC.main` function. Run an autofix rule with `--autofix` and observe the autofix get correctly applied and observe "HELLO WORLD" in the output of pysemgrep.

### CODE REVIEW

**Comment by nmote** [comment]
Not sure what was going on with #10196. Maybe the logs were getting printed on stderr instead of stdout in the OCaml process? If so, that needs to get sorted out.

**Comment by aryx** [comment]
logs are printed on stderr.

**Review by aryx — APPROVED** [review]

**Comment by nmote** [comment]
Looks like a bunch of e2e-pro autofix tests are failing

**Comment by nmote** [comment]
I'm seeing:

```
  File "/usr/lib/python3.10/subprocess.py", line 1657, in _get_handles
    errwrite = stderr.fileno()
io.UnsupportedOperation: fileno
```

My suspicion right now is that pytest is mocking `sys.stderr` in such a way that the `fileno()` method is not implemented.

**Comment by aryx** [comment]
hmm, probably yes. Pytest is doing lots of things under the hood ...
we've been bitten by it before.

**Pull request closed without merging**
