### PR TITLE
Add snippet to sarif

### PR DESCRIPTION
**Pull request by oxeye-yuvalk**
Related to https://github.com/returntocorp/semgrep/issues/4805

I toke the logic from the Json fomratter
PR checklist:

- [X] Documentation is up-to-date
- [X] Changelog is up-to-date
- [X] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by brendongo** [comment]
Thanks for the contribution @oxeye-yuvalk! Mind signing the CLA and we can get this in.

**Review by brendongo — APPROVED** [review]

**Comment by brendongo** [comment]
Mind updating the changelog to mention a change in sarif output to include matching code as well :D

**Comment by oxeye-yuvalk** [comment]
> Thanks for the contribution @oxeye-yuvalk! Mind signing the CLA and we can get this in.

Hey, for some reason, I signed the CLA but the workflow is steal pending

**Comment by ievans** [comment]
@oxeye-yuvalk maybe this is the issue?

> oxeye-yuvalk seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by oxeye-yuvalk** [comment]
> @oxeye-yuvalk maybe this is the issue?
> 
> > oxeye-yuvalk seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

I am not sure what is the problem, maybe it's related to the fact that it's my first contribution to this project
I signed the agreement and I have a public email under my user
There is any option to run this check again?
@ievans @brendongo

**Comment by DrewDennison** [comment]
@brendongo @oxeye-yuvalk yay! The CLA bot is behaving again

**Comment by oxeye-yuvalk** [comment]
> @brendongo @oxeye-yuvalk yay! The CLA bot is behaving again

Great!!
Can we merge it?
@brendongo

**Comment by brendongo** [comment]
Yep! Will have to update the changelog as it did not make this week's release

**Comment by brendongo** [comment]
@oxeye-yuvalk normally i'd resolve the conflict and update the changelog myself here but github seems to be fighting me. Mind merging develop in and updating the changelog to be under unreleased then we can merge this

**Comment by oxeye-yuvalk** [comment]
> @oxeye-yuvalk normally i'd resolve the conflict and update the changelog myself here but github seems to be fighting me. Mind merging develop in and updating the changelog to be under unreleased then we can merge this

Hey, I just fixed the conflict again, we need to merge it or if someone would merge something into this file again we would have conflict again 
@brendongo

**Comment by brendongo** [comment]
Really sorry forgot to hit merge this morning. I don’t want to take more of your time fixing this conflict again so will figure out a way to merge this by tomorrow morning!

**Comment by oxeye-yuvalk** [comment]
> Really sorry forgot to hit merge this morning. I don’t want to take more of your time fixing this conflict again so will figure out a way to merge this by tomorrow morning!

@brendongo can you merge this?...

**Comment by brendongo** [comment]
Thannks @oxeye-yuvalk sorry for the delays!

**Pull request merged**
