### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sabrinabrogren**

### CODE REVIEW

**Comment by brendongo** [comment]
Does `pipenv install --dev` not already handle this?

**Comment by sabrinabrogren** [comment]
> Does `pipenv install --dev` not already handle this?

Unless I did it incorrectly, it didn't for me. Side note: I also don't seem to have pytest, even after running `pip install -e .`. Not sure if I messed up somewhere. Though I did run through the steps several times to make sure I did them correctly.

**Review by brendongo — APPROVED** [review]

**Comment by sabrinabrogren** [comment]
Making this a draft for now because this may be something that's just necessary on my machine...

**Comment by sabrinabrogren** [comment]
Ah, so the reason things weren't working for me is because I was running in `semgrep` not `semgrep/semgrep`. So this change is not necessary, but I'm going to make another PR with a short clarification, since I'm not the only one who's made this mistake.

**Pull request closed without merging**
