### PR TITLE
Hide semgrep-core stderr

### LINKED ISSUE #873: java parser spews output to stderr, should be hidden/fixed
When parsing echelon-backend, as observed in @dlukeomalley run this am: 

ine@imbp4 ~/D/r/echelon-backend (develop)> semgrep --config=https://semgrep.live/c/p/java
scanning code...
depth_angle < 0, -1
Tag17 ([((" ", 14047, 408, 51, "./analysis/analyzers/r2c/synode/external/test/com/google/javascript/jscomp/TemplatesMinner.java"))])

I believe this comes from:
https://github.com/facebookarchive/pfff/blob/ec21095ab7d445559576513a63314e794378c367/lang_java/parsing/parsing_hacks_java.ml#L40

### LINKED ISSUE #927: don't vomit internal debugging messages without `--verbose`
```
$ semgrep --config https://semgrep.live/p/r2c --json | jq
scanning code...
parse error
 = File "./node_modules/bower/node_modules/handlebars/lib/handlebars/runtime.js", line 1, column 7,  charpos = 7
    around = 'Utils', whole content = module Utils from "./utils";
badcount: 10
BAD:!!!!! module Utils from "./utils";
bad: import Exception from "./exception";
bad: import { COMPILER_REVISION, REVISION_CHANGES, createFrame } from "./base";
bad:
bad: export function checkRevision(compilerInfo) {
bad:   var compilerRevision = compilerInfo && compilerInfo[0] || 1,
bad:       currentRevision = COMPILER_REVISION;
bad:
bad:   if (compilerRevision !== currentRevision) {
bad:     if (compilerRevision < currentRevision) {
bad:       var runtimeVersions = REVISION_CHANGES[currentRevision],
parse error
 = File "./node_modules/bower/node_modules/handlebars/lib/handlebars/compiler/base.js", line 3, column 7,  charpos = 63
    around = 'Helpers', whole content = module Helpers from "./helpers";
badcount: 10
BAD:!!!!! module Helpers from "./helpers";
bad: import { extend } from "../utils";
bad:
bad: export { parser };
bad:
bad: var yy = {};
bad: extend(yy, Helpers, AST);
bad:
bad: export function parse(input) {
bad:   // Just return if an already-compile AST was passed in.
bad:   if (input.constructor === AST.ProgramNode) { return input; }
parse error
 = File "./node_modules/bower/node_modules/handlebars/lib/handlebars/base.js", line 1, column 7,  charpos = 7
    around = 'Utils', whole content = module Utils from "./utils";
badcount: 10
BAD:!!!!! module Utils from "./utils";
bad: import Exception from "./exception";
bad:
bad: export var VERSION = "2.0.0";
bad: export var COMPILER_REVISION = 6;
bad:
bad: export var REVISION_CHANGES = {
bad:   1: '<= 1.0.rc.2', // 1.0.rc.2 is actually rev2 but doesn't report it
bad:   2: '== 1.0.0-rc.3',
bad:   3: '== 1.0.0-rc.4',
bad:   4: '== 1.x.x',
parse error
```

is very confusing

### PR DESCRIPTION
**Pull request by brendongo**

### CODE REVIEW

**Comment by DrewDennison** [comment]
can this be disabled if `--verbose` is passed in?

**Comment by brendongo** [comment]
Not sure we ever want to expose semgrep-core stderr to semgrep stderr?

**Comment by ievans** [comment]
Until we're more robust in terms of the semgrep-core reporting all error output via JSON, I think we're going to want to see it with --verbose. Right now there are a lot of missing cases AFAICT, so +1 to @DrewDennison suggestion.

**Review by DrewDennison — APPROVED** [review]

**Review by ievans — APPROVED** [review]

**Comment by ievans** [comment]
A notable example of semgrep-core stderr that we should be capturing. We probably don't need to revert but we should fix these issues asap: @brendongo  https://github.com/returntocorp/semgrep/issues/811

**Pull request merged**
