### PR TITLE
[WIP] feat(docker): Create and use a semgrep user in our container

### PR DESCRIPTION
**Pull request by bmahe**
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by bmahe** [comment]
This was tested by building the docker image and inspecting it and verifying there is now a user specified

**Review by werrett — APPROVED** [review]

**Comment by milanwilliams** [comment]
@bmahe is this still active? can we re-open this and merge it?

**Comment by aryx** [comment]
Closing to cleanup the list of opened PRs before release. Feel free to reopen.

**Comment by bmahe** [comment]
fixed by #7972

**Pull request closed without merging**
