### PR TITLE
fix(swift): parse expression patterns as expressions

### PR DESCRIPTION
**Pull request by brandonspark**
**What:**
Expressions are currently parsed as singleton statements in Swift.

**Why:**
This means that patterns which are just expressions do not register as expressions, and thus do not recurse more deeply to match against nested expressions.

This means that we fail test cases like the following:
https://semgrep.dev/s/wJlx

**How:**
Made standalone statements that are just `ExprStmt`s parse to expression patterns.

This also means that this wasn't specific to the `try` case -- we'd fail this one, too:
https://semgrep.dev/s/OLbe

Closes PA-1811

PR checklist:

- [X] Each source file starts with an up-to-date [summary of why it exists](https://semgrep.dev/docs/contributing/contributing-code/#explaining)
- [X] Tests included or PR comment includes a reproducible test plan
- [X]  Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by nmote** [comment]
Could you add a test or two for this?

Also, this is out of scope for this PR, but I wonder why this transformation isn't done for all patterns after parsing. It seems language-independent, and @LewisArdern mentioned that he's seen similar issues with other languages too. That makes me suspect that this particular thing has been overlooked elsewhere. @aryx, is there a reason this isn't done later in the pipeline for all patterns instead?

**Comment by brandonspark** [comment]
> Could you add a test or two for this?
> 
> Also, this is out of scope for this PR, but I wonder why this transformation isn't done for all patterns after parsing. It seems language-independent, and @LewisArdern mentioned that he's seen similar issues with other languages too. That makes me suspect that this particular thing has been overlooked elsewhere. @aryx, is there a reason this isn't done later in the pipeline for all patterns instead?

Done!

**Comment by aryx** [comment]
Yes, maybe we could factorize this thing in Parse_pattern.ml.
Some languages have explicit semicolons, so sometimes an ExprStmt is actually a stmt, so in that case
if someone wrote foo();, you don't want to transform that in a pattern for just foo()
But still we can probably factorize things a bit more.

**Comment by nmote** [comment]
Maybe we could check if the semicolon is a real token, or perhaps if its text is nonempty, and if so skip the extraction?

**Review by nmote — APPROVED** [review]

**Pull request merged**
