### PR TITLE
[wip] Alias pattern-not to pattern-not-inside

### PR DESCRIPTION
**Pull request by minusworld**

### CODE REVIEW

**Comment by ievans** [comment]
fix for https://github.com/returntocorp/semgrep/issues/1218 ?

**Comment by ievans** [comment]
@aryx is this obviated by the work you are doing in the core? can you fix #1218 there?

**Comment by aryx** [comment]
yes, semgrep-core already treats pattern and pattern-inside as the same.

**Comment by aryx** [comment]
actually I've found recently examples in our rules preventing us from merging pattern and pattern-inside:.

**Pull request closed without merging**
