### PR TITLE
Add a new -max_match_per_file flag to semgrep-core to avoid stalling

### LINKED ISSUE #2102: Typescript rule hangs on Signal Desktop
This hangs for at least an hour:

using Signal-Desktop at https://github.com/signalapp/Signal-Desktop 

```
ine@imbp4 ~/D/r/t/Signal-Desktop (development) [130]> time semgrep --debug -f r/typescript
trying to download from https://semgrep.dev/r/typescript
using config from https://semgrep.dev/r/typescript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
loaded 1 configs in 0.7014610767364502
running 16 rules from 1 config remote-url_0
running 16 rules...
Running rule typescript.angular.security.audit.angular-domsanitizer.angular-bypasssecuritytrust...

...ran on 510 files
Running rule typescript.angular.security.audit.angular-domsanitizer.angular-sanitize-none-context...

...ran on 510 files
Running rule typescript.react.best-practice.react-props-in-state.react-props-in-state...
```

```
$ semgrep --version
0.32.0
```

Labeling as P0 (high) as this makes Semgrep totally unusable when running any set of rules that contains this rule.

### PR DESCRIPTION
**Pull request by aryx**
This fixes https://github.com/returntocorp/semgrep/issues/2102

This diffs adds also more logging information to track which
files are done processing, how many matches we found, and also
the biggest offending file and rules.

test plan:
install latest semgrep-core in the PATH (make install in semgrep-core/)
then:
(semgrep) pad@yrax:~/work/lang-ts/Signal-Desktop$ time semgrep --debug -f r/typescript
trying to download from https://semgrep.dev/r/typescript
using config from https://semgrep.dev/r/typescript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
...
[0.481  Info       Main.Dune__exe__Main ] Analyzing ts/textsecure/Helpers.ts
[0.481  Info       Main.Dune__exe__Main ] using cache: /tmp/tmpl79hx_fw/3439090b488f63ce7fa88abebaf9f849.ast_cache
[0.483  Info       Main.Dune__exe__Main ] done with ts/textsecure/Helpers.ts
[0.267  Info       Main.Dune__exe__Main ] found 538304 matches and 8 errors
[0.826  Info       Main.Dune__exe__Main ] too many matches on ts/background.ts, generating Timeout for it
[0.836  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 10130, pattern = $PROP
[0.836  Info       Main.Dune__exe__Main ] too many matches on ts/groups.ts, generating Timeout for it
[0.855  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 9077, pattern = $PROP
[0.855  Info       Main.Dune__exe__Main ] too many matches on ts/models/conversations.ts, generating Timeout for it
[0.872  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 13065, pattern = $PROP
[0.872  Info       Main.Dune__exe__Main ] too many matches on ts/models/messages.ts, generating Timeout for it
[0.888  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 11492, pattern = $PROP
[0.888  Info       Main.Dune__exe__Main ] too many matches on ts/sql/Server.ts, generating Timeout for it
[0.897  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 7378, pattern = $PROP
[0.897  Info       Main.Dune__exe__Main ] too many matches on ts/textsecure/AccountManager.ts, generating Timeout for it
[0.902  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 5134, pattern = $PROP
[0.902  Info       Main.Dune__exe__Main ] too many matches on ts/textsecure/MessageReceiver.ts, generating Timeout for it
[0.909  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 6698, pattern = $PROP
[0.909  Info       Main.Dune__exe__Main ] too many matches on ts/textsecure/SendMessage.ts, generating Timeout for it
[0.919  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 10065, pattern = $PROP
[0.920  Info       Main.Dune__exe__Main ] too many matches on ts/textsecure/WebAPI.ts, generating Timeout for it
[0.977  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 5656, pattern = $PROP
[0.977  Info       Main.Dune__exe__Main ] too many matches on ts/views/conversation_view.ts, generating Timeout for it
[0.990  Info       Main.Dune__exe__Main ] most offending rule: id = 0..1.0.2, matches = 11612, pattern = $PROP
[25.862 Info       Main.Dune__exe__Main ] size of returned JSON string: 155652095
...

### CODE REVIEW

**Comment by aryx** [comment]
@inkz your react typescript rules contains pattern that are too general:
  - patterns:
    - pattern-inside: |
        function $FN({$PROP},...) {
          ...
        }
    - pattern-inside: useState(...)
    - pattern: $PROP

the last one just matches everything and put a huge stress on semgrep-core and the semgrep python wrapper
because of the way the engine currently works. Would it be possible to rewrite the rule?

**Comment by nbrahms** [comment]
> @inkz your react typescript rules contains pattern that are too general:
> 
> * patterns:
>   
>   * pattern-inside: |
>     function $FN({$PROP},...) {
>     ...
>     }
>   * pattern-inside: useState(...)
>   * pattern: $PROP
> 
> the last one just matches everything and put a huge stress on semgrep-core and the semgrep python wrapper
> because of the way the engine currently works. Would it be possible to rewrite the rule?

As a suggestion,
```yaml
- patterns:
  - pattern-inside: |
      function $FN({$PROP},...) {
      ...
      }
  - pattern: useState(..., $PROP, ...)
```
perhaps?

**Comment by aryx** [comment]
or maybe useState(..., <... $PROP ...>, ...)

**Comment by aryx** [comment]
I can understand we want to just highlight the use of $PROP and not the englobing use_state, but performance wise this is terrible because of the way the engine works.

**Comment by aryx** [comment]
We could even give a lint warning for the use of such pattern in our rule; it will not scale well on big files.

**Comment by berney** [comment]
It might be worth running the benchmark against rules on PRs, if it's not done already, before they make it into semgrep-rules repo.
Perhaps slow rules can be tagged and can opt-out or opt in (new feature - similar to how ansible allows tagging).
If `--timeout` worked properly it wouldn't be so bad.

**Pull request merged**
