### PR TITLE
Skeleton code for patterns-from-code project

### PR DESCRIPTION
**Pull request by aryx**

### CODE REVIEW

**Comment by mschwager** [comment]
What is `patterns-from-code`? Could you provide an example of where it'd be useful?

**Comment by aryx** [comment]
https://returntocorp.quip.com/ivoKAgodyblv/Pattern-From-Code-Scope-Doc

**Comment by aryx** [comment]
Sorry we didn't advertise this new project of Emma before. Things went fast; Isaac had this idea during a meeting last tuesday and from there we started to design a possible new project for Emma's internship. This diff is just skeleton code that Emma will fill up later to handle all the cases. It's just easier to write down the types of the interface that write doc.

**Comment by mschwager** [comment]
> https://returntocorp.quip.com/ivoKAgodyblv/Pattern-From-Code-Scope-Doc

Ahh, interesting, thanks for the context!

**Pull request merged**
