### PR TITLE
sgrep_types: Allow free-form metadata key in rule definitions

### PR DESCRIPTION
**Pull request by underyx**

### CODE REVIEW

**Comment by DrewDennison** [comment]
@underyx if I run `--json` does the `metadata` object make it through to `extra`?

**Comment by underyx** [comment]
I just force-pushed to fix a silly typo in the commit message 😇

**Comment by underyx** [comment]
> @underyx if I run `--json` does the `metadata` object make it through to `extra`?

It does not. Should I add this as well?

**Comment by DrewDennison** [comment]
if it's easy, that would be great!

**Comment by underyx** [comment]
Alright, @DrewDennison, done. `"metadata"` will now be `{}` by default in the output. I thought that's nicer than only sometimes setting the key, and it would be a nice hint towards the feature existing.

Also note that if somehow someone gets a non-JSON serializable object in via YAML, sgrep will crash. I don't think it's possible, but I'm only 95% sure there's no way to do this.

**Review by DrewDennison — APPROVED** [review]
:ultrafastparrot:

**Review by brendongo — CHANGES_REQUESTED** [review]
I don't think this is something sgrep should support. If there are strings linked to a rule they can be kept externally and use the rule-id to index into it.

**Comment by DrewDennison** [comment]
@brendongo why not support any undefined fields to just flow into extra field? This feels very clean and future proofs us to me

**Comment by brendongo** [comment]
It unnecessarily pollutes the output of sgrep.

**Comment by brendongo** [comment]
What is the specific use case here and why is it not an option for the consumer of sgrep output to shim in desired metadata.

**Pull request merged**
