### PR TITLE
update docs URLs in --help

### PR DESCRIPTION
**Pull request by ievans**

### CODE REVIEW

**Review by dlukeomalley — APPROVED** [review]
lgtm. @pabloest, I wonder if we should rename /pattern-logic to /rule-syntax per the docs title. Changes like that will become more painful once this change ships.

**Comment by ievans** [comment]
+1 to that suggestion Luke

**Comment by pabloest** [comment]
@dlukeomalley yeah heavy plus one

Want me to make the change on this branch?

**Comment by pabloest** [comment]
Sorry, I meant to suggest I can make the change on docs, not on this branch.

**Comment by pabloest** [comment]
@ievans @dlukeomalley https://github.com/returntocorp/semgrep-docs/pull/36

**Comment by ievans** [comment]
@pabloest @dlukeomalley I updated to use https://semgrep.dev/docs/writing-rules/rule-syntax/ after I merged pablo's PR

**Pull request merged**
