### PR TITLE
Combine --include/exclude with their dir option

### LINKED ISSUE #1063: Clean up --include/exclude and --include-dir/exclude-dir
After #946 can make CLI flags more consistent with per rule exclude include behavior

### PR DESCRIPTION
**Pull request by brendongo**

### CODE REVIEW

**Comment by mschwager** [comment]
It seems like this will break existing `semgrep` installs. Should we deprecate then remove?

**Comment by mschwager** [comment]
Erm, by "break existing installs" I mean break backwards compatibility by breaking scripts/CI/workflows that use these flags.

**Comment by brendongo** [comment]
We could. Though the update story is removing `-dir` from their use and it will be equivalent.

**Comment by mschwager** [comment]
At some point we'll have to come up with a deprecation story. If I was a user I wouldn't be thrilled if my scripts/CI kept breaking because of upgrades. I understand we haven't hit our first major release yet, but it's worth considering, especially for changes we don't _have_ to make. At the very least we could track backwards incompatible changes for a month or so and make them all at once instead of having them ~every release.

**Review by mschwager — APPROVED** [review]

**Pull request merged**
