### PR TITLE
fix: run without secrets instead of crashing

### PR DESCRIPTION
**Pull request by akuhlens**
If the secrets product is enabled and the `--oss-only` flag is given the `semgrep ci` crashes. This code fixes that by disabling secrects when `--oss-only` is passed on the command line.

closes [SCRT-223](https://linear.app/semgrep/issue/SCRT-223/semgrep-ci-oss-only-is-crashing-when-secrets-is-enabled)

## test plan
Run command `semgrep ci --oss-only` when logged into the semgrep organization in the semgrep repo.

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
For the test plan you can try on the semgrep repo itself, where secrets is enabled.

I tried, but I get 
```
  Scanning 1870 files (only git-tracked) with 1469 Code rules, 820 Secrets rules, 2549 Supply Chain rules:
```
so even with --oss-only we running secrets and supply chain rules?

**Comment by aryx** [comment]
when run from cli/

When run from the root of the repo, I get similar behavior (but more files to process).

**Comment by aryx** [comment]
I also get Pro rules ...
```
  <multilang>      26    6071          Pro rules     731                                                                
```
so it's a bit confusing to have --oss-only actually running pro rules, secrets rules, and sca rules.

cc @milanwilliams

**Comment by akuhlens** [comment]
I might be able to modify the CI request so that that App doesn't send any SCA or Secrets rules, but I am not certain. Let me check on that today. I will run your test plan and try to get this landed today.

**Comment by akuhlens** [comment]
After looking at the code which requests the rules it isn't 100% obvious to me that there is currently a way to only request community rules if other products are enabled in the app. I can ask for only code rules, but that also gives us the pro-rules.  Fixing which rules are sent will probably require coordination with the cloud team. I am going to go ahead and land this for now. @milanwilliams feel free to open a new ticket that includes the desired rules to run when --oss-only flag is passed.  Cheers!

**Pull request merged**
