### PR TITLE
Allow choosing rules based on severity

### PR DESCRIPTION
**Pull request by kishorbhat**
Addresses #1509, feedback welcome!

### CODE REVIEW

**Comment by kishorbhat** [comment]
Sent over signed CLA to cla@r2c.dev -- @cla-bot check

**Review by aryx — COMMENTED** [review]
Looks good to me!

**Comment by ievans** [comment]
@cla-bot check

**Comment by ievans** [comment]
@cla-bot check pls

**Review by aryx — APPROVED** [review]

**Pull request merged**
