### PR TITLE
WIP: Ruby tree-sitter integration

### PR DESCRIPTION
**Pull request by mjambon**
I added [ocaml-tree-sitter-lang](https://github.com/returntocorp/ocaml-tree-sitter-lang) as a submodule. It inserts into a dune project and should build as is. Some dependencies need to be installed. I put some instructions in ocaml-tree-sitter-lang's readme but no automatic setup in semgrep-core yet. Once the dependencies are installed, semgrep-core should build without errors (worked for me).

I'll keep working on automating the setup.

### CODE REVIEW

**Review by aryx — COMMENTED** [review]
Looks good

**Comment by aryx** [comment]
Ok so now we depend on ocaml 4.10.0 I think. tsort 2.0 is not available for 4.07 apparently.

**Comment by aryx** [comment]
yep switch to ocaml 4.10.0, reinstalling pfff, many opam packages, and running ./install-scripts/intall-ocaml-tree-sitter did the trick. It compiles!

**Comment by mjambon** [comment]
> Ok so now we depend on ocaml 4.10.0 I think. tsort 2.0 is not available for 4.07 apparently.

The dev version of tsort supports ocaml >= 4.03 (https://github.com/dmbaturin/ocaml-tsort/blob/master/.circleci/opam-switches) but it hasn't been released. We can ask for a release if you think it's important, otherwise we just stick to 4.10.

**Comment by aryx** [comment]
I have pbs on my machine with 4.10 but 4.09.1 works fine

**Comment by mjambon** [comment]
I'm pursuing an effort to isolate the semgrep-core build in its own alpine container, and upload the semgrep-core binary as an artifact. This is to avoid having to worry about python in an ocaml environment and vice-versa.

**Comment by aryx** [comment]
Ok, 8 successful tests, progress!

**Comment by mjambon** [comment]
I think I fixed all the issues having to do with the semgrep-core build. @mschwager or @brendongo we need your help with the rest plz :pray:

**Review by aryx — APPROVED** [review]
looks like it works!

**Comment by aryx** [comment]
The only error is: There was an exception [Errno 2***] Is a directory: '/github/workspace/ocaml-
tree-sitter'
Traceback (most recent call last):
  File "/root/.local/bin/bento", line 8, in <module>
    sys.exit(main())

and I don't understand why bento complains about the ocaml-tree-sitter directory so I'll merge the branch!

**Pull request merged**
