### PR TITLE
Match deep ellipsis against statement sub-expressions

### PR DESCRIPTION
**Pull request by nbrahms**
Previously, we only supported deep-ellipsis for matching against
expression sub-expressions.

That is, the following pattern:

    if (cond) {
      <... a ...>
    }

will match:

    if (cond) {
      some_complicated_expression_of(a);
    }

However, we would not match statement sub-expressions. So the pattern:

    <... a ...>
    b

would not match:

    if (a) { ... }
    b

This commit generalizes m_expr_deep to enable use with either expression
or statement sub-expressions (actually to anything for which we can
extract sub-expressions), and then adds a matching branch for
deep-ellipsis against statements.

Closes PA-41.

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by mjambon** [comment]
Maybe you need to install ocamlformat for the pre-commit hook to run correctly locally. If you don't have it installed, there's no error on purpose.

**Review by mjambon — APPROVED** [review]
Awesome.

**Comment by mjambon** [comment]
I did the ocaml reformatting. Merging this when CI succeeds.

**Comment by mjambon** [comment]
I thought this would fix https://github.com/returntocorp/semgrep/issues/3953 (C#) but it doesn't, according to https://semgrep.dev/s/mjambon:match-conditional?version=develop

**Comment by nbrahms** [comment]
Is something up with the Docker building? I copied the test case in this code into your link, and it doesn't match. 🤔

**Pull request merged**
