### PR TITLE
osemgrep: use sarif>=0.3.0

### PR DESCRIPTION
**Pull request by reynir**
Now that the sarif package is in a usable state let's use it!

### CODE REVIEW

**Comment by reynir** [comment]
Failures seem to be due to CI opam state being stale. I'm not sure how to run `opam update` on CI.

**Comment by aryx** [comment]
yes we probably need to update ocaml-layer

**Review by aryx — APPROVED** [review]
Nice work!
I can take it from there, don't worry, I'll fix the CI opam state issue.

**Comment by aryx** [comment]
I think I've fixed the opam stale state in develop. rebasing and hoping this will pass the CI tests now.

**Comment by reynir** [comment]
Glad to see it merged! FWIW `sarif` depends on `dune>=3.12`. It is probably a small change to make `sarif` work with `dune>=3.7`.

**Pull request merged**
