### PR TITLE
fix(output): defatult to MAX_TEXT_WIDTH if os.get_terminal_size returns 0

### LINKED ISSUE #4063: ValueError: invalid width 0 (must be > 0) Exception
**Describe the bug**
Latest version (0.69.0) results in a raised exception:

```
$ semgrep --version
0.69.0

$ semgrep --error --include '*.go' --exclude 'vendor' -f tools/semgrep/ci .
including files:
- *.go
excluding files:
- vendor
Running 8 rules...
100% 8/8 [00:09<00:00,  1.13s/it]
ran 8 rules on 1537 files: 0 findings
Traceback (most recent call last):
  File "/usr/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/semgrep/cli.py", line 662, in cli
    semgrep.semgrep_main.main(
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/lib/python3.8/site-packages/semgrep/output.py", line 150, in managed_output
    output_handler.close()
  File "/usr/lib/python3.8/site-packages/semgrep/output.py", line 351, in close
    self.final_raise(final_error, error_stats)
  File "/usr/lib/python3.8/site-packages/semgrep/output.py", line 302, in final_raise
    terminal_wrap(
  File "/usr/lib/python3.8/site-packages/semgrep/util.py", line 123, in terminal_wrap
    wrapped_paras = ["\n".join(textwrap.wrap(p, width)) for p in paras]
  File "/usr/lib/python3.8/site-packages/semgrep/util.py", line 123, in <listcomp>
    wrapped_paras = ["\n".join(textwrap.wrap(p, width)) for p in paras]
  File "/usr/lib/python3.8/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/usr/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)

Exited with code exit status 1
```

**Expected behavior**
This error was not present on earlier versions 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
alpine:3.13 container on CircleCI

### PR DESCRIPTION
**Pull request by brendongo**
Fixes #4063

PR checklist:
- [ ] Documentation is up-to-date
- [ ] Changelog is up-to-date
- [ ] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Review by emjin — APPROVED** [review]
Would be good to test this; I don't know how

**Comment by brendongo** [comment]
tbh not sure either

**Comment by s3rius** [comment]
Hi, @brendongo. When this feature would be released? My pre-commit check fails every time i run it.
Thanks in advance.

**Comment by emjin** [comment]
This should be released now! Update to the latest semgrep (0.71.0)

**Pull request merged**
