### PR TITLE
Remove the dependency on 'Testo.update_func' which is going away.

### PR DESCRIPTION
**Pull request by mjambon**
Converting Lwt tests to synchronous tests has become difficult. The solution here is to create both kinds of tests instead of converting one to the other.

See https://github.com/semgrep/testo/pull/60

### CODE REVIEW

**Review by aryx — APPROVED** [review]
Would be good to explain somewhere why we need to run the test function
in 2 different ways. Why not just run the synchronous version of the test?
Why do we need Test_lwt.create?

**Review by ajbt200128 — APPROVED** [review]
looks good

**Comment by mjambon** [comment]
> Why do we need Test_lwt.create?

It's for the JavaScript tests because `Lwt_main.run` isn't available in that environment.

**Comment by aryx** [comment]
But can't we use the dune virtual module system @ajbt200128 to provide a Lwt_main.run in JS context?
I still don't understand why we need to have both the regular tests and the lwt tests and why we need
two APIs. I don't understand why even in a JS context we can't take a async function and just force it
so that we can use it in a Testo.create context.
Would be good to add comments explaining why we need those 2 Testo APIs.

**Pull request merged**
