### PR TITLE
Add ?dryrun to Autofix.apply_fixes and apply_fixes_of_core_matches

### PR DESCRIPTION
**Pull request by hannesm**
Before, running `pytest -n auto tests/e2e/test_autofix.py` (with `export PYTEST_USE_OSEMGREP=true`) lead to modifications of the snapshot directory, since dryrun was always false. Now, the snapshot is not modified.

### CODE REVIEW

**Comment by hannesm** [comment]
This also marks 5 more tests to pass with osemgrep.

**Comment by hannesm** [comment]
The build-test-osx-arm64/build-wheels CI job fails, but I can't see any output. Any hints how to triage (or just restart it)?

**Comment by hannesm** [comment]
> The build-test-osx-arm64/build-wheels CI job fails, but I can't see any output. Any hints how to triage (or just restart it)?

NB: restarting lead to success.

**Review by aryx — APPROVED** [review]
great work!

**Pull request merged**
