### PR TITLE
Pin benchmark to current latest

### PR DESCRIPTION
**Pull request by emjin**
Fix failing benchmarks

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by spencerdrak — APPROVED** [review]
I'm comfortable merging this in despite our release-workflow code freeze:
- it'll be run on each PR, meaning we can confirm operation before release
- If something does go wrong, it'll be caught at test time before any release steps are run

**Review by aryx — APPROVED** [review]

**Review by spencerdrak — APPROVED** [review]
approve pending benchmarks are run either on this PR or on merge to develop

**Comment by aryx** [comment]
@emjin why do we still get bench perf regressions in our latest PRs even after this was merged?

**Comment by emjin** [comment]
Develop is slower than 0.122.0

**Comment by aryx** [comment]
we already introduced a new perf regression? Not possible.

**Pull request merged**
