### PR TITLE
chore(README): Note terraform is GA

### PR DESCRIPTION
**Pull request by ievans**
PR checklist:

- README update

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by pabloest — APPROVED** [review]

**Review by emjin — CHANGES_REQUESTED** [review]
Is Terraform GA? Requesting changes while I double check

**Comment by ievans** [comment]
@emjin it is listed as GA https://semgrep.dev/docs/#language-support so I assumed but appreciate you checking

**Comment by emjin** [comment]
@brandonspark Can you run a quick check on the current Terraform parse rate?

**Review by emjin — APPROVED** [review]
Brandon checked and it's 1.0!

**Pull request merged**
