### PR TITLE
added --max-memory flag

### PR DESCRIPTION
**Pull request by sabrinabrogren**
Initial changes, haven't tested yet

### CODE REVIEW

**Comment by sabrinabrogren** [comment]
Tried to test by running the same tests here but in the CLI: https://github.com/returntocorp/semgrep/pull/1367 but I didn't get any errors. The command I was running is `python -m semgrep --config ../semgrep-core/data/basic.yml --max-memory 1 --lang js ../semgrep-core/tests/PERF/l10000.js`

**Comment by sabrinabrogren** [comment]
@aryx The -max_memory flag in semgrep-core appears to be hidden behind -test currently (see https://github.com/returntocorp/semgrep/pull/1367/files#diff-775b9086b9f1a4b7c4c824ee62e8ae41R582). Is it going to stay that way? The changes in this PR were made assuming that wouldn't be the case.

**Comment by brendongo** [comment]
@sabihb you can include the change in this PR moving the -test out of the ocaml code.

**Comment by aryx** [comment]
You don't need to call semgrep-core with -test.
The -test is is just a flag to trigger certain conditions that makes it easier to test features.
Here, if you use -max_memory with a low number (e.g., 1MB), you might not get a Out_of_memory error
that we want to generate because we rely on an alarm in the GC (Garbage collector), but if you use semgrep on small problems, you will not even trigger the GC. The -test flag allows to explicitely calls the Gargave collector, which then gives a chance to run the alarm and raise the Out_of_memory error.

**Comment by sabrinabrogren** [comment]
This started to get messy, so I moved everything over here: https://github.com/returntocorp/semgrep/pull/1426

**Pull request closed without merging**
