### PR TITLE
Adding more token in Rule.ml

### PR DESCRIPTION
**Pull request by aryx**
This will help the metachecker to report errors accurately
at the right location

testp plan:
make

PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Review by IagoAbal — APPROVED** [review]

**Comment by aryx** [comment]
please don't merge for me :) I was adding more stuff in it.

**Comment by IagoAbal** [comment]
> please don't merge for me :) I was adding more stuff in it.

Ooops, sorry about that. But in these cases maybe you could create a "Draft pull request" instead. When you create the pull request, on the right of the green "Create pull request" button there is a down arrow head, if you click that you can choose to create the PR as a draft. Then GH will give you another button so that you can mark the PR as being ready for review&merge.

**Comment by aryx** [comment]
Ah ok, will try next time. But to create pull request I actually don't  use the web interface, I use the 'hub pull-request -b develop' command-line tool (see the 'pr' target in the Makefile of semgrep-core).
But maybe I can change things after.

**Comment by IagoAbal** [comment]
Interesting to know about `hub`, I was not aware of it. It seems that one can pass `--draft` (`-d`) to `pull-request` to create a PR in draft mode.

**Comment by aryx** [comment]
Cool.
Yes hub is very nice. It speedups things a bit. I just do 'make pr; ... sometimes make push; and then make merge'
to automate stuff.

**Pull request merged**
