### PR TITLE
Switch to standard jsonnet and yq for GHA

### PR DESCRIPTION
**Pull request by aryx**
test plan:
cd .github/workflows
make clean
make

### CODE REVIEW

**Comment by aryx** [comment]
I'll make a separate PR to add a CI check to ensure people have run make

**Review by cgdolan — APPROVED** [review]
Thank you, this is great!

**Comment by cgdolan** [comment]
> I'll make a separate PR to add a CI check to ensure people have run make

I took a pass at this in: https://github.com/semgrep/semgrep/pull/9761/commits/19ffea418ba3e5016c31ae7c05b5cb20189dbd3d

**Review by tpetr — APPROVED** [review]

**Comment by aryx** [comment]
thx, I'll take your code and make a PR out of it

**Comment by cgdolan** [comment]
> thx, I'll take your code and make a PR out of it

I've rebased this draft PR to latest develop: https://github.com/semgrep/semgrep/pull/9761

**Pull request merged**
