### PR TITLE
fix: missing warning when improperly mounting docker

### LINKED ISSUE #1047: Docker run calls without a volume mount fail silently in 0.11.0
Screenshot 2020-06-17 at 17 36 15

**To Reproduce**

`docker run returntocorp/semgrep:0.11.0`

**Expected behavior**

The error message from above should be printed.

### PR DESCRIPTION
**Pull request by brendongo**
Fixes https://github.com/returntocorp/semgrep/issues/1047

### CODE REVIEW

**Comment by mschwager** [comment]
I think this stems from the shifting around of error output. Would this affect us anywhere else @rcoh?

**Comment by brendongo** [comment]
Yeah alternative fix would be to not have output_manager handle the last exception https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/output.py#L335
and have that exception just bubble up and be handled (in this case in __main__.py)

**Comment by rcoh** [comment]
I think the output_manger should continue handling the last error, but maybe we should wrap the entirety of CLI in it? I didn't realize that `adjust_for_docker` could throw semgrep errors, that's the only reason it wasn't wrapped already.

**Comment by brendongo** [comment]
I think that raises the core issue though. With output manager you need to know all the things raised but with a top level exception handler you don't need to know where it came from

**Review by underyx — APPROVED** [review]

**Pull request merged**
