### PR TITLE
chore(ci): run semgrep jsonnet tests in CI only

### PR DESCRIPTION
**Pull request by brendongo**
PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
No! This was added to dogfood the use of jsonnet ... It takes 4s on my machine, which IMHO is not that long. Actually
some of the pre-commit steps take longer I think.

**Comment by aryx** [comment]
What is the test plan?
How do I run manually the semgrep-jsonnet?

**Comment by brendongo** [comment]
@brandonspark how slow is the step on your machine? is it a docker m1 mac issue?

@aryx `pre-commit run --hook-stage manual` to run locally.  This PR doesn't remove it, just makes it run only in CI. https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/lint.yml#L55 is there it runs the hooks marked as manual

**Comment by aryx** [comment]
I'll let @brandonspark and @nmote accept if they are really bothered by the current dogfooding of semgrep-jsonnet.
Personally I think it would have been better if brandon tried to investigage/fix the issue rather than bypassing it everytime
at commit, but if people think it's really too slow (it takes 4secs on my machine and I don't commit a hundred time per day, so it's fine with me), then I can live with running it manually. I personally prefer to wait 4sec in pre-commit than waiting 4min to get the error displayed in CI in github.

**Comment by nmote** [comment]
Adding 4 seconds to commit is pretty frustrating to me. I constantly commit and amend and it's especially annoying because I usually have to run it twice because the formatting step formats and fails instead of formatting and then passing. The longer pre-commit jobs only run on Python changes, which I rarely make (but I am frustrated with the commit delay there too when I do).

@aryx, when we previously discussed this, you said that running this in Docker was temporary and once jsonnet shipped to prod we could go back to running Semgrep natively, which is much faster. What is the current status? I'd prefer to have it run quickly on commit, but if I have to choose between fast commits and Semgrep on commit, I'll choose fast commits.

Plus, I VERY rarely end up with any Semgrep findings from this job. The tradeoff of putting it in CI sounds good to me.

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
Ok, let's merge it then.

**Pull request merged**
