### PR TITLE
revert: undo libpcre2 migration so we can fix the build first

### PR DESCRIPTION
**Pull request by amchiclet**
The pro build is failing in osx. We try to link pcre2 statically in semgrep, and to do so, we remove the dynamic library from the system.

However, in the osx build, opam requires git, which requires the dynamically linked pcre2 library. But we removed it because we want to statically build semgrep.

While we figure this out, we've decided to revert the migration.

### CODE REVIEW

**Comment by amchiclet** [comment]
@ajbt200128 There was a conflict in Test_LS_e2e.ml when I reverted the pcre2 change. I wanted to make sure I'm doing the right thing. Can you take a look at Test_LS_e2e.ml?

**Comment by ajbt200128** [comment]
@amchiclet yup looks good

**Comment by amchiclet** [comment]
The check-semgrep-pro workflow is expected to fail here, and will be fixed with a change in the pro repo that updates the function calls to testo.

**Review by kopecs — APPROVED** [review]
lgtm

**Comment by emjin** [comment]
@kopecs Do you know anything about the failing tests?

**Comment by amchiclet** [comment]
The other failings tests though... Looking now.

**Comment by amchiclet** [comment]
This may be related: https://github.com/semgrep/semgrep/blob/67fd39005cb4e1d7c546db9b8ac97e7b888578cb/.github/workflows/build-test-docker.jsonnet#L107

Finding a way to reset the depot cache. I think depot is like some service we use for faster docker builds.

**Comment by amchiclet** [comment]
The depot cache is reset. Retrying now.

**Comment by amchiclet** [comment]
build-test-docker for arm went through successfully after the depot.dev cache refresh.

build-test-windows-x86 is still failing for some other reason. It says it can't build `paf`: https://github.com/semgrep/semgrep/actions/runs/8573190639/job/23499854171?pr=10064#step:8:906

**Comment by kopecs** [comment]
Seems like perhaps `Tls_mirage` had an update? Shouldn't be related to the PCRE stuff.

**Comment by amchiclet** [comment]
Interesting. I does sounds like it's not related to pcre2, but I'd like to be more confident before bypassing this check and merging.

I'm wondering why this windows [workflow that was ran 8 hours ago](https://github.com/semgrep/semgrep/actions/runs/8568360454/job/23482035485) passed with

```
opam install -y --deps-only ./ ./libs/ocaml-tree-sitter-core ./dev/required.opam
Nothing to do.
```

What sort of caching is going on here? I would think that this windows workflow has nothing to do with depot.dev, so the cache refresh is not related and its some other cache issue we're looking at.

**Comment by amchiclet** [comment]
I'm trying to create a clean PR that includes some other library that's not pcre2, just so that [GHA cache misses](https://github.com/semgrep/semgrep/actions/runs/8573190639/job/23499854171?pr=10064#step:6:26) and everything gets rebuilt again for the windows workflow. That way if the build fails, I will know it's unrelated.

**Comment by amchiclet** [comment]
Alright. Confirmed that this failure is indeed not related to pcre2.

I've triggered a re-build in this workflow that doesn't hit the cache, and the re-build fails with the same problem: https://github.com/semgrep/semgrep/actions/runs/8574908656/job/23502744495?pr=10065#step:8:742

The rest are known issues.

**Pull request merged**
