### PR TITLE
Simplify Core_profiling.ml

### PR DESCRIPTION
**Pull request by aryx**
Lessons learned:
 - use the same field name in multiple types (e.g., parse_time, file,
 ...) is confusing in the long term; hard to look at code and
  understanding which variant it is
 - option types are clearer
 - lack of type annotations make the code harder to refactor

I've spent a huge amount of time typing correctly collate_results ...

test plan:
make
make core

### CODE REVIEW

**Comment by aryx** [comment]
I'll make a PR to fix semgrep-pro

**Comment by aryx** [comment]
https://github.com/semgrep/semgrep-proprietary/pull/1320

**Review by emjin — COMMENTED** [review]
Nice; glad to simplify this now that debug no longer has additional information compared to time. At some point we should do some profiling to check how much `--time` adds on large repos

**Comment by emjin** [comment]
Wait, I missed that this was merged with failing checks. @aryx the slowdown could be related

**Comment by aryx** [comment]
where do you see a slowdown?

**Comment by emjin** [comment]
I was referring to the semgrep-compare workflow timing out. Looks like it didn't time out on the PR that actually moved skipped_targets though.

**Pull request merged**
