### PR TITLE
Upgrade to jsoo 5.7.0 (required for OCaml 5)

### PR DESCRIPTION
**Pull request by aryx**
test plan:
make setup

### CODE REVIEW

**Comment by aryx** [comment]
@tpetr can you have a look at the test failure?
```
    Error: pcre_names_stub: namecount
```
maybe just need to define another stub?

**Comment by ajbt200128** [comment]
weird, js_of_ocaml shouldn't touch libpcre, and this error is actually something not returning correctly internally. Not a need for a stub

**Comment by kopecs** [comment]
Doesn't fail for me locally on the current commit with 5.2.0~alpha1. Need to test with 4.14.2 in case it is related to the difference there, but otherwise unclear to me.

Edit: passes for Emma on 4.14.1

**Comment by kopecs** [comment]
whoops accidentally pushed one of the changes for 5 which breaks CI

**Comment by kopecs** [comment]
Looks like
```js
            var ret = libpcre._pcre_fullinfo(
                regexp_ptr,
                extra_ptr,
                PCRE_INFO_NAMECOUNT,
                name_count_ptr
            );
```
at `js/libpcre/runtime.js:465` is returning `PCRE_ERROR_NULL`. Still can't repro locally.

@tpetr / @ajbt200128 any ideas?

**Comment by kopecs** [comment]
@ajbt200128 and I looked into this more. It appears like this might be due to a bug in jsoo. The compile stub in the jsoo generated js code ends with
```js
return {regexp_ptr, extra_ptr, studied: 0};
```
but name stub, rather than destructing with those names, uses minified ones:
```js
let {f: r, e} = ...
```

I don't think I can spend much more time on this, but looks like we should try and simplify and report upstream.

**Comment by kopecs** [comment]
Seems like [c863993](https://github.com/semgrep/semgrep/pull/9861/commits/c863993282b56b9e8c1c47fb38f98c55c778a8e5) avoid that issue and CI failure is now related to QL support. @brandonspark

**Comment by ajbt200128** [comment]
Check Semgrep Pro seems to be failing for unrelated reasons. @kopecs @aryx we should rebase + merge this

**Review by ajbt200128 — APPROVED** [review]
slightly hacky, but oh well

**Comment by aryx** [comment]
Can someone rebase this so we can merge it?

**Comment by aryx** [comment]
@kopecs @ajbt200128 great work! Looks like we're almost there. The error in the snapshot is
```
    +  invalid regex '^fo+': Internal error: pcre_names_stub: namecount (ret=-2)",
```
Also next time @kopecs avoid commits that reindent things; it makes the PR bigger that it needs to be.

**Comment by kopecs** [comment]
Yeah, previously we had that due to the aforementioned jsoo bug. This isn't urgent for me but I can take a look when I get a chance (or @ajbt200128 maybe).

Re formatting: wilco, but I would recommend turning on "ignore whitespace" in github or using `-w` with local git diff to just ignore the whitespace changes.

**Comment by aryx** [comment]
How do you ignore whitespace in github?

**Comment by aryx** [comment]
@ajbt200128 can you push this on the finish line? I'd really like to try OCaml 5.2 ASAP, at least enable it in CI.

**Comment by kopecs** [comment]
image

**Comment by ajbt200128** [comment]
I can probably take another pass at this this week. @kopecs did you ever make a JSOO bug report? if not I'll probably do that too, since this seems p fragile

**Comment by kopecs** [comment]
No, I didn't get around to it before I was OOO

**Pull request merged**
