### PR TITLE
style: Add styling to details and shortlink textual output

### PR DESCRIPTION
**Pull request by zzeleznick**
## Description
Add bold and underline formatting to `Details` and shortlink, respectively.

### CODE REVIEW

**Comment by aryx** [comment]
LGTM. Not sure why osemgrep test is failing. The output actually looks similar.

**Comment by aryx** [comment]
Did you manage to fix this one?

**Review by aryx — APPROVED** [review]
LGTM, we can merge this once the tests are passing.

**Comment by hannesm** [comment]
FWIW, the diff needed to get the osemgrep tests to pass:

```OCaml
--- a/src/osemgrep/reporting/Matches_report.ml
+++ b/src/osemgrep/reporting/Matches_report.ml
@@ -283,8 +283,8 @@ let pp_text_outputs ~max_chars_per_line ~max_lines_per_finding ~color_output ppf
         else Fmt.any ""
       in
       let no_bold_esc =
-        if Fmt.style_renderer ppf = `Ansi_tty then Fmt.any "\027[22m"
-        else Fmt.any ""
+        if Fmt.style_renderer ppf = `Ansi_tty then "\027[22m"
+        else ""
       in
       List.iter
         (fun (sp, l) ->
@@ -297,10 +297,10 @@ let pp_text_outputs ~max_chars_per_line ~max_lines_per_finding ~color_output ppf
         (wrap ~indent:10 ~width:text_width cur.extra.message);
       (match Yojson.Basic.Util.member "shortlink" cur.extra.metadata with
       | `String s ->
-          Fmt.pf ppf "%s%a %a@." base_indent
+          Fmt.pf ppf "%s%a %s%a@." base_indent
             Fmt.(styled `Bold (no_underline_esc ++ string))
-            "Details:"
-            Fmt.(styled `Underline (string ++ no_bold_esc))
+            "Details:" no_bold_esc
+            Fmt.(styled `Underline string)
             s
       | _ -> ());
       Fmt.pf ppf "@.");
```

So the 22m needs to be emitted before the underline. The whole ANSI escape sequences is pretty messy (and it is unfortunate that python and OCaml's fmt have different opinions about that).

Hope that helps. This PR needs a rebase as well.

**Comment by zzeleznick** [comment]
Thanks for the note @hannesm! 

> ANSI escape sequences is pretty messy ...
100%, especially when dealing with our test snapshots across our python and ocaml implementation

This PR was much less ambitious than #9575, and served as a probe for gauging the difficulties with implementing a small style improvement. I'll look to update the tests and merge in once #9586 lands!

**Pull request closed without merging**
