### PR TITLE
Temporarily comment out failing benchmarks

### PR DESCRIPTION
**Pull request by emjin**
PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Review by mjambon — APPROVED** [review]

**Review by aryx — COMMENTED** [review]
great!

**Comment by IagoAbal** [comment]
Does the job work now? Perhaps I did something wrong but I tried running locally and I get segfaults.

**Comment by emjin** [comment]
Wait what do you mean locally? (I've never been able to get a segfault on my computer from these benchmarks, if you can that would be very useful for debugging)

**Comment by emjin** [comment]
Ah, actually just now I ran it again and I got one. Unfortunately it is not the same one as the one that happens in CI, but it's still good to be able to produce it. I do see that the benchmarks segfaulted last night (on django, whereas locally I get it on pmd). Maybe I will just comment out everything from django on.

**Comment by IagoAbal** [comment]
Fixed this one: https://github.com/returntocorp/semgrep/pull/3843

**Pull request merged**
