### PR TITLE
Scala: do not parse parenthesized expressions as unary tuples

### PR DESCRIPTION
**Pull request by mmcqd**
Fixes the bug described in #5376, which was caused by parsing `(e)` as a unary tuple containing `e`. This is not valid Scala syntax for a unary tuple, so this was incorrect. Also replaces a manually string index check with a pre-existing helper function to test for metavariable names.

test plan: make test (see added test)

PR checklist:

- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by aryx** [comment]
what is it with the CI failures?

**Comment by emjin** [comment]
If you merge develop, the extra snapshots will go away

**Review by emjin — APPROVED** [review]
Nice!

**Comment by Strunevskiy** [comment]
@emjin @aryx  @mmcqd  do you have any idea why the build is failing ?

Are you going to include this fix in upcoming release ?

**Comment by mmcqd** [comment]
> @emjin @aryx @mmcqd do you have any idea why the build is failing ?
> 
> Are you going to include this fix in upcoming release ?

It'll be in the next release, yes

**Comment by Strunevskiy** [comment]
@mmcqd  do you have any date for upcoming release?

**Comment by mmcqd** [comment]
@Strunevskiy semgrep releases are usually Tuesday, sometimes Wednesday, of each week. So the next release should be either June 7th or 8th.

**Comment by Strunevskiy** [comment]
@mmcqd  are you releasing it today ?

**Pull request merged**
