### PR TITLE
feat(new syntax): translate taint rules to new syntax

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR adds in the ability to `-translate_rules` taint rules, which previously were not implemented for the new syntax, following #7070.

## Why:
At some point we will need to do a migration for the new syntax. This offers a programmatic way to do it, for taint rules specifically, which otherwise just haven't been touched yet.

## How:
Just did the thing.

Closes PA-2555

## Test plan:
I translated the rule `react-unsanitized-rule` from `semgrep-rules`, and verified that the test still passed.

Before:
```
rules:
- id: react-unsanitized-method
  message: >-
    Detection of $HTML from non-constant definition. This
    can inadvertently expose users to cross-site scripting (XSS) attacks if this
    comes from user-provided input. If you have to use $HTML,
    consider using a sanitization library such as DOMPurify to sanitize your HTML.
  metadata:
    cwe:
    - "CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
    owasp:
    - A07:2017 - Cross-Site Scripting (XSS)
    - A03:2021 - Injection
    references:
    - https://developer.mozilla.org/en-US/docs/Web/API/Document/writeln
    - https://developer.mozilla.org/en-US/docs/Web/API/Document/write
    - https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
    category: security
    confidence: MEDIUM
    technology:
    - react
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    cwe2022-top25: true
    cwe2021-top25: true
    subcategory:
    - vuln
    likelihood: HIGH
    impact: MEDIUM
  languages:
  - typescript
  - javascript
  severity: WARNING
  mode: taint
  pattern-sources:
    - patterns:
        - pattern-either:
            - pattern-inside: |
                function ...({..., $X, ...}) { ... }
            - pattern-inside: |
                function ...(..., $X, ...) { ... }
        - focus-metavariable: $X
        - pattern-either:
            - pattern: $X.$Y
            - pattern: $X[...]
  pattern-sinks:
  - patterns:
    - pattern-either:
      - pattern: |
          this.window.document. ... .$HTML('...',$SINK) 
      - pattern: |
          window.document. ... .$HTML('...',$SINK) 
      - pattern: |
          document.$HTML($SINK)  
    - metavariable-regex:
        metavariable: $HTML
        regex: (writeln|write)
    - focus-metavariable: $SINK
  - patterns:
    - pattern-either:
      - pattern: |
          $PROP. ... .$HTML('...',$SINK) 
    - metavariable-regex:
        metavariable: $HTML
        regex: (insertAdjacentHTML)
    - focus-metavariable: $SINK
  pattern-sanitizers:
  - patterns:
    - pattern-either:
      - pattern-inside: |
          import $S from "underscore.string"
          ...
      - pattern-inside: |
          import * as $S from "underscore.string"
          ...
      - pattern-inside: |
          import $S from "underscore.string"
          ...
      - pattern-inside: |
          $S = require("underscore.string")
          ...
    - pattern-either:
      - pattern: $S.escapeHTML(...)
  - patterns:
    - pattern-either:
      - pattern-inside: |
          import $S from "dompurify"
          ...
      - pattern-inside: |
          import { ..., $S,... } from "dompurify"
          ...
      - pattern-inside: |
          import * as $S from "dompurify"
          ...
      - pattern-inside: |
          $S = require("dompurify")
          ...
      - pattern-inside: |
          import $S from "isomorphic-dompurify"
          ...
      - pattern-inside: |
          import * as $S from "isomorphic-dompurify"
          ...
      - pattern-inside: |
          $S = require("isomorphic-dompurify")
          ...
    - pattern-either:
      - patterns:
        - pattern-inside: |
            $VALUE = $S(...)
            ...
        - pattern: $VALUE.sanitize(...)
      - patterns:
        - pattern-inside: |
            $VALUE = $S.sanitize
            ...
        - pattern: $S(...)
      - pattern: $S.sanitize(...)
      - pattern: $S(...)
  - patterns:
    - pattern-either:
      - pattern-inside: |
          import $S from 'xss';
          ...
      - pattern-inside: |
          import * as $S from 'xss';
          ...
      - pattern-inside: |
          $S = require("xss")
          ...
    - pattern: $S(...)
  - patterns:
    - pattern-either:
      - pattern-inside: |
          import $S from 'sanitize-html';
          ...
      - pattern-inside: |
          import * as $S from "sanitize-html";
          ...
      - pattern-inside: |
          $S = require("sanitize-html")
          ...
    - pattern: $S(...)
  - patterns:
    - pattern-either:
      - pattern-inside: |
          $S = new Remarkable()
          ...
    - pattern: $S.render(...)

```

After:
```
rules:
- id: react-unsanitized-method
  message: Detection of $HTML from non-constant definition. This can inadvertently
    expose users to cross-site scripting (XSS) attacks if this comes from user-provided
    input. If you have to use $HTML, consider using a sanitization library such as
    DOMPurify to sanitize your HTML.
  metadata:
    cwe:
    - 'CWE-79: Improper Neutralization of Input During Web Page Generation (''Cross-site
      Scripting'')'
    owasp:
    - A07:2017 - Cross-Site Scripting (XSS)
    - A03:2021 - Injection
    references:
    - https://developer.mozilla.org/en-US/docs/Web/API/Document/writeln
    - https://developer.mozilla.org/en-US/docs/Web/API/Document/write
    - https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
    category: security
    confidence: MEDIUM
    technology:
    - react
    license: Commons Clause License Condition v1.0[LGPL-2.1-only]
    cwe2022-top25: true
    cwe2021-top25: true
    subcategory:
    - vuln
    likelihood: HIGH
    impact: MEDIUM
  languages:
  - typescript
  - javascript
  severity: WARNING
  taint:
    sources:
    - all:
      - any:
        - inside:
            pattern: 'function ...({..., $X, ...}) { ... }

              '
        - inside:
            pattern: 'function ...(..., $X, ...) { ... }

              '
      - any:
        - pattern: $X.$Y
        - pattern: $X[...]
      where:
      - focus:
        - $X
    sanitizers:
    - all:
      - any:
        - inside:
            pattern: 'import $S from "underscore.string"

              ...

              '
        - inside:
            pattern: 'import * as $S from "underscore.string"

              ...

              '
        - inside:
            pattern: 'import $S from "underscore.string"

              ...

              '
        - inside:
            pattern: '$S = require("underscore.string")

              ...

              '
      - any:
        - pattern: $S.escapeHTML(...)
    - all:
      - any:
        - inside:
            pattern: 'import $S from "dompurify"

              ...

              '
        - inside:
            pattern: 'import { ..., $S,... } from "dompurify"

              ...

              '
        - inside:
            pattern: 'import * as $S from "dompurify"

              ...

              '
        - inside:
            pattern: '$S = require("dompurify")

              ...

              '
        - inside:
            pattern: 'import $S from "isomorphic-dompurify"

              ...

              '
        - inside:
            pattern: 'import * as $S from "isomorphic-dompurify"

              ...

              '
        - inside:
            pattern: '$S = require("isomorphic-dompurify")

              ...

              '
      - any:
        - all:
          - inside:
              pattern: '$VALUE = $S(...)

                ...

                '
          - pattern: $VALUE.sanitize(...)
        - all:
          - inside:
              pattern: '$VALUE = $S.sanitize

                ...

                '
          - pattern: $S(...)
        - pattern: $S.sanitize(...)
        - pattern: $S(...)
    - all:
      - any:
        - inside:
            pattern: 'import $S from ''xss'';

              ...

              '
        - inside:
            pattern: 'import * as $S from ''xss'';

              ...

              '
        - inside:
            pattern: '$S = require("xss")

              ...

              '
      - pattern: $S(...)
    - all:
      - any:
        - inside:
            pattern: 'import $S from ''sanitize-html'';

              ...

              '
        - inside:
            pattern: 'import * as $S from "sanitize-html";

              ...

              '
        - inside:
            pattern: '$S = require("sanitize-html")

              ...

              '
      - pattern: $S(...)
    - all:
      - any:
        - inside:
            pattern: '$S = new Remarkable()

              ...

              '
      - pattern: $S.render(...)
    sinks:
    - all:
      - any:
        - pattern: "this.window.document. ... .$HTML('...',$SINK) \n"
        - pattern: "window.document. ... .$HTML('...',$SINK) \n"
        - pattern: "document.$HTML($SINK)  \n"
      where:
      - metavariable: $HTML
        regex: (writeln|write)
      - focus:
        - $SINK
    - all:
      - any:
        - pattern: "$PROP. ... .$HTML('...',$SINK) \n"
      where:
      - metavariable: $HTML
        regex: (insertAdjacentHTML)
      - focus:
        - $SINK
```

In addition, I had to add ranges to preconditions, so I could grab their verbatim text.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by emjin — COMMENTED** [review]
I'm actually kind of surprised this passes:
```
        - inside:
            pattern: '$S = require("underscore.string")

              ...

              '
```

Would it be possible to translate this to the same multiline format? (aka using `|`)

**Comment by brandonspark** [comment]
@emjin so, we use `Yaml.to_string` to achieve this, which does have a `scalar_style` parameter. Unfortunately, setting it to `Literal produces the following:
image

which works for some of the patterns, but introduces some Wyrd `|-` thing (which i don't understand) for some. It also does it for things which we don't typically associate with multiline formatting, like `mode: taint`, and quotes the keys.

Since this is pre-existing, is it OK if we merge this and I figure this out later?

cc @kopecs

**Comment by kopecs** [comment]
Can't look in depth until Tuesday likely.

I think that at one point I was manually running what we dumped though some `jq` equivalent for yaml to get prettier formatting, but I'm not 100%.

IIRC `|-` is just the same as `|` but without the trailing newline included.

**Comment by brandonspark** [comment]
@emjin thoughts?

**Comment by emjin** [comment]
Yeah, I'm ok with `|-`. It's unfortunate that it quotes the keys, though---do you think we could get one and not the other? And perhaps only apply this to the patterns, so that `mode: taint` doesn't become `"mode": |-\n taint`. imo this is pretty important because SR takes their formatting seriously

**Comment by brandonspark** [comment]
@emjin because we're using the `Yaml` module as a black-box, i'm not sure that there's any further customizability possible...

one idea is that we could use this in conjunction with Autofix, to possibly change all the quoted keys to be un-quoted. for the `"mode":\n taint` stuff though, I've no idea.

i also hesitate to spend a large amount of time on this right now, though, and even the autofix stuff i think might be a pain to set-up. i can look into it if you think it's important, though

**Comment by aryx** [comment]
Non consensus. Closing for now (I'm cleaning up our list of open PRs).

**Comment by brandonspark** [comment]
@emjin thoughts? this is important, as the new syntax gets more adopted, and i'd like to make progress

**Comment by brandonspark** [comment]
@LewisArdern requesting a security perspective, what behavior would you like to see out of this automatic rule translation? is the only acceptable behavior that the output looks like what people would normally write (no quoted keys, no `|-`, etc)?

**Comment by LewisArdern** [comment]
Sorry for not responding to this, we ideally need a way to port rules to the new syntax if we plan to make it the default @aryx @brandonspark. Re-opening, to discuss.

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
need to rebase probably, but looks good to me. I don't know why I closed it before ... I think I misunderstood the purpose of the PR ...

**Comment by aryx** [comment]
Can we merge this?

**Comment by brandonspark** [comment]
@aryx should be up to date with `develop` now

**Comment by aryx** [comment]
failing CI :(

**Comment by brandonspark** [comment]
@aryx oops, rebased wrong. i may need a proper review here.

**Review by aryx — APPROVED** [review]

**Pull request merged**
