### PR TITLE
Add ttok in AST_generic.type_definition

### PR DESCRIPTION
**Pull request by aryx**
This is useful for autofix, otherwise the range is wrong.
Most languages have a keyword like 'type' to introduce
a type definition.

test plan:
test file included
make
make test

### CODE REVIEW

**Review by emjin — APPROVED** [review]
We are truly becoming a CST

**Comment by aryx** [comment]
@ajbt200128 @tpetr any idea why this PR has has a regression regarding large ints?

```
 misc
    ✕ js representation handles large ints (42484 ms)
    ✓ interpolates metavariables in rule message (82 ms)

  ● misc › js representation handles large ints

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      71 |
      72 | describe("misc", () => {
    > 73 |   test("js representation handles large ints", async () => {
         |   ^
      74 |     const engine = await enginePromise;
      75 |     const python = require("../../languages/python/dist/index.cjs");
      76 |     engine.addParser(await python.ParserFactory());

      at test (tests/index.test.js:73:3)
      at Object.describe (tests/index.test.js:72:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 7 passed, 8 total
Snapshots:   3 passed, 3 total
Time:        139.262 s
```

(reproduced locally by cd js; make test)

Also not sure why but I can't really look at the CI logs for the JS test failures :(

**Comment by ajbt200128** [comment]
```
2024-02-20T20:37:27.2517398Z <source>, line 1, characters 0-10:
2024-02-20T20:37:27.2517566Z print(...);
2024-02-20T20:37:27.2517684Z ^^^^^^^^^^ 
2024-02-20T20:37:27.2518028Z parent: script, no left sibling, first child: "print"
2024-02-20T20:37:27.2518167Z node type: ERROR
2024-02-20T20:37:27.2518310Z children: [
2024-02-20T20:37:27.2518437Z   "print"
2024-02-20T20:37:27.2518548Z   parameters
2024-02-20T20:37:27.2518660Z ]
2024-02-20T20:37:27.2518807Z Unrecognized construct
2024-02-20T20:37:27.2526418Z Stdlib.Parsing.Parse_error
```
looks like the errors in CI are different and look like this

**Comment by ajbt200128** [comment]
the logs are so large you cant view them in the browser :/ they need to be downloaded

**Comment by ajbt200128** [comment]
it seems like though python parsing is messed up for all the js stuff tho

**Comment by aryx** [comment]
@ajbt200128 is it possible to change the way we run the JS tests to have less loggings? So at least when there's an error we can inspect the log from github?

**Pull request closed without merging**
