### PR TITLE
rule_match: Remove metavars key from output JSON

### LINKED ISSUE #721: remove internal representation from json output
`metavar` and `md5sum` from the `extra` property shouldn't be output as they are internal and will change from run to run if the internals of `pfff` change

### PR DESCRIPTION
**Pull request by underyx**
This key was meant to be internal-only,
and was quite annoyingly changing a lot across pfff versions.

Closes https://github.com/returntocorp/semgrep/issues/721

### CODE REVIEW

**Review by brendongo — APPROVED** [review]

**Review by mschwager — CHANGES_REQUESTED** [review]
Removing metavariable information from the JSON output breaks the ability to leverage said information in other tools. E.g. route visualization depends on the context in the metavariable information. Are we sure this is what we want?

**Comment by underyx** [comment]
> Removing metavariable information from the JSON output breaks the ability to leverage said information in other tools. E.g. route visualization depends on the context in the metavariable information. Are we sure this is what we want?

@DrewDennison @brendongo thoughts? We could just add a util function to all the tests that remove it from the saved JSONs.

**Comment by brendongo** [comment]
yeah didn't realize it was being used outside. For now let's just remove it in tests and we can revisit what we're exposing later.

**Comment by underyx** [comment]
> @DrewDennison @brendongo thoughts? We could just add a util function to all the tests that remove it from the saved JSONs.

In this case, what exactly should be removed? Just the MD5 sum? Cause we should be testing as much of the output as possible for correctness.

**Comment by brendongo** [comment]
Is there another field outside from md5 that makes tests fragile to pfff updates?

**Comment by underyx** [comment]
> Is there another field outside from md5 that makes tests fragile to pfff updates?

We haven't seen any other yet, but I'm not sure.

**Comment by underyx** [comment]
@mschwager thanks for stopping us just in time! @brendongo ready for review again.

**Review by brendongo — APPROVED** [review]

**Review by mschwager — APPROVED** [review]
LGTM

**Pull request merged**
