### PR TITLE
Ability to test rules with `paths`

### PR DESCRIPTION
**Pull request by fopina**
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

This PR tries to solve https://github.com/returntocorp/semgrep/issues/5487 by allowing _test directories_ to be processed instead of single test files.

### unit test
New unit test for `relatively_eq` included in `tests/unit/test_semgrep_test.py`

### manual e2e
Testing done by using the [same test repository](https://github.com/fopina/delme/tree/main/semgrep_cannot_test_path_includes):

```
$ python -m semgrep --test /Users/fopina/Documents/delme/semgrep_cannot_test_path_includes
0/1: 1 unit tests did not pass:
--------------------------------------------------------------------------------
	✖ my-rule-a
	missed lines: [3], incorrect lines: [4]
	test file path: /Users/fopina/Documents/delme/semgrep_cannot_test_path_includes/my-rule-a/mymodule/views.py


No tests for fixes found.
```

**Note**

`my-rule-a.py` needs to be removed otherwise output is _blocked_ by

```
Found rule id mismatch - file=.../semgrep_cannot_test_path_includes/my-rule-a.py 'ruleid' annotation with no YAML rule={'my-rule-a'}
Failing due to rule id mismatch. There is a test denoted with 'ruleid: <rule name>' where the rule name does not exist or is not expected in the test file.
```

### CODE REVIEW

**Comment by fopina** [comment]
Just noticed that `parts[0]` cannot be used without first removing common prefix (such as `language/`

I'll update tomorrow and include an unit test

**Comment by fopina** [comment]
fixed the matching ✅ 
I've also refactored `relatively_eq` to make it simpler for this change and because it was only used in this file and in this context (comparing targets with configs).
I've renamed the its parameters to make its restricted use clearer as well

**Comment by brendongo** [comment]
@fopina I'm not sure I understand the intention of the change could you explain more?

**Comment by fopina** [comment]
@brendongo I avoided duplicating the problem as it is linked to an issue.

Did you miss that or you mean the problem is not clearly stated in the issue?

**Comment by brendongo** [comment]
Oh I somehow missed that 😓

**Comment by brendongo** [comment]
This looks good. Do you mind adding a changelog entry

**Comment by fopina** [comment]
> Oh I somehow missed that

No worries, I just wasn't sure if it was the case. It's easy for a reporter to assume all context is provided in the description when it's not!

Added the changelog entry, I hope that's ok, not that many entries to use as example

**Review by emjin — APPROVED** [review]
Thanks for this change and the unit tests! If you have time, we would welcome an update to https://github.com/returntocorp/semgrep-docs

**Comment by emjin** [comment]
Need to look into how best to run pre-commit. @brendongo do you know?

**Comment by fopina** [comment]
> we would welcome an update to https://github.com/returntocorp/semgrep-docs

Would it be ok to do it after this is merged?

Mostly because this PR also depends on the undocumented behavior described in https://github.com/returntocorp/semgrep/issues/6880 so I was thinking of opening a PR (to docs) to add both things.

Just needed confirmation on #6880 that it is ok to make the behaviour official and not meant to be removed/"fixed"

> how best to run pre-commit

I know this wasn't towards me and probably I miss context on what you need but I usually just run pre-commit with the failed id from the pipelines

in this case
```
pre-commit run --all end-of-file-fixer
```

I don't use `pre-commit install` to avoid having all checks running on each commit and sometimes I end up forgetting to run `pre-commit run --all` manually before last commit...

**Comment by emjin** [comment]
> Would it be ok to do it after this is merged?

Yup! Re #6880, I'm happy for that to be official behavior. I'll leave the ticket open until you or we document it!

> I usually just run pre-commit 

Wasn't sure if you were able to run pre-commit on your end. Thanks for running it!

**Comment by ben-elttam** [comment]
> I don't use `pre-commit install` to avoid having all checks running on each commit and sometimes I end up forgetting to run `pre-commit run --all` manually before last commit...

If you do install it and want to avoid the hooks, you can use `git commit -n` (`--no-verify`) to skip the hooks.

**Comment by ben-elttam** [comment]
I've tested this and it works well. The only thing I noticed is you can't have a test file that is all `# ok: <ruleid>` comments. It will trigger the error:

> Found rule id mismatch - file=.../semgrep_cannot_test_path_includes/my-rule-a.py 'ruleid' annotation with no YAML rule={'my-rule-a'}
Failing due to rule id mismatch. There is a test denoted with 'ruleid: <rule name>' where the rule name does not exist or is not expected in the test file.

The file can simply be included with no comments, it will be scanned and should have no matches, so passes. It won't show up in the list of test file path(s), but it is used. If you modify the file so it matches, the test will fail and the file will be listed.

**Comment by fopina** [comment]
The "single-ok" issue already existed though using this feature will make it more visible/common.

A colleague is actually trying to address it in https://github.com/returntocorp/semgrep/pull/6987 ⚡

**Pull request merged**
