### PR TITLE
chore: Delete test-semgrep-pro-latest CI job

### PR DESCRIPTION
**Pull request by nmote**
This job was created as a stopgap so we could avoid shipping breakages, back when we served only a single version of the
`semgrep-core-proprietary` binary no matter what version of Semgrep was requesting it.

Fortunately, now we serve the appropriate `semgrep-core-proprietary` binary for the requesting version of Semgrep, so we no longer need to care about compatibility between versions.

Furthermore, this job wasn't actually testing what we wanted it to test because it used the current `returntocorp/semgrep:develop` image, but didn't wait for that image to get updated based on the contents of the current commit.

Test plan: CI

### CODE REVIEW

**Review by aryx — APPROVED** [review]
what about test-semgrep-pro.yml? Can we also delete it?

**Comment by nmote** [comment]
Maybe? I'd have to think through exactly what kind of failure modes that one might catch. It has this comment:

```
      # This is the `develop` binary, so this is truly the most recent version of
      # `semgrep-proprietary` from that repository's `develop` branch.           
      # We test with this so that we know whether any changes we make on this PR are breaking with
      # the `develop` branch of `pro`.
```

**Comment by aryx** [comment]
maybe @brandonspark whether we can delete also the test-semgrep-pro.yml workflow (and not just test-semgrep-pro-latest.yml).

**Comment by aryx** [comment]
one less thing to convert to jsonnet if it's deleted!

**Pull request merged**
