### PR TITLE
Allow explicitly passed hidden config files

### LINKED ISSUE #573: semgrep lint cannot read rules under directories that start with a . (dot)
**Describe the bug**
Due to this https://github.com/returntocorp/semgrep/blob/bf3f33bf851402cc708ed7500188b342236a7e8b/semgrep/semgrep/config_resolver.py#L131

Rule file directories that starts with a `.` are skipped.

I am using tox to run tests. 
semgrep rules are loaded from 

`/***/njsscan/.tox/py37/lib/python3.7/site-packages/njsscan/rules/semantic_grep`

semgrep won't load the rules due to `.tox` in path.

**To Reproduce**
https://github.com/ajinabraham/njsscan/runs/614300110?check_suite_focus=true#step:7:49

**Expected behavior**
Should not complain about directories that starts with a `.` if they are explicitly specified.

**Screenshots**
Can provide on request

**Environment**
experimental branch

### PR DESCRIPTION
**Pull request by nbrahms**
Previously, semgrep would silently ignore any config files in hidden
directories. Here, we allow semgrep to be explicitly passed a path to
a file within a hidden path (or a hidden file path).

This fixes issue #573.

Changes were validated by adding integration tests for the positive and
negative cases.

### CODE REVIEW

**Review by brendongo — APPROVED** [review]

**Comment by brendongo** [comment]
Can you add to changelog

**Comment by nbrahms** [comment]
Fixes #573

**Comment by nbrahms** [comment]
Closes #573

**Comment by nbrahms** [comment]
Closes #573

**Pull request merged**
