### PR TITLE
fix(swift): attribute implicit semicolon locations to previous line

### PR DESCRIPTION
**Pull request by brandonspark**
**What:**
Currently, the Swift tree-sitter parser inserts fake semicolons whenever there is an implicit one. Strangely, however, it inserts them at the beginning of the next line. This borks things w.r.t. Semgrep, because now it means that matches which match an entire expression with an implicit semicolon at the end now match the expression, and the following line.

See https://github.com/alex-pinkus/tree-sitter-swift/issues/179 for more.

**Why:**
We should fix this so that our range reporting is more accurate to the actual finding produced. Otherwise, people might think we matched two lines instead of one.

**How:**
So, there was a time where I considered hacks my enemy. Now, it looks like I have become Death, destroyer of worlds, because this is really hacky.

Actually, the above sentence is no longer true, but it's funny, so I'm keeping it.

Basically, for anytime we map a semicolon token, we check if it contains nullary data as a string. This should only happen if it has absurd location data, which should only happen if it's one of the aforementioned implicit semicolons. If so, we insert a fake semicolon, which does not cause problems for the range data.

For finding the pattern `foo` in the following program:
```
foo
bar
```
before this change, Semgrep reported:
```
test.swift:1
 foo
 bar
```

After this change, Semgrep reports:
```
test.swift:1
 foo
```

Looks like a win to me.

**Alternatives Considered:**
So, I thought about doing something at the `tree-sitter` level. But I really don't understand what's going on over there, so I decided to just do it here.

Closes PA-1810

PR checklist:

- [X] Each source file starts with an up-to-date [summary of why it exists](https://semgrep.dev/docs/contributing/contributing-code/#explaining)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by brandonspark** [comment]
Note: I couldn't figure out how to get Semgrep to stop crashing when an implicit semicolon is the last thing in the program. Hopefully that doesn't happen very often, or I'll keep thinking.

**Comment by nmote** [comment]
This would also be a major hack, but what if instead of inspecting the location of the semicolon, we inspect the contents and if it contains only whitespace (which hopefully the implicit semicolons do?) we drop it and use `G.sc` instead? Would that address the crashing at the end of the file issue?

@alex-pinkus is amenable to changing the grammar so that explicit and implicit semicolons can be distinguished from each other, so if we prove this approach out with a hack, we have a path towards making it less hacky in the future. What do you think?

**Comment by alex-pinkus** [comment]
Yep, just let me know if you need me to separate those out and I'll update the grammar.

Really sorry for causing this hack to be necessary, by the way. I've spent literal months trying to get the whitespace-handling logic to behave similarly to how the real compiler does it, where there's so much nonsense around comments and ambiguous expressions that make me suspect the official rules boil down to "do what we think the programmer wants, no matter what it takes."

**Comment by brandonspark** [comment]
> This would also be a major hack, but what if instead of inspecting the location of the semicolon, we inspect the contents and if it contains only whitespace (which hopefully the implicit semicolons do?) we drop it and use `G.sc` instead? Would that address the crashing at the end of the file issue?
> 
> @alex-pinkus is amenable to changing the grammar so that explicit and implicit semicolons can be distinguished from each other, so if we prove this approach out with a hack, we have a path towards making it less hacky in the future. What do you think?

Actually, this solution is pretty good. It almost feels like it's not even a hack. It fixes the crashing issue, too.

Updated!

**Review by nmote — APPROVED** [review]
Nice, looks great! This turned out simpler than I imagined.

**Comment by nmote** [comment]
Could you update the summary to reflect the new implementation?

@alex-pinkus, thanks, and no apologies needed. I think it would be nice to have explicit and implicit semicolons separated out in the parse tree, but this hack isn't actually that bad so I wouldn't consider it urgent.

**Pull request merged**
