### PR TITLE
fix: Attempt a match between Id and IdQualified

### PR DESCRIPTION
**Pull request by nmote**
It's possible for DeepSemgrep to match in this case when the pattern is
an `Id` and the source is an `IdQualified`, but a parent of the source
name ultimately resolves to a matching `Id`.

At some point we'll likely have to add another case so that
`IdQualified` can match `Id`.

Test plan: Automated tests

PR checklist:

- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Review by aryx — APPROVED** [review]
Not super convinced, but let's try this.

**Comment by nmote** [comment]
Is there something about this that I could clarify?

**Comment by aryx** [comment]
No it's just that I could not imagine easily an example where this would trigger, where this would be useful.

**Comment by nmote** [comment]
Makes sense. Since it's motivated by an example in a different repo, it's not at all obvious. I hope that now that you've reviewed that PR, it's a little clearer?

**Comment by aryx** [comment]
yep, clearer now :)

**Pull request merged**
