### PR TITLE
add semgrep-php

### PR DESCRIPTION
**Pull request by aryx**
PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Comment by aryx** [comment]
This will help https://github.com/returntocorp/semgrep/issues/3576

**Comment by aquynh** [comment]
do i understand correctly that this means future version will move away from pfff to tree-sitter?

**Comment by aryx** [comment]
Yes.

**Comment by aquynh** [comment]
What are pfff-based languages are missing now, compared with tree-sitter?

**Comment by aryx** [comment]
I think right now the PHP parser in pfff is more complete than the tree-sitter-php, but in the past we've seen the community around tree-sitter being quite active, so I think the tree-sitter-php should soon be more complete than the pfff one.

**Comment by aquynh** [comment]
I mean in principle what pfff cannot do that tree-sitter can, so switching
to tree-sitter is encouraged?

**Comment by aryx** [comment]
The pfff repository contains mostly OCaml code, and most of the grammars are using ocamlyacc or menhir which are LALR(1) parser generators. tree-sitter is using a GLR parser generator which is more general and in principle more powerful.
Moreover, I've found that it's difficult for people to extend grammars written in OCaml, but for tree-sitter many people have manage to contribute. So regarding PHP it's either me who need to modify the PHP grammar in pfff, or people in the tree-sitter community who can modify tree-sitter-php. The later is a bigger set of people.

**Pull request merged**
