### PR TITLE
Drop 3.6 support

### PR DESCRIPTION
**Pull request by brendongo**
Python 3.6 was EOL on Dec 23 2021 

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by nbrahms** [comment]
image

whoops :D

**Comment by nbrahms** [comment]
> image
> 
> whoops :D

I think in YAML, `3.10` is a float, not a string

**Comment by brendongo** [comment]
Sigh

**Review by underyx — APPROVED** [review]

**Comment by aryx** [comment]
OMG, so much speedup! look @emjin ! We just needed to drop 3.6 support!

**Pull request merged**
