### PR TITLE
Update '--test' to respect '--config'

### LINKED ISSUE #1796: --test: separate out test and pattern files
Allow semgrep yaml files and test files to be in separate directories

### PR DESCRIPTION
**Pull request by mschwager**
Fixes #1796.

```
$ tree zoo/
zoo/
└── bar
    ├── eval-use.php
    └── eval-use.yaml

1 directory, 2 files
```

```
$ python -m semgrep --quiet --test /tmp/zoo/
1 yaml files tested
check id scoring:
================================================================================
(TODO: 0) /tmp/zoo/bar/eval-use.yaml
	✔ eval-use                                                     TP: 1 TN: 1 FP: 0 FN: 0
================================================================================
final confusion matrix: TP: 1 TN: 1 FP: 0 FN: 0
================================================================================
```

```
$ tree foo/
foo/
└── bar
    └── eval-use.php

1 directory, 1 file
$ tree boo/
boo/
└── bar
    └── eval-use.yaml

1 directory, 1 file
```

```
$ python -m semgrep --quiet --test --config /tmp/boo/ /tmp/foo/
1 yaml files tested
check id scoring:
================================================================================
(TODO: 0) /tmp/boo/bar/eval-use.yaml
	✔ eval-use                                                     TP: 1 TN: 1 FP: 0 FN: 0
================================================================================
final confusion matrix: TP: 1 TN: 1 FP: 0 FN: 0
================================================================================
```

cc @ajinabraham

### CODE REVIEW

**Review by minusworld — APPROVED** [review]
Looks good - this will also keep the current behavior, right?

**Comment by mschwager** [comment]
> Looks good - this will also keep the current behavior, right?

Yup, works on `zoo/` above --^

**Comment by ajinabraham** [comment]
@mschwager Any ideas why my yaml files are not tested?

```
semgrep --quiet --test --config njsscan/rules/semantic_grep tests/assets/node_source/true_positives
The following config files are missing tests:
	njsscan/rules/semantic_grep/jwt/jwt_none_algorithm.yaml
	njsscan/rules/semantic_grep/jwt/jwt_exposed_credentials.yaml
	njsscan/rules/semantic_grep/jwt/jwt_exposed_data.yaml
	njsscan/rules/semantic_grep/jwt/jwt_not_revoked.yaml
	njsscan/rules/semantic_grep/jwt/jwt_hardcoded.yaml
	njsscan/rules/semantic_grep/jwt/jwt_express_hardcoded.yaml
	njsscan/rules/semantic_grep/ssrf/ssrf_playwright.yaml
	njsscan/rules/semantic_grep/ssrf/ssrf_phantomjs.yaml
	njsscan/rules/semantic_grep/ssrf/ssrf_wkhtmltoimage.yaml
	njsscan/rules/semantic_grep/ssrf/ssrf_puppeteer.yaml
	njsscan/rules/semantic_grep/ssrf/ssrf_node.yaml
	njsscan/rules/semantic_grep/ssrf/ssrf_wkhtmltopdf.yaml
	njsscan/rules/semantic_grep/database/nosql_injection.yaml
	njsscan/rules/semantic_grep/database/sql_injection.yaml
	njsscan/rules/semantic_grep/database/nosql_find_injection.yaml
	njsscan/rules/semantic_grep/crypto/crypto_node.yaml
	njsscan/rules/semantic_grep/crypto/timing_attack_node.yaml
	njsscan/rules/semantic_grep/crypto/tls_node.yaml
	njsscan/rules/semantic_grep/dos/regex_dos.yaml
	njsscan/rules/semantic_grep/dos/express_bodyparser_dos.yaml
	njsscan/rules/semantic_grep/dos/regex_injection.yaml
	njsscan/rules/semantic_grep/dos/layer7_object_dos.yaml
	njsscan/rules/semantic_grep/memory/buffer_noassert.yaml
	njsscan/rules/semantic_grep/xss/xss_mustache_escape.yaml
	njsscan/rules/semantic_grep/xss/xss_node.yaml
	njsscan/rules/semantic_grep/xss/xss_serialize_js.yaml
	njsscan/rules/semantic_grep/xss/xss_templates.yaml
	njsscan/rules/semantic_grep/xml/xxe_xml2json.yaml
	njsscan/rules/semantic_grep/xml/xxe_node.yaml
	njsscan/rules/semantic_grep/xml/xml_entity_expansion_dos.yaml
	njsscan/rules/semantic_grep/xml/xpathi_node.yaml
	njsscan/rules/semantic_grep/xml/xxe_sax.yaml
	njsscan/rules/semantic_grep/xml/xxe_expat.yaml
	njsscan/rules/semantic_grep/good/good_helmet_checks.yaml
	njsscan/rules/semantic_grep/good/good_ratelimiting.yaml
	njsscan/rules/semantic_grep/good/good_anti_csrf.yaml
	njsscan/rules/semantic_grep/headers/header_cors_star.yaml
	njsscan/rules/semantic_grep/headers/header_injection.yaml
	njsscan/rules/semantic_grep/headers/header_cookie.yaml
	njsscan/rules/semantic_grep/headers/host_header_injection.yaml
	njsscan/rules/semantic_grep/headers/header_xss_protection.yaml
	njsscan/rules/semantic_grep/headers/header_helmet_disabled.yaml
	njsscan/rules/semantic_grep/traversal/resolve_path_traversal.yaml
	njsscan/rules/semantic_grep/traversal/path_traversal.yaml
	njsscan/rules/semantic_grep/traversal/archive_path_overwrite.yaml
	njsscan/rules/semantic_grep/redirect/open_redirect.yaml
	njsscan/rules/semantic_grep/exec/exec_shelljs.yaml
	njsscan/rules/semantic_grep/exec/exec_os_command.yaml
	njsscan/rules/semantic_grep/generic/hardcoded_secrets.yaml
	njsscan/rules/semantic_grep/generic/logic_bypass.yaml
	njsscan/rules/semantic_grep/generic/error_disclosure.yaml
	njsscan/rules/semantic_grep/generic/hardcoded_passport.yaml
	njsscan/rules/semantic_grep/eval/eval_require.yaml
	njsscan/rules/semantic_grep/eval/eval_yaml_deserialize.yaml
	njsscan/rules/semantic_grep/eval/eval_vm_injection.yaml
	njsscan/rules/semantic_grep/eval/eval_node.yaml
	njsscan/rules/semantic_grep/eval/eval_sandbox.yaml
	njsscan/rules/semantic_grep/eval/eval_drpc_deserialize.yaml
	njsscan/rules/semantic_grep/eval/eval_deserialize.yaml
	njsscan/rules/semantic_grep/eval/eval_vm2_injection.yaml
	njsscan/rules/semantic_grep/eval/server_side_template_injection.yaml
	njsscan/rules/semantic_grep/electronjs/security_electronjs.yaml
0 yaml files tested
check id scoring:
================================================================================
================================================================================
final confusion matrix: TP: 0 TN: 0 FP: 0 FN: 0
================================================================================
```

All the files under true_positive have the ` // ruleid: <rule_name>` denotation.

**Comment by mschwager** [comment]
The config and test directories need to have the same structure.

E.g. if the config is `njsscan/rules/semantic_grep/jwt/jwt_none_algorithm.yaml`, then the test needs to be `test/rules/semantic_grep/jwt/jwt_none_algorithm.js`. You can use a directory other than `test`, but the child directory structure must be the same for Semgrep to correctly detect the tests :+1:

**Comment by ajinabraham** [comment]
Oh, I see. So I need to rework the directory structure. Thanks.

**Pull request merged**
