### PR TITLE
Parse rest of Rust syntax constructs

### PR DESCRIPTION
**Pull request by Ruin0x11**
This should remove the remaining TODOs in the Rust parser. Afterwards a lot of testing will be needed.

### CODE REVIEW

**Comment by aryx** [comment]
Can you fix the failing CI tests?
Also why there are also kotlin stuff in this PR?

**Review by aryx — CHANGES_REQUESTED** [review]
can you see with @colleend why some kotlin stuff got mixed in?
Also can you fix the CI failure?
make test seems to fail.

**Comment by Ruin0x11** [comment]
It seems when I published ocaml-tree-sitter-lang that some of the changes made to the Kotlin part got included somehow. Should we revert them?

**Comment by aryx** [comment]
@colleend might know whether we should revert the kotlin changes.
But still, there are tests failings in this PR that you need to get to pass before I can merge it.

**Comment by colleend** [comment]
ah yes -- we should revert the kotlin changes, they're not currently ready yet 👍

**Comment by Ruin0x11** [comment]
I was debugging the failures and it turns out the tree-sitter binding segfaults:

```
 » OCAMLRUNPARAM=b ./_build/default/CLI/Main.exe -lang rs -dump_tree_sitter_cst tests/rust/metavar_pattern.rs                                                                                                                                             ~/build/work/semgrep/semgrep-core
zsh: segmentation fault (core dumped)  OCAMLRUNPARAM=b ./_build/default/CLI/Main.exe -lang
```

Does this have to do with the version of tree-sitter-cli being used? All of the tests pass when run from the semgrep-rust directory.

**Comment by Ruin0x11** [comment]
Actually it was because the version of tree-sitter I had install got out of sync. I was getting Node errors when `tree-sitter generate` was generating the parser for `semgrep-csharp` and I didn't know why, but updating the parser fixed the problem. My new workaround is to remove `semgrep-csharp` from the Makefile and restore it back so `./release` does not complain about the index being dirty.

**Comment by aryx** [comment]
forgot pre-commit run -a to reindent correctly the code.
Did you setup pre-commit? It is explained in CONTRIBUTING.md

Also not sure what is going on with the test failures in CI.

**Comment by Ruin0x11** [comment]
Oh sorry, the state of my checkout was becoming difficult to contribute to with the number of submodules so I deleted and checked it out again, but forgot to run `pre-commit install` again.

**Comment by aryx** [comment]
No problem. I'm fixing it here: https://github.com/returntocorp/semgrep/pull/2494
I also had to fix some tests and regenerate some snapshots.

**Comment by Ruin0x11** [comment]
Closing due to #2494. Thanks @aryx.

**Pull request closed without merging**
