### PR TITLE
feat: update interfaces for new optional history field

### PR DESCRIPTION
**Pull request by kopecs**
Provides updates necessary for using https://github.com/semgrep/semgrep-interfaces/pull/220 once merged.

Requires an additional commit to point to the version of the commit on main once the above linked PR is merged.

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by kopecs** [comment]
Rebasing + force pushing since I'm getting CI failures related to a new file from develop which requires changes due to interface updates.

**Comment by kopecs** [comment]
I love pytest failures only in CI 🥰

**Review by emjin — APPROVED** [review]
lgtm

**Comment by aryx** [comment]
Nice work!

**Pull request merged**
