### PR TITLE
chore: safe-ast-equality Semgrep rule

### PR DESCRIPTION
**Pull request by nmote**
See #6423

Test plan:

Catches the issue fixed in #6423

Has no findings after that fix.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by nmote** [comment]
Labeled as do not merge because until #6423 is merged, this will have a blocking finding.

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
Nice.

**Comment by aryx** [comment]
This is the kind of rule that would be great to embed in the code, next to the definition of with_structural_equal.

**Comment by nmote** [comment]
Huh, that's an interesting idea. It would be cool to be able to write rules inline in the code.

**Comment by aryx** [comment]
yep, see https://github.com/returntocorp/semgrep/issues/1059

**Review by aryx — APPROVED** [review]

**Pull request merged**
