### PR TITLE
Use Java tree-sitter parser and skeleton for Java CST to AST

### PR DESCRIPTION
**Pull request by aryx**
Test plan:
make test

also
 /home/pad/github/semgrep/semgrep-core/_build/default/bin/Main.exe -lang java -test_parse_lang /path/to/gradle/

to test the java parser on the open source gradle project gives
pretty good result, from 32 errors with just the Java pfff parser
to 11 errrors

### CODE REVIEW

**Comment by aryx** [comment]
Related to https://github.com/returntocorp/ocaml-tree-sitter/issues/66

**Comment by aryx** [comment]
The CI failures are probably because of https://github.com/returntocorp/ocaml-tree-sitter/issues/68

**Review by DrewDennison — APPROVED** [review]

**Comment by aryx** [comment]
The other failures seems to be due to regressions in semgrep-actions and pre-commit;

**Review by nbrahms — APPROVED** [review]
Nice and simple!

**Pull request merged**
