### PR TITLE
Rename rule option commutative_compop to symmetric_eq

### PR DESCRIPTION
**Pull request by IagoAbal**
The previous name was confusing because equality is a relation (not an operation) and it can be symmetric or not, but commutativity simply does not apply to it.

Better rename the option now than wait any longer...

test plan:
make test

### CODE REVIEW

**Review by aryx — CHANGES_REQUESTED** [review]
I think we still need to provide the previous option too ... otherwise it will break some rules.

**Comment by aryx** [comment]
Seems a dupe of https://github.com/semgrep/semgrep/pull/9497

**Comment by IagoAbal** [comment]
OK fine to close it in favor of #9497. But I wasn't keeping the old option because it is not in this table https://semgrep.dev/docs/writing-rules/rule-syntax/#options and there a notice in the docs that says:

> Note that options not included in the table above are considered experimental, and they may change or be removed without notice.

**Comment by aryx** [comment]
ah, good call. As you want then. I assumed we already some rules in semgrep-rules using the old option.

**Pull request closed without merging**
