### PR TITLE
Create Dockerfile-nonroot

### LINKED ISSUE #1437: Non root docker image
Hi

The docker image for semgrep runs as root. I think a new image should be released with a less privileged user

### PR DESCRIPTION
**Pull request by javixeneize**
Created non root dockerfile. Closes #1437

### CODE REVIEW

**Comment by javixeneize** [comment]
Apparently the image can’t be pushed to docker hub. Can somebody have a look please?

**Comment by brendongo** [comment]
Thanks for the PR @javixeneize. For security we don't push to dockerhub from PRs coming from a forked repo (changes will be pushed after the PR is merged) so don't worry about the failing docker test. 

@DrewDennison is there a reason we need the docker to run as root or can these changes be made to the main dockerfile instead of having a second dockerfile?

**Comment by DrewDennison** [comment]
@brendongo I don't believe semgrep needs to be root. We can probably have a `semgrep` user inside the main docker file.

**Comment by javixeneize** [comment]
I can amend it if needed. On top of that, I have done the change using as a base the most recent tag/hash in docker hub (It’s confusing, maybe you should use a more standardised naming for tags). The image with the latest tag is very different to this one (the binary is in /root/.local/bin) and it needs a different dockerfile, which was my initial commit. Is this the right image to modify?

Thanks

**Comment by brendongo** [comment]
You probably want to make those changes here: https://github.com/returntocorp/semgrep/blob/develop/Dockerfile#L56
Also the hashes on dockerhub correspond to commits on Github. The official named tags are latest, develop, and semver versions (like 0.17.0)

**Comment by javixeneize** [comment]
I have added the changes to the main Dockerfile and removed the extra file

Thanks

**Review by brendongo — APPROVED** [review]

**Comment by brendongo** [comment]
Thanks @javixeneize!

**Pull request merged**
