### PR TITLE
osemgrep: use http lwt client

### PR DESCRIPTION
**Pull request by hannesm**
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

As stated in the commit message: use http-lwt-client instead of cohttp. This is a point for discussion, which features and which HTTP implementation would you like to use? Our preferred one is the http-lwt-client (but there are other options, such as interfaces to curl / executions of curl (curly, ezcurl)).

I'm aware the opam-layers repository which prepares the docker images should be updated if this PR is merged. :)

### CODE REVIEW

**Comment by hannesm** [comment]
The flipside is that the OCaml dependencies increase slightly, since http-lwt-client uses happy-eyeballs (for IPv4/IPv6 connection establishment) and ocaml-dns (instead of `getaddrinfo`) and h2 (for HTTP/2 support)

**Review by aryx — APPROVED** [review]
Why the Metrics.ml rename? The same module name is used in another library
and we get a linking error?

**Comment by hannesm** [comment]
> Why the Metrics.ml rename? The same module name is used in another library and we get a linking error?

Yes, since the OCaml compiler doesn't know anything about opam packages nor ocamlfind libraries, it requires that module names do not clash. The path chosen here is to rename `Metrics` to `Metrics_` to allow the opam package `metrics` to be part of the binary. Another path is to remove the `wrapped false` from `dune`, and use `Osemgrep_core.Metrics` at the call site.

**Comment by hannesm** [comment]
Before:
```
# _build/default/src/osemgrep/main/Main.exe --config p/foobar .
Main.exe: [ERROR] Error: exception invalid YAML, /tmp/tmp-2286629-bb76fc.yaml:1:0: missing rules entry as top-level key
Raised at Parse_rule.yaml_error in file "src/parsing/Parse_rule.ml", line 86, characters 21-57
Called from Parse_rule.parse_generic_ast.(fun) in file "src/parsing/Parse_rule.ml", line 1482, characters 12-99
Called from Rule_fetching.load_rules_from_file in file "src/osemgrep/cli_scan/Rule_fetching.ml", line 165, characters 24-39
Called from Rule_fetching.load_rules_from_url.(fun) in file "src/osemgrep/cli_scan/Rule_fetching.ml", line 189, characters 16-41
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from Rule_fetching.rules_from_dashdash_config in file "src/osemgrep/cli_scan/Rule_fetching.ml", line 219, characters 8-31
Called from Stdlib__List.concat_map.aux in file "list.ml", line 268, characters 16-19
Called from Scan_subcommand.run in file "src/osemgrep/cli_scan/Scan_subcommand.ml", line 135, characters 8-63
Called from CLI.safe_run in file "src/osemgrep/cli/CLI.ml", line 163, characters 8-12
```

After:
```
# _build/default/src/osemgrep/main/Main.exe scan --config p/foobar .
Main.exe: [ERROR] Failed to download config from https://semgrep.dev/c/p/foobar: HTTP request failed, server response 404
```

**Comment by aryx** [comment]
I like (wrapped false).
But why do we need the OPAM metrics package? Or it's used indirectly by one of your new dependency?

**Comment by aryx** [comment]
Love the new error message. Very nice!

**Comment by aryx** [comment]
Btw, what is the error message of semgrep pyton with the same arguments?

**Comment by hannesm** [comment]
> Btw, what is the error message of semgrep pyton with the same arguments?

```
# semgrep --config p/foobar .
[ERROR] Failed to download config from https://semgrep.dev/p/foobar: bad status code: 404 returned by config url:
https://semgrep.dev/p/foobar
[ERROR] invalid configuration file found (1 configs were invalid)
```

**Comment by hannesm** [comment]
> I like (wrapped false). But why do we need the OPAM metrics package? Or it's used indirectly by one of your new dependency?

It is used indirectly by http-lwt-client.

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
The 2 failures are because you're not part of the returntocorp org and so you're missing some tokens to push
information to our server.

**Pull request merged**
