### PR TITLE
[Hack] small cleanup to Parse_hack_tree_sitter.ml

### PR DESCRIPTION
**Pull request by aryx**
test plan:
make

PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Comment by aryx** [comment]
cc @frankeld

**Comment by aryx** [comment]
What does TSH mean @frankeld

**Comment by frankeld** [comment]
> What does TSH mean @frankeld

[tree-sitter-hack](https://github.com/slackhq/tree-sitter-hack)

**Comment by aryx** [comment]
ok, merging this then.

**Pull request merged**
