### PR TITLE
Use PCRE regexp syntax in semgrep "=~/xxx/" pattern

### PR DESCRIPTION
**Pull request by aryx**
This fixes
https://github.com/returntocorp/semgrep/issues/1514
and
https://github.com/returntocorp/semgrep/issues/688

test plan:
test files included

### CODE REVIEW

**Comment by aryx** [comment]
@ajinabraham I've seen a few rules in nodejjscan that will not work with the new syntax.
Here is the diff to update crypto_node.yaml (that we include in semgrep-rules/contrib/nodejjscan/
```
   - pattern-either:
     - pattern: |
-        $X.createCipheriv("=~/aes-\([0-9]+\)-ecb/", ...)
+        $X.createCipheriv("=~/^aes-([0-9]+)-ecb$/", ...)
     - pattern: |
-        $X.createDecipheriv("=~/aes-\([0-9]+\)-ecb/", ...)
+        $X.createDecipheriv("=~/^aes-([0-9]+)-ecb$/", ...)
```

**Comment by aryx** [comment]
The failures are in semgrep-rules because of the change of syntax.
I'll update semgrep-rules in a separate PR. 
There is a mutual dependency between the CI of those 2 repos so I'll force merge this one.

**Comment by underyx** [comment]
Copy-pasted from Slack for you @aryx:

> • I think this is a textbook insecure default, if /foo/ matches thai food as well, people won’t notice while testing. If the problem is the old, inverse one, that /foo/ doesn’t match thai food even if you want it to, that will be clear during the rule writing and testing process.
> • This causes false positives in our very own examples too: https://semgrep.dev/s/8xQy/?version=0.22.0 — I know we can update it, but the fact that this is how we originally wrote the rule should probably taken as evidence that the old regex behavior was more natural.
> • I think the phrase “regex matching” we use in the changelog, as well as in common parlance, implies that a full match is required. The behavior where any substring matching is okay I’ve seen usually called “regex search”. See: python re module.
> • The syntax is "=~/foo/" where the equals sign seems to suggest we are test whether the string is equal to the given pattern, not whether it’s a partial match

Couldn't we just always wrap the given pattern in `^` and `$` to get the old behavior back and undo the breaking change?

**Comment by ajinabraham** [comment]
I have around 59 individual lines across 7 rule files using the old syntax. I can change them, but as @underyx mentioned if It is something that can be wrapped without causing a big problem to the regex conventions or writing patterns, wouldn't that be a better backward compatible approach?

**Comment by aryx** [comment]
The original convention was a bad convention. It was using the ugly syntax of OCaml regexp because that's what was available at that time and I was too lazy to use a proper syntax. We should never have forced users to escape pipe or parenthesis because only in OCaml you have to do those things. I was also using the wrong matching function in OCaml, Str.string_match instead of Str.search_forward which is what everybody else is doing. So this was by accident that we had this bad syntax and bad semantic.

**Comment by aryx** [comment]
I understand that it's a bit annoying to have to update your rules and that being backward compatible is nice, but we're still in the early stage of semgrep and it's nice to be able to update the language and remove ugly corners.

**Comment by ievans** [comment]
@aryx @DrewDennison can you make sure we update the docs for this? https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#strings

**Comment by ajinabraham** [comment]
@aryx Are these changes present in semgrep 0.22.0?
I tried both develop and 0.22.0 with the recommended changes of adding ^ and $.
https://semgrep.dev/s/D892?version=develop
https://semgrep.dev/s/D892?version=0.22.0

Both returns no match.

**Comment by aryx** [comment]
You should not escape any more parenthesis.

Here is the relevant part in Changelog.md:
- Breaking: regular expressions in semgrep string patterns (e.g., `"=~/foo/"`)
  are now using the PCRE (Perl Compatible Regular Expressions) syntax instead of
  the OCaml syntax. This means you should not escape parenthesis for grouping
  or escape pipes for dijunctions (e.g., use simply `"=~/foo|bar/"` instead of
  `"=~/foo\|bar/"`). You can also use more advanced regexp features available
  in PCRE such as case-insensitive regexps with '/i' (e.g., `"=~/foo/i"`).
  The semantic of matching changes also to look for the regexp anywhere
  in the string, not just at the beginning, which means if you want to
  enforce a format for the whole string, you will now need to use the '^' anchor
  character (e.g., `"=~/^o+$/"` to check if a string contains only a sequence
  of 'o').

**Comment by aryx** [comment]
See https://semgrep.dev/s/WeLy/

**Comment by ajinabraham** [comment]
Thanks for the clarification. Noted and updated in njsscan 0.1.3

**Pull request merged**
