### PR TITLE
Remove unused .ocamlformat from semgrep-core/

### PR DESCRIPTION
**Pull request by mjambon**
PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Review by IagoAbal — APPROVED** [review]

**Comment by aryx** [comment]
Why so many changes then if it was unused?

**Comment by mjambon** [comment]
Oh, removing the .ocamlformat config in semgrep-core actually did something. A lot of code has been reformatted. This explains why some match-with were crammed on the same line despite having the correct option in the root .ocamlformat.

If this looks good, let's wait for the weekend to merge.

**Comment by aryx** [comment]
ah ok, I didn't get the root/.ocamlformat vs semgrep-core/.ocamlformat. I thought we just had one.

**Comment by aryx** [comment]
This was merged with error.
develop does not compile now.

**Comment by mjambon** [comment]
> This was merged with error.
> develop does not compile now.

yes, sorry about that. I see you fixed it.

**Pull request merged**
