### PR TITLE
chore: update unix primitives names for 5.2

### PR DESCRIPTION
**Pull request by kopecs**
ocaml/10926 updates the runtime functions from Unix in 5.x to be prefixed with `caml_`, which they previously were not. Thus we need to update that here.

### CODE REVIEW

**Comment by kopecs** [comment]
cc: @brandonspark if you're working on this

**Review by ajbt200128 — APPROVED** [review]

**Comment by aryx** [comment]
Does that mean the code will not compile with OCaml 4.14.0?
or using caml_xxx is backward compatible?

**Comment by kopecs** [comment]
> Does that mean the code will not compile with OCaml 4.14.0?

That's correct -- they made a breaking change to the names. This should only get merged if we are building with 5.x.

**Comment by aryx** [comment]
That's annoying, because it's nice to be able to both compile in CI for 4.14.1 and 5.2.0.
Maybe we could use some ifdefs in this code? to make the code portable on both OCaml version?
I usually hate ifdefs, but might be a good use case here.

**Comment by ajbt200128** [comment]
@kopecs I don't see any reason why we can't export the function under both names. Ugly, and clutters the global namespace a bit, but shouldn't break anything. Might even be able to do `//provides: name1, name2` or something simple

**Comment by kopecs** [comment]
Oh, perhaps. Not particularly opposed, but I would figure it just makes more sense to swap over when we move to 5 given we'd presumably be using other features which aren't backwards compatible so it wouldn't matter if this built with 4.

**Comment by ajbt200128** [comment]
I think @aryx wants to be able to have 5.2 working in CI before we actually start using its features and/or releasing with it. So we probably want to be able to merge this and have both versions work for now

**Comment by aryx** [comment]
yep, @ajbt200128 is correct;

**Pull request closed without merging**
