### PR TITLE
chore(deps): bump ocaml from 4.12 to 4.14

### LINKED ISSUE #5483: Upgrade to ocaml 4.14
Why:

- (add reasons)
- support for ocamldebug!
- stay on top of things

Progress so far:
- ocaml-layer published an updated docker image with ocaml 4.14 but it causes a build error in semgrep: https://github.com/returntocorp/semgrep/runs/6810560366?check_suite_focus=true (see also below*)
- @aryx pinned the CI images to a version that won't change and uses ocaml 4.12 (https://github.com/returntocorp/semgrep/pull/5476)

*error message:
```
Install pfff dependencies
The following dependencies couldn't be met:
  - pfff -> ppxlib = 0.20.0 -> ocaml < 4.13
      base of this switch (use `--unlock-base' to force)
```

### PR DESCRIPTION
**Pull request by kopecs**
- Removes ppxlib pinned version to allow this
- Similar changes in pfff submodule

PR checklist:

- [x] Documentation is up-to-date (See https://github.com/returntocorp/semgrep-docs/pull/568)
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by kopecs** [comment]
Blocked on https://github.com/returntocorp/ocaml-layer/pull/13

**Comment by kopecs** [comment]
Looks like following changes are still needed: 
- [x] Dockerfiles (blocked on above)
- [x] `scripts/{*-release,setup-m1-builder}.sh`
- [x] Homebrew formula (at <https://github.com/Homebrew/homebrew-core/blob/master/Formula/semgrep.rb>)---looks like this should be done as part of the next release after this gets merged (cc: @spencerdrak)?
- [x] Contributing docs

**Comment by kopecs** [comment]
Related: seems like there's a comment about adding `bisect_ppx` once we can upgrade `ppxlib` (which this should allow). Is this still relevant @aryx?

**Comment by underyx** [comment]
@kopecs heads up, you might wanna rebase before fixing the dockerfiles; there were a bunch of changes to them (and also to the github actions) here: https://github.com/returntocorp/semgrep/commit/f43d4e498acb822676401543f5738b628773ad9c

**Comment by aryx** [comment]
we didn't use bisect_ppx in a long time. It's useful to get code coverage, but is not super important.

**Comment by kopecs** [comment]
Force pushing to rebase.

**Review by spencerdrak — COMMENTED** [review]
@kopecs my only comment is to ensure that the images referenced by tag aren't rolling tags - that's bit me once or twice before. The ones referenced by SHA are fine!

**Comment by mjambon** [comment]
@spencerdrak I set our CI to use rolling tags on purpose so we can stay on top of things. I want to avoid a situation where we have to fix a bunch of unrelated problems at once when we need a more recent version of one package.

If we had a way to test semgrep CI with the new weekly images independently from production semgrep CI, we'd use that. Meanwhile, I'd rather stick to rolling tags.

**Comment by spencerdrak** [comment]
@mjambon check - if that's what we want to roll with (pun intended), I'll defer to you folks there. And in either case it should be caught by our tests, so @kopecs we can leave as is. 

If we want to revisit this later, I'm okay with that.

**Review by underyx — APPROVED** [review]

**Pull request merged**
