### PR TITLE
fix(ci): release issues

### PR DESCRIPTION
**Pull request by spencerdrak**
This change fixes and issue experienced [in releasing semgrep 0.120.0](https://github.com/returntocorp/semgrep/actions/runs/3379203790) and some follow-on issues that would've popped up if that step had succeeded. 

Test plan: 

The changes in this PR were tested in go/test-gh-actions and then ported to this repo.
- [source](https://github.com/returntocorp/test-gh-actions/blob/develop/.github/workflows/release.yml)
- [successful run](https://github.com/returntocorp/test-gh-actions/actions/runs/3381581391)
- [uploaded schema file (draft release)](https://github.com/returntocorp/semgrep-interfaces/releases)

In addition, I'll be running another release soon to ensure we're good to go.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by bmahe — APPROVED** [review]

**Comment by aryx** [comment]
I don't have access to this test-gh-actions repo. The link leads to a 404 for me.

**Comment by spencerdrak** [comment]
@aryx you should have access now! LMK if you don't Sorry - I thought that developers already had access.

**Review by ajbt200128 — APPROVED** [review]
LGTM

**Comment by spencerdrak** [comment]
Holding on the merge until the macos issue is sorted. Thanks for the reviews!

**Pull request merged**
