### PR TITLE
feat(autofix): Handle Id metavars in metavar replacement

### PR DESCRIPTION
**Pull request by nmote**
Some identifiers were already handled since they end up getting bound to expression metavars. But, for those that are bound as identifier metavars, like the ones in the tests, autofix will now correctly replace them.

Test plan: Automated tests

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by nmote** [comment]
The e2e test changes are because that case is now using AST-based autofix, which conservatively inserts parentheses around binary expressions.

**Comment by aryx** [comment]
Is there a way to implement the minimum parenthesis so we avoid those extra parens to avoid updating all those snapshots?

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
or maybe just hardcode something for the ugly python printer that recognize == and avoid the parenthesis around?

**Comment by nmote** [comment]
Yes, there's a way but I explicitly laid it out as out of scope for this month's work. Would you like me to re-evaluate that?

**Comment by aryx** [comment]
I would hack something just for $X == $Y that would be enough for all those snapshots.

**Comment by aryx** [comment]
But up to you.

**Comment by nmote** [comment]
Sure, I'll look into it

**Comment by nmote** [comment]
Actually, I don't think that we can safely leave out the parentheses for `==`. Consider the expression:

`2 + 3 == 4 + 1`
vs
`2 + (3 == 4) + 1`

The latter is kind of nonsense, but Python does happily evaluate it to `3`. If we are printing the latter expression and leave off the parentheses, we change the meaning of the program.

**Comment by nmote** [comment]
I think that to address this, we will need to take into account the context of the expression. This is something that I intend to do, but not as part of this month's project which is focused on getting correct (if ugly) output in as many cases as possible.

**Pull request merged**
