### PR TITLE
add semgrepdep

### PR DESCRIPTION
**Pull request by ievans**
experimental, but should do this - before & after:

### CODE REVIEW

**Comment by aryx** [comment]
Why the modifs to the submodules?

**Comment by ievans** [comment]
Oops, accident. Fixed and force-pushed.

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
any idea about the ci failure?
can we merge this?

**Comment by ievans** [comment]
looks like it was transient or got fixed

**Pull request merged**
