### PR TITLE
Create a semgrep user for our docker container so that people can run…

### PR DESCRIPTION
**Pull request by bmahe**
… it as a non-root user

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by bmahe** [comment]
Tested:
```bash
[bruno@buo semgrep]$ podman run --rm -v "${PWD}/cli:/src" --security-opt "label=disable"  -it b8670583fea8 /bin/bash -c "semgrep scan -c auto && whoami" | tail -n 2
Ran 1077 rules on 201 files: 3 findings.
root
```
So it defaults to root and won't break our circle ci workflows

And then when ran as semgrep:
```bash
[bruno@buo semgrep]$ podman run --rm -v "${PWD}/cli:/src" --security-opt "label=disable" --user semgrep -it b8670583fea8 /bin/bash -c "semgrep scan -c auto && whoami" | tail -n 2
Ran 1077 rules on 201 files: 3 findings.
semgrep
```

**Comment by bmahe** [comment]
Separating the changes from #8116

**Review by cgdolan — APPROVED** [review]

**Comment by bmahe** [comment]
Merged develop into the branch.
I will merge that PR if/when the tests pass given it was given a :+1: from @cgdolan

**Review by emjin — APPROVED** [review]
Seems reasonable from my very limited knowledge

**Pull request merged**
