### PR TITLE
chore: hide internal findings in count

### PR DESCRIPTION
**Pull request by niklasmannhardt**
PR checklist:

- [x] Documentation is up-to-date
- [ ] `changelog.d/<issue>.<type>` is a file with the _what_, _why_, and _how_ of the change.
  - \<issue> is `pa-312` (Linear ticket), `gh-1234` (GitHub issue), or `new-gizmo` (unique semantic name)
  - \<type> is `added`, `changed`, `fixed`, or `infra`.
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see the [Contribution guidelines](https://semgrep.dev/docs/contributing/how-to-contribute/)!

### CODE REVIEW

**Review by brendongo — DISMISSED** [review]
Lets add to the changelog that reported rule count ignores inventory and experiment rules

**Comment by ievans** [comment]
I worry this change could be pretty confusing to the user, and also make us appear extra slow. Is there any way to discover that this is happening in the default output? Does --verbose or --debug show these rules?

Are these rules still reported anyways else? E.g. in the "N rules x M files" header?

**Comment by raghavjain3** [comment]
@ievans @brendongo perhaps we can have a line like "Additionally, scanned with X rules to detect technologies in this project"?

**Comment by emjin** [comment]
> Are these rules still reported anyways else? E.g. in the "N rules x M files" header?

@ievans I would expect that they are unless it's been explicitly changed in this PR, because that's produced from uses the target matrix sent to semgrep-core

**Pull request closed without merging**
