### PR TITLE
Revert "Revert "ResolvedName of dotted_ident -> GlobalName of string list (#6900)" (#6965)"

### PR DESCRIPTION
**Pull request by aryx**
This reverts commit 49faa10b1bc875abf894b0ac367363512a67db80.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
reverting the revert, but this time we should see a CI failure now that the GHA core-cache regexps are fixed.

**Comment by IagoAbal** [comment]
Could we fix the `abstract_content` ?

**Comment by aryx** [comment]
No, we should get rid of abstract_content.
It was a hack a long time ago, but the Python code should not use it anymore.
The join code should use core_output.read_metavariable if it wants to access the content of a metavariable.
Abstract_content was deprecated a long time ago.

**Comment by aryx** [comment]
the string in abstract_content is garbage.

**Comment by aryx** [comment]
Trying to deprecate abstract_content: https://github.com/returntocorp/semgrep/pull/6969

**Pull request merged**
