### PR TITLE
regex: Add line and column numbers to regex pattern matches

### LINKED ISSUE #765: pattern-regex does not have start and end line numbers
pattern-regex does not fill `start` and `end` fields. Relatedly this causes semgrep.live to crash

 https://semgrep.live/O22?version=e4e89dcbe40830bfb8d5a8e5341e5587824e1770

```
rules:
  - id: boto-client-ip
    patterns:
      - pattern-regex: '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
    message: "boto client using IP address"
    languages: [python]
    severity: ERROR
```

on 

```
x = "1.1.1.1"
```

### PR DESCRIPTION
**Pull request by brendongo**
Closes https://github.com/returntocorp/semgrep/issues/765

### CODE REVIEW

**Comment by brendongo** [comment]
Thanks @rcoh for pointing out rfind. made this much cleaner

**Review by DrewDennison — APPROVED** [review]

**Comment by rcoh** [comment]
(test failure is real)

**Comment by brendongo** [comment]
https://github.com/returntocorp/semgrep/pull/796 will fix the test failure

**Comment by mschwager** [comment]
Woooo, nice! You probably already noticed this, but I'll re-state for posterity's sake in-case we ever need to look back on this: this should work even on Windows, which uses `\r\n` as line endings instead of `\n`. [`Path.read_text`](https://docs.python.org/3/library/pathlib.html?highlight=path#pathlib.Path.read_text) takes the same arguments as [`open`](https://docs.python.org/3/library/functions.html#open), which defaults it's `newline` kwarg to translate all line endings (`\n`, `\r`, `\r\n`) to `\n`. Free Windows support :100:

**Pull request merged**
