### PR TITLE
chore: add back `--pro` to the metrics test

### PR DESCRIPTION
**Pull request by emjin**
Now that semgrep-pro has been updated, this test should work. Add it back!

Test plan: automated tests

### CODE REVIEW

**Comment by emjin** [comment]
Still doesn't work. I suspect these tests don't have access to the pro binary, so I'll probably just move this to the proprietary tests just for my convenience. I'm going to take a break and work on something else first though

**Comment by aryx** [comment]
Can we merge this @emjin ? I thing if you merge develop the CI tests should pass now.

**Comment by emjin** [comment]
ooh wait I didn't see the comment. Will try to merge develop!

**Comment by emjin** [comment]
Might be easy after https://github.com/semgrep/semgrep/pull/9880

**Pull request closed without merging**
