### PR TITLE
update interface submodule

### PR DESCRIPTION
**Pull request by ihji**
PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by emjin** [comment]
Haha I just made two prs that also update the submodule. See https://github.com/returntocorp/semgrep/pull/8273#issuecomment-1636503726 about the build failing

**Comment by ihji** [comment]
@emjin thanks for the link. will wait for the fix.

**Comment by ihji** [comment]
depends on #8255

**Comment by aryx** [comment]
closing, there's been lots of change to the interface file anyway.

**Pull request closed without merging**
