### PR TITLE
tainting: Add experimental taint-propagators feature

### LINKED ISSUE #4509: [JS] Taint does not propagate through `.push(...)` for arrays
**Describe the bug**
It appears that taint mode stops propagating data at `.push(...)` in array objects.

**To Reproduce**
This link has 3 examples. The third does not work, but should.
https://semgrep.dev/s/bXKp

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

### PR DESCRIPTION
**Pull request by IagoAbal**
Closes PA-1361
Closes #4509

test plan:
make test # added three tests

PR checklist:

- [ ] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Review by aryx — APPROVED** [review]
This is quite complicated. I didn't have the time to really understand the new code, but let's
merge this to avoid conflicts.

What are the alternatives to taint propagator?
What if we consider that each time you do    foo.bar(stuff), then if stuff is tainted then the object foo becomes tainted? We would get too many FPs after?

**Comment by aryx** [comment]
Also I guess we want somewhere to discuss that this taint-propagators would work well with pattern-ref:, because we really
want to factorize in one place all the different way standard API functions behave regarding tainting no?

**Comment by IagoAbal** [comment]
> This is quite complicated. I didn't have the time to really understand the new code, but let's merge this to avoid conflicts.

I'll give it another look and try to add some more comments!

> What are the alternatives to taint propagator? What if we consider that each time you do foo.bar(stuff), then if stuff is tainted then the object foo becomes tainted? We would get too many FPs after?

I tried to do exactly that as a quick hack in returntocorp/semgrep#5150 but then we got a bunch of FPs in semgrep-rules due to code like `out.println(tainted)` (`out` becomes tainted and then that causes an FP).

**Comment by aryx** [comment]
Ok then good to add those examples and the pr that was implementing that in comment

**Comment by IagoAbal** [comment]
> Also I guess we want somewhere to discuss that this taint-propagators would work well with pattern-ref:, because we really
> want to factorize in one place all the different way standard API functions behave regarding tainting no?

Indeed, I think there is an "pressing" need for `pattern-ref` or similar solution.

**Comment by IagoAbal** [comment]
> Ok then good to add those examples and the pr that was implementing that in comment

👍 Preparing a follow-up PR.

**Pull request merged**
