### PR TITLE
Generate Lang.ml from flat file

### PR DESCRIPTION
**Pull request by nbrahms**
This:
- Reduces the number of code locations we need to update when
  adding or modifying supported languages
- Moves language data to a single source of truth
- Ensures consistency of language data between idioms and codebases

cc. @aryx I saw the note about external libraries, so wanted to get your thoughts here and how to best accomplish this goal while not negatively impacting external consumers too much.

PR checklist:
- [X] Documentation is up-to-date
- [X] Changelog is up-to-date
- [X] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by nbrahms** [comment]
cc. @ievans

**Review by aryx — APPROVED** [review]
Lgtm.
What about my notes on external libraries? Where do I speak about that?

**Comment by nbrahms** [comment]
> Lgtm. What about my notes on external libraries? Where do I speak about that?

It's in a comment in `src/core/ast/dune`:

> This library used to be in pfff and is still used in projects outside semgrep (e.g., codemap/efuns) which rely on this pfff-lang_... name and rely on small dependencies.

**Comment by aryx** [comment]
ah true ... annoying.

**Comment by aryx** [comment]
What about we do the code generation in the submodule and commit in the submodule repo the generated OCaml, python, typescript code?

**Pull request merged**
