### PR TITLE
Adds initial R support

### PR DESCRIPTION
**Pull request by zythosec**
Part of https://github.com/returntocorp/semgrep/issues/2360

I was getting some errors related to rust when building locally, so not sure what's going on there or if it had something to do with updating submodules:
```
File "parsing/Parse_rust_tree_sitter.ml", line 1112, characters 5-16:
1112 |    | `Ellips tok -> G.Ellipsis (token env tok) (* "..." *)
            ^^^^^^^^^^^
Error: This pattern matches values of type [? `Ellips of 'a ]
       but a pattern was expected which matches values of type CST.expression
       The second variant type does not allow tag(s) `Ellips
```

### CODE REVIEW

**Comment by aryx** [comment]
The errors are probably because you didn't start from the latest develop or some of your submodule were not in sync.
I usually do
$ git checkout develop
$ git pull
$ git submodule update --recursive
at this point git status should not report anything.

**Comment by aryx** [comment]
See "This branch is 1 commit ahead, 2 commits behind returntocorp:develop."
at https://github.com/zythosec/semgrep/tree/r
You were behind, which is why you got those errors, and probably you didn't do the git submodule update --recursive
(git status should have shown you that pfff was not up to date).

**Review by aryx — APPROVED** [review]
Looks good. 
Just git pull; git merge develop to get the latest version so there are not those 
unrelated changes to rust in this PR.

**Comment by zythosec** [comment]
@aryx I had previously run `git submodule update --init --remote --recursive`. I rebased on develop and did a recursive submodule update again, but I am still seeing the above error. Could there be changes from a commit in another branch that got merged in?

**Comment by aryx** [comment]
Hmm I know why, it's because @Ruin0x11 may have forgotten to pull the latest semgrep-grammars in ocaml-tree-sitter/lang/ 
and so when we generate a new release for ocaml-tree-sitter-lang, it does not take the recent changes for Rust in semgrep-grammars.
I'll try to fix it.

**Comment by aryx** [comment]
Those submodules are tricky to get right @mjambon ...

**Comment by aryx** [comment]
Did you sign the CLA @zythosec ?

**Comment by zythosec** [comment]
@aryx I should have it by you to end of day. Double checking there is no issue with my employer.

**Comment by zythosec** [comment]
@aryx CLA signed and sent.

**Comment by ievans** [comment]
pls @cla-bot check

**Comment by aryx** [comment]
ok merging develop here to fix conflicts: https://github.com/returntocorp/semgrep/pull/2407

**Comment by aryx** [comment]
merged in the other PR.

**Pull request closed without merging**
