### PR TITLE
Ensure that scanned paths aren't directories

### PR DESCRIPTION
**Pull request by malexmave**
Workaround for issue with git submodules and `git ls-files`, see #3660 for details.

Someone who knows more about semgrep internals should definitely take a closer look at this and ensure that I didn't miss any cases where passing folders into the list of targets is desired - I didn't find any, but I'm new to the codebase :). One could also replace it with an `is_file`, but again, I don't know if there are any non-file things you want to be able to investigate.

Note that at least on my machine, this code has [a bunch of failing `pytest` tests](https://gist.github.com/malexmave/aa61e2acf30de02e838d90049f0a3c52). However, the tests [also fail for the unmodified code](https://gist.github.com/malexmave/1d94f4ff68f5725a8ff57a5d523f5141) on my machine, so I don't quite know what to make of this.

PR checklist:
- [x] documentation is up to date (no changes necessary)
- [x] changelog is up to date

### CODE REVIEW

**Comment by malexmave** [comment]
That's what happens when you just make a quick edit using the GitHub Web UI and forget about pre-commit. Fixed the linter complaint, let's hope the CI run is happy now :).

**Comment by mjambon** [comment]
Great investigation, @malexmave. This is a problem right now for the generic mode but will be a bigger problem for all the scripting languages when we start scanning executable scripts that don't have an extension.

 In your branch, I think the filtering needs to take place earlier, as close as possible to where we run `git ls-files`. I'll give it a try.

**Comment by brendongo** [comment]
Agree with @mjambon I think filtering the directories out in TargetManager._expand_dir during the git ls-files call would be better. TargetManager.get_files should only be actual files. Nice find with the submodules behavior

**Comment by malexmave** [comment]
I figured I'd avoid adding another loop somewhere else and rather "recycle" an existing loop, but your argument about the semantics / expected behavior of the function make a lot more sense than shaving off a few microseconds (if even that). All maintainers of this repo should have write access to the branch, so feel free to make the change yourself if you know where you want the exclusion to happen :). Otherwise I can do it tomorrow (GMT).

**Comment by mjambon** [comment]
@malexmave I took over your branch and made a new PR (https://github.com/returntocorp/semgrep/pull/3701). Sorry about that, I normally try to avoid to take over people's work when they're almost done... It's an area of the code I wanted to get familiar with. Thanks again for the finding.

**Comment by malexmave** [comment]
@mjambon No worries, I'm happy it was helpful and the issue will be fixed. Closing this PR in favor of the other one, then :).

**Pull request closed without merging**
