### PR TITLE
Use logging instead of print to output to stderr

### PR DESCRIPTION
**Pull request by brendongo**
logging framework allows us to add debug logs to a file
and have more sanity around verbosity.

Does not yet create a file handler for the logs. Just reaches feature parity for now.

### CODE REVIEW

**Comment by brendongo** [comment]
Related to https://github.com/returntocorp/semgrep/issues/1170

**Comment by brendongo** [comment]
TODO: cli flags should set logging levels

**Review by aryx — APPROVED** [review]
looks good. Not a Python expert but this looks ok to me.

**Comment by aryx** [comment]
Now we need the log file ... I used to be able to see the semgrep-core command semgrep was using, but now -v does not display it anymore.

**Pull request merged**
