### PR TITLE
Add dataflow traces to SARIF output - Closes #6367

### LINKED ISSUE #6367: Add Dataflow Traces to SARIF Output Formatter
**Is your feature request related to a problem? Please describe.**
Currently the SARIF output only includes information about the `rule_match` location. This is fine for Semgrep rules matching on a single line of code, but for rules with mode `taint`, the output should include the dataflow details. The text formatter output already includes this information when passing the `--dataflow-traces` flag. This dataflow information should be extended to the SARIF output to allow better integration with tools supporting the SARIF standard.

**Describe the solution you'd like**
Add `codeFlows` and associated `threadFlowLocation` information to SARIF output formatter:

* [SARIF Formatter](https://github.com/returntocorp/semgrep/blob/develop/cli/src/semgrep/formatter/sarif.py)

SARIF Spec Details
* [codeFlows](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317740)
* [threadFlowLocation](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317751)

The `threadFlowLocation` information would include information from taint `sources`, `propagators`, and `sinks`.

**Describe alternatives you've considered**
An alternative is to use the raw JSON output and externally parse and transform this output data into SARIF. Since SARIF output is already possible using the `--sarif` flag, it would be preferable to modify this to include the additional data produced with `taint` mode.

**Use case**
Better integration with external tools that support `codeFlows` data in SARIF. An example of this is the `Analysis Steps` functionality within the popular VSCode plugin [SARIF Viewer](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer)

**Additional context**
Have already started some work on this, so glad to pick it up.

### PR DESCRIPTION
**Pull request by jharper-sec**
PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
Hmm, we're actually in the process of migrating the Semgrep Python wrapper to OCaml, so even if we merge this, someone would need to port this code to OCaml in a month, so probably better to wait for the migration to be over.

**Comment by jharper-sec** [comment]
Thanks for letting me know @aryx. Can the contributing documentation for the CLI component be updated? Outside of your comment, I can't find any indication of this planned change: https://semgrep.dev/docs/contributing/semgrep-contributing/

A notice to this effect on the contributing page will probably save contributors and the core team's time on useless PRs.

**Comment by aryx** [comment]
Well the port is still not officially decided. We started to experiment with the idea 4 weeks ago (see the semgrep-core/src/osemgrep directory) and we will probably go forward with it, so this explains why the docs are not updated. Sorry about that.

**Comment by aryx** [comment]
Ok I'll merge this, we don't know when the migration to OCaml will be ready, so let's merge this.
Just bit warned that the --dataflow-traces format is still exeperimental and will very likely change in the next few weeks, and
the python code may disappear (hopefully ported) in the next few months.

Otherwise thanks for the contribution!

**Review by aryx — APPROVED** [review]

**Pull request merged**
