### PR TITLE
add an option to only show a max number of lines per finding

### PR DESCRIPTION
**Pull request by ievans**
Not a perfect response to https://github.com/returntocorp/semgrep/issues/1482 but close.

A question for reviewers: should we truncate at 10 or 20 lines by default? We'll show the flag users can use to adjust it next to the truncation message.

Output example:

### the new default:
```
tests/unit/test_version.py
9:    with mock.patch("semgrep.version._fetch_latest_version") as fetched_mock:

tests/unit/test_yaml_parsing.py
40:    yaml = parse_config_string("testfile", yaml_contents, "file.py")
--------------------------------------------------------------------------------
44:        validate_single_rule("testfile", rule_dict)
--------------------------------------------------------------------------------
49:    config1 = dedent(
50:        """
51:    rules:
52:    - id: rule1
53:      pattern: $X == $X
54:      languages: [python]
55:      severity: INFO
56:      message: bad
57:    """
58:    )
--------------------------------------------------------------------------------
59:    config2 = dedent(
60:        """
61:    rules:
62:    - id: rule2
63:      pattern: $X == $Y
64:      languages: [python]
65:      severity: INFO
66:      message: good
67:    - id: rule3
68:      pattern: $X < $Y
69:      languages: [c]
70:      severity: INFO
71:      message: doog
72:    """
73:    )
--------------------------------------------------------------------------------
76:        tf1.write(config1.encode("utf-8"))
--------------------------------------------------------------------------------
77:        tf2.write(config2.encode("utf-8"))
ran 1 rules on 72 files: 318 findings
```

### max 4 lines
```
pipenv run semgrep --max-lines-per-finding=4 -e '$X.$Y("...", ...)' -l py
...
tests/unit/test_version.py
9:    with mock.patch("semgrep.version._fetch_latest_version") as fetched_mock:

tests/unit/test_yaml_parsing.py
40:    yaml = parse_config_string("testfile", yaml_contents, "file.py")
--------------------------------------------------------------------------------
44:        validate_single_rule("testfile", rule_dict)
--------------------------------------------------------------------------------
49:    config1 = dedent(
50:        """
51:    rules:
52:    - id: rule1
-------- [hid 6 additional lines, adjust with --max-lines-per-finding] ---------
59:    config2 = dedent(
60:        """
61:    rules:
62:    - id: rule2
-------- [hid 11 additional lines, adjust with --max-lines-per-finding] --------
76:        tf1.write(config1.encode("utf-8"))
--------------------------------------------------------------------------------
77:        tf2.write(config2.encode("utf-8"))
ran 1 rules on 72 files: 318 findings
```

### with max-lines = 1

```
pipenv run semgrep --max-lines-per-finding=1 -e '$X.$Y("...", ...)' -l py
...
tests/unit/test_version.py
9:    with mock.patch("semgrep.version._fetch_latest_version") as fetched_mock:

tests/unit/test_yaml_parsing.py
40:    yaml = parse_config_string("testfile", yaml_contents, "file.py")
44:        validate_single_rule("testfile", rule_dict)
49:    config1 = dedent(
59:    config2 = dedent(
76:        tf1.write(config1.encode("utf-8"))
77:        tf2.write(config2.encode("utf-8"))
ran 1 rules on 72 files: 318 findings
```

### CODE REVIEW

**Comment by dlukeomalley** [comment]
@ievans Interesting PR, thanks for opening! Couple questions pre-merge:

* What is the core problem you're solving with this feature? Curious how prevalent the issue has been for you and others and what alternative solutions you explored. Is it possible to more narrowly address #1482?
* Have you dry-run this functionality with anyone and what was their feedback? I have some UX/workflow concerns and am looking for external-to-us feedback. Would love to queue this up and get input before we have code to support/maintain going for.
* How far outside the scope of this work is it to address https://github.com/returntocorp/semgrep/issues/1990? With the change here I'm worried it looks like singular code blocks. It was difficult for me to visually distinguish what code the "... collapsed for brevity ..." applied to.

A crude idea I had was to minimally indent the "..." lines so they're clearly associated with the source code above. I introduce newlines as well below, which I don't love.

```sh
tests/e2e/test_api.py
9:    output = invoke_semgrep(
       ... hiding 3 additional lines ...

10:        Path("rules/eqeq.yaml"),

11:        [Path("targets/bad/invalid_python.py"), Path("targets/basic/stupid.py")],

11:        [Path("targets/bad/invalid_python.py"), Path("targets/basic/stupid.py")],

14:    captured = capsys.readouterr()

15:    assert len(output["errors"]) == 1

16:    assert len(output["results"]) == 1

21:    x = subprocess.run(
       ... hiding 9 additional lines ...
```

**Comment by dan5382** [comment]
@dlukeomalley I like your solution there. I guess I just have two points
1. Are you intending to give the total number of lines that they can uncover? If so maybe we can 'show me the next 3 lines' ie. what does the viewer get by knowing the total line count? Do they care about that? Or do they care about flooding their screen with code? 
2. This goes along with point 1. I'd love to direct a user to the next step of being able to expose those lines. 

What might this look like? 
```
tests/e2e/test_api.py
9:    output = invoke_semgrep(
       ... view all 3 lines | more

10:        Path("rules/eqeq.yaml"),

11:        [Path("targets/bad/invalid_python.py"), Path("targets/basic/stupid.py")],

11:        [Path("targets/bad/invalid_python.py"), Path("targets/basic/stupid.py")],

14:    captured = capsys.readouterr()
       ... view next 5 lines | more

15:    assert len(output["errors"]) == 1

16:    assert len(output["results"]) == 1

21:    x = subprocess.run(
       ... view next 5 lines | more
```

**Comment by ievans** [comment]
@dlukeomalley @dan5382 thanks for the feedback. I made this because I had the same problem as #1482 today and I have not seen a workaround for it. Since this is behind a flag, I don't plan to dry run it with anyone but I welcome feedback from @msorens and @xmo-odoo who filed related issues but defer to code reviewers to decide whether or not it is useful enough to merge. If someone wants to work on #1990 in this branch they are welcome to, but these changes are tiny so I won't block on it.

@dan5382 to your comments true that there isn't a crazy amount of value, for most queries, to showing the number of lines that were trimmed. Unfortunately the CLI isn't interactive so I can't think of a good way to add "show hidden"-esque functionality.

**Comment by msorens** [comment]
1. This definitely has value to me just as it is: it gives me the option of seeing the full output or dialing it down to whatever line count I want.
2. I imagine that #1990, once addressed, will add in either blank lines or separator lines whether or not this flag is used, so that question is somewhat orthogonal to this PR.
3. Interesting notion to display the suppressed line count: I would lean towards the more terse `... hiding 9 additional lines ...` as @dlukeomalley suggested.

**Comment by ievans** [comment]
@dlukeomalley @msorens @dan5382 I tweaked it a bit tonight. Take a look at the top-level issue description and let me know what you think.

**Comment by dlukeomalley** [comment]
A small tweak and a big improvement. Thank you @ievans for the follow-up 🙏

**Comment by msorens** [comment]
Hmmm, I might be missing something but the output is much more confusing now. Near as I can tell:
1. If two adjacent findings contain multiple lines each, then **include** a separator line between them.
2. If two adjacent findings contain a single line each, do **not** include a separator line.
3. If a multiple-line finding is adjacent to a single line finding, do **not** include a separator line.

Parsing this, for example, takes way too much cognitive effort--first glance I thought all of these lines were a single finding, then I noticed 110 was missing so thought it was two findings, but then realized it was _four_ findings:
image

**Comment by ievans** [comment]
Yes that's a very fair point @msorens . Your point #3 I'd consider a bug and I can fix that at some point (I am working on a background thread where I'm using this branch, but it's not an active priority). If the behavior in #3 was to include a separator line, it might look like proposal A. I threw in a few variations to get comments from reviewers. I think A is my personal preference.

proposal A
```
semgrep/autofix.py
26:    lines = contents.split(SPLIT_CHAR)
32:    start_line = start_obj.get("line", 1) - 1  # start_line is 1 indexed
33:    start_col = start_obj.get("col", 1) - 1  # start_col is 1 indexed
35:    end_line = end_obj.get("line", 1) - 1  # end_line is 1 indexed
36:    end_col = end_obj.get("col", 1) - 1  # end_line is 1 indexed
107:                regex = fix_regex.get("regex")
108:                replacement = fix_regex.get("replacement")
109:                count = fix_regex.get("count", 0)
--------------------------------------------------------------------------------
111:                    raise SemgrepError(
112:                        "'regex' and 'replacement' values required when using 'fix-regex'"
113:                    )
--------------------------------------------------------------------------------
117:                    raise SemgrepError(
118:                        "optional 'count' value must be an integer when using 'fix-regex'"
119:                    )
--------------------------------------------------------------------------------
143:        logger.info(f"no files modified.")
```

proposal B (just show discontinuities)


```
semgrep/autofix.py
26:    lines = contents.split(SPLIT_CHAR)
32:    start_line = start_obj.get("line", 1) - 1  # start_line is 1 indexed
33:    start_col = start_obj.get("col", 1) - 1  # start_col is 1 indexed
35:    end_line = end_obj.get("line", 1) - 1  # end_line is 1 indexed
36:    end_col = end_obj.get("col", 1) - 1  # end_line is 1 indexed
--------------------------------------------------------------------------------
107:                regex = fix_regex.get("regex")
108:                replacement = fix_regex.get("replacement")
109:                count = fix_regex.get("count", 0)
--------------------------------------------------------------------------------
111:                    raise SemgrepError(
112:                        "'regex' and 'replacement' values required when using 'fix-regex'"
113:                    )
--------------------------------------------------------------------------------
117:                    raise SemgrepError(
118:                        "optional 'count' value must be an integer when using 'fix-regex'"
119:                    )
--------------------------------------------------------------------------------
143:        logger.info(f"no files modified.")
```

proposal C (always separate)

```
semgrep/autofix.py
26:    lines = contents.split(SPLIT_CHAR)
--------------------------------------------------------------------------------
32:    start_line = start_obj.get("line", 1) - 1  # start_line is 1 indexed
--------------------------------------------------------------------------------
33:    start_col = start_obj.get("col", 1) - 1  # start_col is 1 indexed
--------------------------------------------------------------------------------
35:    end_line = end_obj.get("line", 1) - 1  # end_line is 1 indexed
--------------------------------------------------------------------------------
36:    end_col = end_obj.get("col", 1) - 1  # end_line is 1 indexed
--------------------------------------------------------------------------------
107:                regex = fix_regex.get("regex")
108:                replacement = fix_regex.get("replacement")
109:                count = fix_regex.get("count", 0)
--------------------------------------------------------------------------------
111:                    raise SemgrepError(
112:                        "'regex' and 'replacement' values required when using 'fix-regex'"
113:                    )
--------------------------------------------------------------------------------
117:                    raise SemgrepError(
118:                        "optional 'count' value must be an integer when using 'fix-regex'"
119:                    )
--------------------------------------------------------------------------------
143:        logger.info(f"no files modified.")
```

**Comment by msorens** [comment]
Thanks for the feedback, Isaac! Looking from a UX perspective, though, the only viable choice among those is (C). One should be able to tell at a glance what is going on.

While I completely agree (C) seems noisy/verbose, it is the only one that makes things easy and obvious for the user; the others are just too confusing; you have to put in effort to figure them out.

**Comment by ievans** [comment]
@msorens thanks for the feedback. I do agree (C) is much clearer. What do you think about a proposal where (C) is the default for --max-lines-per-finding > 1, but if --max-lines-per-finding=1 then we use (A)?

**Comment by msorens** [comment]
@ievans Yes, I like that! If someone is asking for 1 line then they certainly know that every line is separate, so you can make less cluttered, more terse output. Thanks for doing this!

**Comment by xmo-odoo** [comment]
Just commenting to say that this looks good and would largely solve #1482 (which as far as I'm concerned could be closed), especially with the toggling between separators / no separators based on lines of context following the discussion, that looks like a good mix of clarity and terseness.

**Comment by ievans** [comment]
@msorens I had a free minute and implemented the proposal we workshopped! See top-level PR description for the new output.

@dlukeomalley this is going to change default output now, so I'd love to have you schedule it for a dry run. 

@aryx @brendongo thoughts on ^ ?

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
Ok merging it; looks good.

**Pull request merged**
