### PR TITLE
semgrep/setup.py: exclude tests from packaging

### LINKED ISSUE #2633: pypi dist installs a package called `tests`
**Describe the bug**

After I `pip install semgrep`, I have a package called `tests` in my virtualenv. 

I'm aware of the debate about whether or not to include tests in your sdist, and take no particular view on that, but if you're going to do it, please don't put them in the top level of the dist. I feel like cluttering the package namespace in this way is incorrect.

**To Reproduce**

```
$ pip install semgrep
$ python -c "import tests.conftest"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rav/work/synapse/env3/lib/python3.8/site-packages/tests/conftest.py", line 13, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Expected behavior**

semgrep's tests should not be installed in the root of the package namespace.

**What is the priority of the bug to you?**

P2

### PR DESCRIPTION
**Pull request by priv-kweihmann**
Fixes #2633

Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>

PR checklist:

- [ ] Documentation is up-to-date
- [ ] Changelog is up-to-date
- [ ] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by ievans** [comment]
thanks for this contribution! @brendongo can you review?

**Comment by brendongo** [comment]
I think running `SEMGREP_SKIP_BIN=1 python3 setup.py bdist_wheel` still generates a wheel with the tests folder for me

**Comment by priv-kweihmann** [comment]
@brendongo you're right :disappointed: - Didn't saw that the tests actually land in a subpackage - latest commit you address that

**Comment by brendongo** [comment]
Would `*/tests/*` work? Wondering how to avoid a file with the name test in it being ignored. Or is this only for top level package names and not files?

**Comment by brendongo** [comment]
On second thought seems fine as is. Thanks for the contribution @priv-kweihmann

**Review by brendongo — APPROVED** [review]

**Pull request merged**
