### PR TITLE
minimal typescript support

### PR DESCRIPTION
**Pull request by mjambon**
It doesn't have tests at this point but shouldn't break anything either.

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
What is going on with the tests failures inCI?

**Comment by mjambon** [comment]
> What is going on with the tests failures inCI?

This was due to changes in `combine_infos` which I hadn't merged into my branch.

**Comment by mjambon** [comment]
I added all the pure javascript (non-jsx) tests as typescript tests using symlinks. I added just one typescript-specific test. Everything passed without particular difficulties, which is nice.

**Comment by aryx** [comment]
great! let's merge

**Pull request merged**
