### PR TITLE
core: tests: Add three more tests for metavariable-pattern

### PR DESCRIPTION
**Pull request by IagoAbal**
PR checklist:
- changelog update not needed

### CODE REVIEW

**Comment by emjin** [comment]
I feel like with metavariable-pattern there's very little reason to have equivalences---it's not hard to express equivalences as a pattern-either now. Especially true if we allowed something like

```
- metavariable-pattern:          
   metavariable: $REQUEST, $REQUEST2
   patterns:           
   - pattern-either:              
      - pattern: request.$W.get(...)     
      - pattern: request.$W[...]
```

**Comment by aryx** [comment]
looks good. The failures are probably because semgrep-rules changed and we need to regenerate some snapshots.

**Comment by IagoAbal** [comment]
Thanks for the hint I'll take a look!

**Comment by IagoAbal** [comment]
Tests passing now 👍

**Review by aryx — APPROVED** [review]

**Pull request merged**
