### PR TITLE
Use the right semgrep-core binary during pytest in CI

### PR DESCRIPTION
**Pull request by aryx**
We don't need anymore build-semgrep-pro.

test plan:
green CI check and hopefully the next release will now
pass

### CODE REVIEW

**Review by IagoAbal — APPROVED** [review]

**Review by akuhlens — CHANGES_REQUESTED** [review]
🙈 This looks like what I would expect. We definitely want to port test_ci.py to pro before landing this so that we don't lose the ci tests.

**Comment by aryx** [comment]
@akuhlens I've merged develop so this should work better now.

**Comment by emjin** [comment]
@akuhlens Do you know roughly what it would take to port test_ci.py now that you've done some work around porting workflows?

**Comment by aryx** [comment]
We don't need to port test_ci.py
test_ci.py does work perfectly without semgrep-pro.
You just need to port test_intrafile_taint.py which is 20 lines long.

**Comment by emjin** [comment]
It works, but we're testing with `--oss-only`, which we don't want any of our customers to be running. Granted, that might not matter today for most of the tests, but we should make it easy to add tests where it does matter. Or, we might add more `pro-intrafile` features (especially after porting ci to osemgrep) and that might might the flag matter for existing tests.

**Comment by aryx** [comment]
Maybe we can make this oss-only a global or something in test_ci.py and then run test_ci.py from the semgrep-pro repo with --pro instead (or nothing since it's now the default).

**Pull request merged**
