### PR TITLE
use junit_xml_2

### LINKED ISSUE #2865: Upgrade junit-xml -> junit-xml-2
The issue is that "junit-xml source is not available in PyPI for v1.9". See the original suggestion and patch at: https://github.com/Homebrew/homebrew-core/pull/73902#issuecomment-806632065

### PR DESCRIPTION
**Pull request by dtrodrigues**
Fixes https://github.com/returntocorp/semgrep/issues/2865
PR checklist:
- [ ] changelog is up to date

### CODE REVIEW

**Comment by mjambon** [comment]
@dtrodrigues thank you for your contribution!

I don't know what's failing. Presumably some API change in the juniit-xml library? If you can find out what's failing, that's great. I assigned the review to someone more knowledgeable than me about the python code in semgrep.

**Comment by dtrodrigues** [comment]
It looks like updating the `Pipfile.lock` file to reflect the new dependency name resolved the test failures.

**Comment by brendongo** [comment]
We probably need to update the lines that import junit_xml to `import junit_xml_2` like in https://github.com/returntocorp/semgrep/pull/1761/files

**Comment by mschwager** [comment]
See https://github.com/returntocorp/semgrep/pull/2895 for an alternate solution :+1:

**Comment by brendongo** [comment]
#2895 seems like less effort maintaining given that we're the ones who published junit-xml-2 :D Going to merge that in instead. Thanks @dtrodrigues

**Pull request closed without merging**
