### PR TITLE
Add timeout to requests

### PR DESCRIPTION
**Pull request by brendongo**

### CODE REVIEW

**Comment by minusworld** [comment]
https://github.com/returntocorp/semgrep-rules/blob/develop/python/requests/best-practice/use-timeout.yaml 😶

**Review by mschwager — APPROVED** [review]
Was this causing an issue somewhere, or just best practices?

**Comment by brendongo** [comment]
We were failing our semgrep registry rules (currently only run after merges while @underyx and @nbrahms still have it WIP)

**Comment by mschwager** [comment]
> We were failing our semgrep registry rules (currently only run after merges while @underyx and @nbrahms still have it WIP)

Now that I think about it, do we want to catch timeout errors and show a convenient message to the user?

**Comment by underyx** [comment]
@brendongo for the record, it runs before merges too, but we only show semgrep results that are new in the PR. On master & develop we run a full scan.

**Comment by brendongo** [comment]
> > We were failing our semgrep registry rules (currently only run after merges while @underyx and @nbrahms still have it WIP)
> 
> Now that I think about it, do we want to catch timeout errors and show a convenient message to the user?

Yeah that's a good idea. Will modify PR with that.

**Comment by brendongo** [comment]
Actually will do a follow up PR so full scans on develop don't report failures.

**Pull request merged**
