### PR TITLE
Return a unique ID for each metavariables

### PR DESCRIPTION
**Pull request by aryx**

### CODE REVIEW

**Comment by aryx** [comment]
@ievans how do I update all those .expected....json files?
I remember ScottMcPeak was using an environment variable like OVERRIDE_EXPECTED
that you could use when you know what you're doing and you want to update easily those expected files.

**Comment by ievans** [comment]
@aryx that's a good idea -- not implemented in the test suite for the expected.json, it is a manual process right now unfortunately

**Review by ievans — DISMISSED** [review]
is an md5 necessary? ie could we create the hashes and then just turn them into integer indices so the output is cleaner, or do we actually want the interface to have a unique keyed hash?

**Comment by aryx** [comment]
As you want. It was just easy to implement like this, to have, like for the variables which have a single unique id, to return a unique id for more complex AST elements so that sgrep_lint can easily and quickly
check if 2 metavars from 2 different matches are equal.
What do you prefer? I can generate a unique, incremented id, for complex AST too.

**Comment by nbrahms** [comment]
> is an md5 necessary? ie could we create the hashes and then just turn them into integer indices so the output is cleaner, or do we actually want the interface to have a unique keyed hash?

I think we want collision likelihood to be low. Since this presumably isn't every human consumed, a 128-bit hash seems more useful than an integer.

**Comment by brendongo** [comment]
Rebasing should fix the bento failures

**Comment by brendongo** [comment]
Was there a ticket tracking this ask and the applications?

**Comment by aryx** [comment]
blocked on https://github.com/returntocorp/sgrep/issues/404

**Comment by aryx** [comment]
@DrewDennison when do you think you will have the OVERRIDE environment variable trick in run-test-lint.sh?

**Comment by aryx** [comment]
See the code of Scott with UPDATE_EXPECTED_OUTPUT at:
https://github.com/returntocorp/echelon-backend/blob/develop/analysis/analyzers/r2c/js-taint/src/lib/utils.ml

**Comment by DrewDennison** [comment]
@aryx tests pass

**Review by DrewDennison — APPROVED** [review]

**Review by ievans — APPROVED** [review]

**Pull request merged**
