### PR TITLE
feat(rust): Support method chain patterns

### PR DESCRIPTION
**Pull request by kopecs**
This PR adds support for using an ellipsis to match method & field chains to Rust, similar to existing support for Java, C#, et al.

Test plan: included tests

PR checklist:

- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Review by emjin — APPROVED** [review]
Since you also updated the Rust tree-sitter-parser, mind rerunning parsing-stats to note the change in parse-percentage?

**Comment by kopecs** [comment]
Can you point me to where I should put the results of that run? Also, since I just modified our extensions to the syntax and not the base language grammar is that meaningful?

**Comment by emjin** [comment]
Just the PR is fine; I was just curious. Did you not modify the base language grammar? Looking at the `tree-sitter-lang` submodule changes I assumed you updated the version of tree-sitter for Rust.

**Comment by kopecs** [comment]
Previous:

Line count: 4556048
Line coverage: 98.930%

After this update:

Line count: 4555959
Line coverage: 98.929%

**Pull request merged**
