### PR TITLE
Add lsp server and command

### PR DESCRIPTION
**Pull request by p4p3r**
This PR adds the ability to run Semgrep as a server for the Language Server Protocol.
The new `lsp` command is added to allow running Semgrep in this new mode.

Currently supported features are:
- specifying the rules to use as a command line option when the server is started
- locally caching the rules to speed up scanning
- scanning files as they are open and saved
- providing code actions for rules that support fixes

Outstanding improvements (possibly in a follow-up PR):
- [ ] use Rule and RuleMatch instead of raw json/dict access
- [x] use the existing config_resolver when downloading/caching rules instead of duplicating some of its logic
- [ ] refactor Semgrep execution into semgrep_main (and ideally allow for scanning files in memory, instead of having to repeatedly writing them to disk...)

PR checklist:

- [ ] Testsuite
- [ ] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by aryx** [comment]
This is great!

**Comment by emjin** [comment]
I'm so excited!!

**Comment by aryx** [comment]
Can we get this in?

**Comment by underyx** [comment]
force pushed to rebase and fix the conflicts

**Review by underyx — APPROVED** [review]

**Pull request merged**
