### PR TITLE
chore: Set timeout for semgrep-comparison argo job (10min)

### PR DESCRIPTION
**Pull request by minusworld**
This sets a timeout on the semgrep-comparison argo workflow job of 10 minutes. Currently it's at an hour, this will set it at 10 minutes. Note: the timeout will occur between 10-15 minutes because the reaper task that watches this timeout runs every 5 minutes.

### CODE REVIEW

**Review by IagoAbal — APPROVED** [review]
Thanks!

**Comment by IagoAbal** [comment]
It does seem to work, on this PR the workflow timed out before 15 min.

**Comment by aryx** [comment]
You need to modify the .jsonnet
Note that last week I've switched to the more traditional jsonnet+yq instead of ojsonnet that still have many bugs,
so potentially you could add your .jsonnet in the Makefile

**Review by aryx — APPROVED** [review]
why there is a need for 2 timeout configuration?

**Comment by aryx** [comment]
the env and the field. weird.

**Comment by minusworld** [comment]
The environment variable is only used to pass the data into the `curl` request, which is good practice when using dynamic information like `{{ github.* }}`. It's not necessary to use this for a constant value, but the `jsonnet` is set up in such a way to put all workflow parameters in an environment variable first for this reason.

**Pull request merged**
