### PR TITLE
Allow backend sending rules as json instead of yaml string

### PR DESCRIPTION
**Pull request by brendongo**
PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by brendongo** [comment]
@chmccreery https://github.com/returntocorp/semgrep/blob/develop/cli/src/semgrep/config_resolver.py#L634 is a little weird so it was hard to track this down. If we have time might be worth making this less fragile :D

**Review by chmccreery — APPROVED** [review]
Very weird, I could swear I already made this change. Maybe there was a bad merge resolution or something. Thanks for tracking down! Agree it's a bit fragile...

**Review by underyx — APPROVED** [review]

**Comment by bmahe** [comment]
Hi @brendongo @chmccreery @underyx ,

I am not clear on the purpose of this change.
Would it be possible to:
* Add a description of the purpose of the change?
* Add a test. It looks like the original state was not correct and we had no test to catch that. So can we add a test?

**Comment by underyx** [comment]
@bmahe note that the old line from this PR never made it to a release. So the description would be: this was a follow-up to https://github.com/returntocorp/semgrep/pull/5981 to add support for when the backend sends rules serialized as JSON instead of YAML.

**Comment by chmccreery** [comment]
Agree with the concern though that this wasn't caught by existing CI tests. @brendongo what prompted this change/what is the use-case that was not supported?

**Comment by underyx** [comment]
> what prompted this change/what is the use-case that was not supported?

We changed the backend today to use JSON serialization instead of YAML serialization for this field.

**Comment by chmccreery** [comment]
> We changed the backend today to use JSON serialization instead of YAML serialization for this field.

So shouldn't we update at least some of the tests to use JSON serialized data instead of YAML to prevent an effective revert of this change?

**Comment by underyx** [comment]
yep, that sounds like a good idea

**Comment by underyx** [comment]
I looked into it and there's no tests for any of this config parsing at all, no test case to extend or modify. Unfortunately I don't have the time to write the whole test suite for this so I'm dropping your request @bmahe @chmccreery.

**Comment by chmccreery** [comment]
Ok, I've made a linear ticket for this https://linear.app/r2c/issue/APP-2245/add-tests-for-config-parsing-in-semgrep-cli

**Pull request merged**
