### PR TITLE
Add 'dockerfile' as a Dockerfile file name

### LINKED ISSUE #7824: Dockerfile language doesn't recognize lowercase `dockerfile` as relevant
**Describe the bug**
Copy semgrep/Dockerfile to a new folder. Rename it to dockerfile. Run semgrep -e "RUN ..." -l docker

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

### PR DESCRIPTION
**Pull request by emjin**
Dockerfiles can be called `dockerfile` as well as `Dockerfile`. Support both.

Closes https://github.com/returntocorp/semgrep/issues/7824

Test plan: see tests

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
@mjambon  is currently rewriting how we process lang.json, so you might need to rebase?

**Comment by mjambon** [comment]
I merged the change in semgrep-langs. We're waiting for https://github.com/returntocorp/semgrep/pull/7828 to get merged.

**Comment by mjambon** [comment]
@emjin the `develop` branch now uses the latest semgrep-langs which includes your change for dockerfile. This branch can use the same version of semgrep-langs and that should solve the conflict.

**Review by mjambon — APPROVED** [review]

**Comment by mjambon** [comment]
The conflict should be solved now. We can merge as soon as the tests pass.

**Review by mjambon — APPROVED** [review]

**Comment by emjin** [comment]
Thanks @mjambon for solving the conflict for me!

**Pull request merged**
