### PR TITLE
[OCaml] Retain all(?) parens during conversion to generic-AST to repair autofix

### LINKED ISSUE #5078: OCaml Matches are leaving a hanging closing-parenthesis, breaking autofix
**Describe the bug**
When matching a simple construct like `function_name $X`, if there's a parenthetical subexpression in the match, semgrep leaves the *closing* paren of that match excluded.

```yaml
rules:
   - id: replace-function
     languages: [ocaml]
     pattern: somefunc $X
     fix: Lwt.return_error (somefunc ($X))
```

```ocaml
somefunc (`Blah 123)
```

Produces this (syntactically invalid 😓):

```ocaml
Lwt.return_error (somefunc (`Blah 123)))
```

**To Reproduce**
https://semgrep.dev/s/YNko

**Screenshots**
Screen Shot 2022-04-22 at 4 24 03 PM

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
`pip3 install semgrep`

### PR DESCRIPTION
**Pull request by ELLIOTTCABLE**
This PR fixes autofix on, well, a *lot* of OCaml code — at least a dozen occurrences of #5078 on the very first `semgrep` we ran on our codebase.

In particular, this passes parentheses (`ParenExpr`) through into the generic-AST untouched, instead of dropping them.

----

As this is my first PR, I need a little direction. Some questions:

1. My primary use for semgrep is the autofix; but does this affect simple matching? There don't seem to be many (any?) tests for OCaml matching in the codebase, so I don't feel particularly secure in my change being safe or effective.

2. This currently branches off of #5085, but I can easily rebase it if y'all reject that change.

----

PR checklist:

- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

/fixes #5078

### CODE REVIEW

**Comment by aryx** [comment]
yes can you merge develop so that we just see the relevant changes?
Also not sure what's going on with pre-commit ocaml.
Did you do pre-commit install on your machine? I think you also need to opam install ocamlformat with opam install --deps-only semgrep-core/dev/ to have ocamlformat 0.21.0

**Comment by aryx** [comment]
ping @ELLIOTTCABLE

**Comment by ELLIOTTCABLE** [comment]
I think I *finally* figured `pre-commit` out. It was, uh, unintuitive for a non-pythoneer. But! Got ocamlformat running correctly according to the config in the codebase, that should hopefully fix CI.

Let me know if you need anything else!

**Comment by aryx** [comment]
I've fixed the CI error in https://github.com/returntocorp/semgrep/pull/5170 and merged.
Thx a lot!

**Pull request closed without merging**
