### PR TITLE
tests: Make a test fail if we cannot read the rules file

### PR DESCRIPTION
**Pull request by IagoAbal**
Make a test fail when we cannot successfully read the rules file, rather than silently consider it as a passing test.

And move all Elixir tests to Pro.

test plan:
See semgrep/semgrep-proprietary#1241

### CODE REVIEW

**Review by amchiclet — APPROVED** [review]
Thanks! 🚀🚀🚀

I think the failing workflow (alcotest_ext related) just needs a rebase, right?

Also I don't see a changelog (the checkbox is ticked).

**Comment by IagoAbal** [comment]
> I think the failing workflow (alcotest_ext related) just needs a rebase, right?

Needs Martin to fix Pro build, it was broken by one of his latest PRs merged.

> Also I don't see a changelog (the checkbox is ticked).

I ticked it because I don't think a changelog is needed, this doesn't seem like user facing, do you disagree? I guess Pad already wrote a changelog entry when he moved Elixir to Pro. For stuff that only matters to developers, we have the Git history.

**Comment by amchiclet** [comment]
I don't think this PR needs a changelog. I was confused by the checklist.

**Comment by IagoAbal** [comment]
The only failing test is `semgrep-compare` which is timing out, maybe there is too much load in the ArgoWorkflows runners.

**Pull request merged**
