### PR TITLE
fix(go): fix range of raw string literals

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR fixes the tokens for raw string literals in Go, to be faithful to the range of the string in the source text.

## Why:
Currently, raw string literals in Go have tokens which capture just the contents of the string, and not the delimiters. This causes issues with metavariable range tracking, because a metavariable matching a raw string literal will start at the delimiter, but only go for the range of the contents of the delimited string, meaning that it will capture two characters less than the entire source-text string. This messes with Autofix and message interpolation in the Playground.

## How:
I made it such that the token produced from the tree-sitter parser instead now has the entire original source-text string inside of it, which will give it the proper length.

## Test plan:
For a file 
```
"hello"
`hello`
```
before we had:
image

now we have 
image

Note that in the second example of the string, the token is now surrounded by backticks, which accurately reflects the range that it corresponds to.

For a file
```
x = `hello`
```
after this change, we get:
image

and before we had:
image

Note how before, the `message` was cut off, and now it properly has the entire statement.

Closes PA-2206

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by nmote** [comment]
Does this fix #6287?

**Comment by brandonspark** [comment]
@nmote Yes!
image

**Comment by nmote** [comment]
Cool! Could you use that as a test case?

**Comment by nmote** [comment]
(or something similar)

**Comment by brandonspark** [comment]
@nmote ah yeah, I was trying to think of how to test this, and couldn't come up with a good way. I didn't think of autofix. Will do.

**Review by nmote — APPROVED** [review]
Nice! When I suggested testing using autofix, I forgot that since Go doesn't have AST-based autofix, the simpler autofix testing that we have for semgrep-core won't work. You've added an e2e test which is fine, but they can also be a bit annoying to maintain. I'm content with the manual test plan. I'll let you decide whether you want to include the test or not.

**Comment by brandonspark** [comment]
> Nice! When I suggested testing using autofix, I forgot that since Go doesn't have AST-based autofix, the simpler autofix testing that we have for semgrep-core won't work. You've added an e2e test which is fine, but they can also be a bit annoying to maintain. I'm content with the manual test plan. I'll let you decide whether you want to include the test or not.

OK, I think I'll take it out then, since it doesn't really fit precedence with the other tests, and I don't really foresee this changing.

**Pull request merged**
