### PR TITLE
feat(promql): add initial translations

### PR DESCRIPTION
**Pull request by MichaHoffmann**
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

Depends on: https://github.com/returntocorp/semgrep-interfaces/pull/93 after which the submodule needs to be updated

### CODE REVIEW

**Comment by MichaHoffmann** [comment]
This is intended as a tool to help lint alerting expressions for prometheus. Since they usually depend on the particular metrics and how they are collected which makes semgrep a great tool to write in-house rules. Right now this allows to write rules like:
```
rules:
- id: too-long-range-in-query
  languages: [yaml]
  severity: WARNING
  patterns:
  - pattern-inside: |
      expr: $PROMQL
  - metavariable-pattern:
      language: promql 
      metavariable: $PROMQL
      patterns:
      - pattern-either: 
        - pattern: $F(...)[$RANGE:$STEP]
        - pattern: $F(...)[$RANGE:]
        - pattern: $X{...}[$RANGE]
      - metavariable-regex:
          metavariable: $RANGE
          regex: '(?![0-9]{1,2}(m|h))'
  message: Ranges should usually a small and expressed in minutes or hours
```
which applied to
```
groups:
- name: example
  rules:
  - alert: BadAlert
    expr: sum_over_time(some_metric{foo="bar", bar="baz"}[1y]) > 0
    labels:
      severity: test
    annotations:
      summary: An alert that should be found because long range
  - alert: GoodAlert
    expr: increase(some_metric[10m]) > 0
    labels:
      severity: test
    annotations:
      summary: An harmless alert that should not be found
```
will match the proper alert:
```
⬢[mhoffm@toolbox semgrep]$ ~/.local/bin/semgrep -c ../rule.yaml ../alertmanager.yaml


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file tracked by git with 1 Code rule:
  Scanning 1 file.
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00                                         


┌────────────────┐
│ 1 Code Finding │
└────────────────┘

    ../alertmanager.yaml
       too-long-range-in-query
          Ranges should usually a small and expressed in minutes or hours

            5┆ expr: sum_over_time(some_metric{foo="bar", bar="baz"}[1y]) > 0



┌──────────────┐
│ Scan Summary │
└──────────────┘

Ran 1 rule on 1 file: 1 finding.
```

 TODO for followup PR:
 - usage of unsafe fake bracket leads to weird highlighting of some captures
 - binary operators should support ellipses
 - binary operators groupings are ignored for now
 - support offset and @ modifier for subqueries and selectors
- code cleanup; but this seems to work somewhat so good enough for now

**Comment by cgdolan** [comment]
@MichaHoffmann Thanks so much for contributing support for PromQL, super excited to see this! We use Prometheus extensively at Semgrep and this is going to be really useful both externally and internally. I've approved the CI runs that were pending to continue moving this PR forward.

**Comment by MichaHoffmann** [comment]
> @MichaHoffmann Thanks so much for contributing support for PromQL, super excited to see this! We use Prometheus extensively at Semgrep and this is going to be really useful both externally and internally. I've approved the CI runs that were pending to continue moving this PR forward.

Thanks! I think test failures were because the bump of `semgrep_interfaces` i'm not sure what to do about them tbh. Do you have an idea?

**Comment by cgdolan** [comment]
> > @MichaHoffmann Thanks so much for contributing support for PromQL, super excited to see this! We use Prometheus extensively at Semgrep and this is going to be really useful both externally and internally. I've approved the CI runs that were pending to continue moving this PR forward.
> 
> Thanks! I think test failures were because the bump of `semgrep_interfaces` i'm not sure what to do about them tbh. Do you have an idea?

Yeah, looks like the change adding '.h' to both 'c' and 'cpp' languages may be problematic:

```
        """
        Ensures one-to-one assumption of mapping from reverse file extensions to language in lang.json
        """
        exts = set()
        for d in LANGUAGE.definition_by_id.values():
            for e in d.reverse_exts:
                if e in exts:
>                   raise Exception(
                        f"Duplicate reverse extension {e} in lang.json occurring in language {d.id}"
                    )
E                   Exception: Duplicate reverse extension .h in lang.json occurring in language cpp
```

@aryx @mjambon How should we handle file extensions that belong to multiple languages?

**Comment by aryx** [comment]
I think we should allow the same extension to be used by different languages (for instance .pl can be perl files or Prolog files).
@mjambon we should remove this Duplicate reverse extension check.

**Comment by MichaHoffmann** [comment]
rebased on latest develop to fix conflicts

**Comment by cgdolan** [comment]
> I think we should allow the same extension to be used by different languages (for instance .pl can be perl files or Prolog files). @mjambon we should remove this Duplicate reverse extension check.

I prepped a PR for this here: https://github.com/returntocorp/semgrep/pull/8288

**Comment by cgdolan** [comment]
> rebased on latest develop to fix conflicts

@MichaHoffmann Would you mind rebasing to pull in the fix for the test failure that was just merged?

**Comment by MichaHoffmann** [comment]
> > rebased on latest develop to fix conflicts
> 
> @MichaHoffmann Would you mind rebasing to pull in the fix for the test failure that was just merged?

rebased and reformatted with ocamlformat.

**Comment by MichaHoffmann** [comment]
Sorry, can you rerun again? I had to fix test failures in cli end to end tests. The output was missing `promql` as supported language.

**Comment by MichaHoffmann** [comment]
sorry, i updated the snapshots using the suggested pytest command; can you run again please?

**Comment by MichaHoffmann** [comment]
CI failure seems is unrelated i think

**Comment by cgdolan** [comment]
> CI failure seems is unrelated i think

Yeah :/ Really sorry for the friction here, we're working on a fix in: https://github.com/returntocorp/semgrep/pull/8291

**Comment by cgdolan** [comment]
Fix has been merged and we're fairly confident this PR will pass the aarch64 build once merged too. I think this is ready for review now and added a few folks who can take a look.

**Review by mjambon — APPROVED** [review]
This looks great.

**Comment by MichaHoffmann** [comment]
rebased on latest develop to get #8291

**Pull request merged**
