### PR TITLE
chore: create Homebrew PRs in standard format

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

---

This patch modifies semgrep's release workflow to create Homebrew PRs in the standard format (https://docs.brew.sh/Formula-Cookbook#commit).

Commits not in this standard format are rejected. For example, https://github.com/Homebrew/homebrew-core/pull/131054 is replaced by https://github.com/Homebrew/homebrew-core/pull/131058.

### CODE REVIEW

**Comment by spencerdrak** [comment]
@ZhongRuoyu I'll take a look at this shortly and run a dry-run before approving.

Thank you very much for opening!

**Comment by spencerdrak** [comment]
[Here's the dry-run of this workflow](https://github.com/returntocorp/semgrep/actions/runs/4992922221) - I'll wait until this is successful to approve, but I don't see any reason why it wouldn't be. Thanks!

**Comment by spencerdrak** [comment]
Release dry-run was successful, going to merge this - thanks again @ZhongRuoyu!

**Review by spencerdrak — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
No problem -- thanks @spencerdrak!

**Pull request merged**
