### PR TITLE
Sophia/7992 adding date comparison Closes #7992

### LINKED ISSUE #7992: Expiration date check in the metavariable-comparison condition
Hi guys!
I would like to check if a date has expired, as in this simple example: https://semgrep.dev/playground/s/DrwY

In the case where you are asking yourself for practical examples. I need this feature to verify inside some XML files that some TLS certificates are not expired.
(Example: https://developer.android.com/training/articles/security-config look at the `<pin-set>` expiration attribute)

As always, thank you guys! :heart:

### PR DESCRIPTION
**Pull request by SophiaSR**
This adds the functionality requested in issue 7992. Currently supports strptime("yyyy-mm-dd") only as a way to create a date. Also has today() to get the current date, again currently supporting only year, month, and date. 

PR checklist:

- [ ] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [ ] Tests included or PR comment includes a reproducible test plan
- [ ] Documentation is up-to-date
- [ ] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [ ] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
Your PR contains code from another PR. You need to start from develop each time.

**Review by aryx — CHANGES_REQUESTED** [review]
Restart from develop

**Comment by brandonspark** [comment]
If you want to do this with minimal hassle (IMO), in case you weren't aware, you can use the following incantation, if you have already updated your local `develop` branch to the most recent:
```
git rebase -i HEAD~5 --onto develop
```
(rebase your last 5 commits (on this branch) onto the develop branch)

Happy to explain more if this is confusing.

**Comment by SophiaSR** [comment]
Ah woops, sorry! @brandonspark thanks! I ended up manually copying this time, but if I do the same thing again, will do that instead.

**Pull request closed without merging**
