### PR TITLE
chore: ensure creds aren't persisted by checkout step

### PR DESCRIPTION
**Pull request by spencerdrak**
This is a security measure to ensure that credentials are not persisted after the checkout step is complete.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by brendongo — APPROVED** [review]

**Review by cgdolan — APPROVED** [review]

**Comment by aryx** [comment]
@spencerdrak  can we make a semgrep rule that automatically detects the missing persistence: false?
So that next time someone adds an action with a checkout, he gets a warning.
And in the message of this semgrep rule, can we add a link to a blog post explaining why we need this thing
and why it's not the default value in GHA.

**Comment by aryx** [comment]
@cgdolan do we have a shared place for semgrep rules for GHA? Can we put them in the semgrep-rules repo?
How can we make sure all our repos are scanned with those GHA semgrep rules? Can we change the r2c ruleboard
to add those GHA rules so that each time we have new repos we automatically scan them?

**Comment by aryx** [comment]
This is important, dogfooding semgrep, dogfooding semgrep for devops, dogfooding the app.

**Comment by spencerdrak** [comment]
We're working on a rule @aryx - and yes, we can set it up org-wide in Semgrep App to scan our codebases. working with @werrett  on this. thanks!

**Comment by aryx** [comment]
Fantastic! Keep me updated. Super excited about dogfooding this.

**Pull request merged**
