### PR TITLE
osemgrep: rename __main__.py to simple main.py and remove some shebang

### PR DESCRIPTION
**Pull request by aryx**
test plan:
cd cli
make e2e
wait for green CI check

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by ajbt200128 — CHANGES_REQUESTED** [review]
Is there a reason to remove __main__.py? It's pretty standard to have one (see [docs](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages)), and removing it disables loading pysemgrep as a module. I'm not sure if this will break anything for us, but considering how common this is, it could possibly break things for people outside of the company using semgrep.

**Comment by aryx** [comment]
That's precisely why I did this. People can still load semgrep code, but yes they will break if they use python -m semgrep, which is intended because soon this will not work anymore.

**Comment by aryx** [comment]
As I was doing that I've found a few occurrence of old code in our CI using python -m semgrep and I'm glad it broke so I was able to find it and fix it.

**Comment by aryx** [comment]
If people want to call semgrep, they must use cli/bin/semgrep entry point, not python -m semgrep or whatever other way.

**Comment by aryx** [comment]
I can add comment in main.py to explain the rational behind it maybe.

**Review by ajbt200128 — APPROVED** [review]

**Pull request merged**
