### PR TITLE
Update to latest tree-sitter-ruby via ocaml-tree-sitter-lang

### PR DESCRIPTION
**Pull request by aryx**
This will help https://github.com/returntocorp/semgrep/issues/2231

test plan:
make
make test

### CODE REVIEW

**Comment by aryx** [comment]
This closes https://github.com/returntocorp/semgrep/issues/2097

**Comment by aryx** [comment]
took me 2h30 ... hopefully next time will be shorter.

**Comment by mschwager** [comment]
:tada: :tada: :tada:

**Comment by mjambon** [comment]
> took me 2h30 ... hopefully next time will be shorter.

I know. The plan to improve this is to automate code generation from the tree-sitter-grammars without having to touch the ocaml-tree-sitter repo (#2240).

**Pull request merged**
