### PR TITLE
Do not remove findings with same range but different metavariables

### LINKED ISSUE #3279: matching keys and values in JavaScript objects
Reporting for an external user. When trying to match a structure like those found in package.json, such as:

```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-regular-svg-icons": "^5.15.1",
  },
}
```
(1) The following matches only the first or last entry in the object:
```
{ ...,
  "dependencies": { 
    ...,
    $DEP_NAME: $DEP_VERSION,
    ...
  }
}
```

Desired behavior is that it returns a match for every key under "dependencies". 

Playground url: https://semgrep.dev/s/2b25

Bonus bug, it finds nothing when in JSON mode. Playground url in JSON mode: https://semgrep.dev/s/XLXA

### PR DESCRIPTION
**Pull request by aryx**
This closes https://github.com/returntocorp/semgrep/issues/3279

test plan:
test file included
and
semgrep --config ~/yy/tests/OTHER/rules/misc_field.yaml
~/yy/tests/OTHER/rules/misc_field.js

returns now 22 findings (same range though).

PR checklist:
- [x] changelog is up to date

### CODE REVIEW

**Comment by aryx** [comment]
```
(semgrep) [pad@yrax semgrep (no_dedup)]$ semgrep --config ~/yy/tests/OTHER/rules/misc_field.yaml ~/yy/tests/OTHER/rules/misc_field.js
running 1 rules...
/home/pad/yy/tests/OTHER/rules/misc_field.js
severity:warning rule:home.pad.yy.tests.OTHER.rules.my_pattern_id: "web-vitals" looks like a new dependency! Please check this on https://deps.dev/npm/"web-vitals"/"^0.2.4" to make sure its license is legit, doesn't have lots of known security issues, and that it has enough users.

2:{
3:  "name": "frontend",
4:  "version": "0.1.0",
5:  "private": true,
6:  "dependencies": {
7:    "@fortawesome/fontawesome-svg-core": "^1.2.32",
8:    "@fortawesome/free-regular-svg-icons": "^5.15.1",
9:    "@fortawesome/free-solid-svg-icons": "^5.15.1",
10:    "@fortawesome/react-fontawesome": "^0.1.12",
11:    "@testing-library/jest-dom": "^5.11.4",
-------- [hid 19 additional lines, adjust with --max-lines-per-finding] --------
severity:warning rule:home.pad.yy.tests.OTHER.rules.my_pattern_id: "typescript" looks like a new dependency! Please check this on https://deps.dev/npm/"typescript"/"^4.0.3" to make sure its license is legit, doesn't have lots of known security issues, and that it has enough users.

2:{
3:  "name": "frontend",
4:  "version": "0.1.0",
5:  "private": true,
6:  "dependencies": {
7:    "@fortawesome/fontawesome-svg-core": "^1.2.32",
8:    "@fortawesome/free-regular-svg-icons": "^5.15.1",
9:    "@fortawesome/free-solid-svg-icons": "^5.15.1",
10:    "@fortawesome/react-fontawesome": "^0.1.12",
11:    "@testing-library/jest-dom": "^5.11.4",
-------- [hid 19 additional lines, adjust with --max-lines-per-finding] --------
...
```

**Review by IagoAbal — APPROVED** [review]

**Comment by emjin** [comment]
Relevant slack conversation:
https://returntocorp.slack.com/archives/C01AX0QCEET/p1622757347088700

**Comment by aryx** [comment]
We got a big release, so This is potentially a big change so I wait for the release cut to merge this.

**Review by ievans — COMMENTED** [review]
I don't see any test that has 22 extra findings @aryx, am I missing something?

**Comment by aryx** [comment]
This works now on develop: https://semgrep.dev/s/2b25?version=develop

**Pull request merged**
