### PR TITLE
Use pre-generated Language.{mli,ml}

### PR DESCRIPTION
**Pull request by mjambon**
This gets rid of the jinja build step. See https://github.com/returntocorp/semgrep-langs/pull/32.

CI checks should pass as usual.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by aryx** [comment]
nice!
I still think we should move Language.ml to semgrep-interfaces (And get rid of this semgrep-langs module)
and use more ATD there, but this PR looks fine otherwise.

**Review by aryx — APPROVED** [review]
Love it

**Comment by IagoAbal** [comment]
When it comes to the maturity type
```ocaml
type maturity =
| Alpha
| Beta
| Develop
| Ga
```
it could be better to have them declared in the right order, so that built-in compare works as expected. Also, officially we only have 3 maturity levels, is `Alpha` what we advertise as `Experimental` and `Develop` something we use internally that is below `Experimental` ?

**Comment by mjambon** [comment]
@IagoAbal makes sense. I'll update semgrep-langs to sort maturity by increasing maturity.

**Comment by mjambon** [comment]
```
    @pytest.mark.quick
    def test_no_duplicate_reverse_exts() -> None:
        """
        Ensures one-to-one assumption of mapping from reverse file extensions to language in lang.json
        """
        exts = set()
        for d in LANGUAGE.definition_by_id.values():
            for e in d.reverse_exts:
                if e in exts:
>                   raise Exception(f"Duplicate language key {e}")
E                   Exception: Duplicate language key .py
```
I don't know why we're getting this error only now. This is not a new test and the Python{2,3} extensions haven't changed.

Update: it's subtle stuff that wasn't explained because JSON doesn't support comments.

**Pull request merged**
